### ISSUE TITLE
Planck likelihood installation error

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#100]
Hi everyone, 

I'm currently trying to install the Planck 2018 likelihood in a cluster, but when I try using ./waf install it raises an error I'm not sure I understand, nor have the slightest idea on how to fix it. 

[dbdfteixeira@service0 plc-3.01]$ ./waf configure 
Setting top to                           : /home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01 
Setting out to                           : /home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/build 
Checking for program 'gcc, cc'           : gcc 
Checking for program 'ar'                : /usr/bin/ar 
Checking if the -o link must be split from arguments : yes 
Check gcc version                                    : 4.4.7 
Compile a test code with gcc                         : yes 
Setting architecture flag to                         : ['-m64'] 
Checking for program 'ifort'                         : not found 
ifort not found, defaulting to gfortran (cause: 'Could not find the program ['ifort']
(complete log in /home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/build/config.log)') 
Checking for program 'gfortran, g77'                 : /usr/bin/gfortran 
Checking for program 'ar'                            : /usr/bin/ar 
Checking if the -o link must be split from arguments : yes 
Check gfortran version                               : GNU Fortran (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23) 
Compile a test code with gfortran                    : yes 
retrieve gfortran link line                          : ok 
fortran link line                                    : -L/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01 -lgfortran -lgomp 
Setting install root to                              : /home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01 
Setting install bin directory to                     : /home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/bin 
Setting install lib directory to                     : /home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/lib 
Setting install include directory to                 : /home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/include 
Checking for program 'python'                        : /opt/npad/shared/softwares/python/2.7-anaconda-5.0.1/bin/python 
Checking for python version                          : 2.7.15 
python-config                                        : /opt/npad/shared/softwares/python/2.7-anaconda-5.0.1/bin/python-config 
Asking python-config for pyembed '--cflags --libs --ldflags --embed' flags : not found 
Asking python-config for pyembed '--cflags --libs --ldflags' flags         : yes 
Testing pyembed configuration                                              : yes 
Checking for library dl                                                    : yes 
checking for RTLD_DEFAULT in dl                                            : no 
compile with debug option                                                  : OFF 
Checking for program 'pmc-config'                                          : not found 
Checking for library pmc                                                   : not found 
Checking for library ['lapack', 'blas']                                    : yes 
checking for function 'dposv'                                              : yes 
checking for function 'dtrsv'                                              : yes 
checking for function 'dpotrf'                                             : yes 
checking for function 'dpotrs'                                             : yes 
checking for function 'dpotri'                                             : yes 
checking for function 'dtrtri'                                             : yes 
checking for function 'dtrmm'                                              : yes 
checking for function 'dtrmv'                                              : yes 
checking for function 'dgeqrf'                                             : yes 
checking for function 'dormqr'                                             : yes 
checking for function 'dsyev'                                              : yes 
checking for function 'dgesvd'                                             : yes 
checking for function 'dsymv'                                              : yes 
checking for function 'dgemv'                                              : yes 
checking for function 'dgemm'                                              : yes 
checking for function 'dsyrk'                                              : yes 
checking for function 'dsyr2k'                                             : yes 
checking for function 'daxpy'                                              : yes 
checking for function 'dtrsm'                                              : yes 
checking for function 'dsymm'                                              : yes 
checking for function 'dsyr'                                               : yes 
checking for function 'ddot'                                               : yes 
checking for function 'dsyevd'                                             : yes 
checking for function 'dlamch'                                             : yes 
checking for function 'dsyevr'                                             : yes 
Checking for library ['cfitsio']                                           : yes 
checking for function 'fits_init_cfitsio'                                  : yes 
Python version allows for automatic install                                : yes (2.7.15) 
Checking for program 'python'                                              : /opt/npad/shared/softwares/python/2.7-anaconda-5.0.1/bin/python 
Checking python module 'numpy'                                             : ok 
Checking python module 'astropy'                                           : ok 
Checking for program 'python'                                              : /opt/npad/shared/softwares/python/2.7-anaconda-5.0.1/bin/python 
Checking python module 'cython'                                            : ok 
Checking python module 'cython'                                            : ok 
Checking cython version (>0.20)                                            : 0.26.1 
Checking for program 'cython'                                              : /opt/npad/shared/softwares/python/2.7-anaconda-5.0.1/bin/cython 
Add plugin : 'rel2015'                                                     : ok 

*----------------------------------------------------*
|                                                    |
|   Configure step ok.                               |
|                                                    |
|   run './waf install' now !                        |
|                                                    |
*----------------------------------------------------*

'configure' finished successfully (3.201s)
[dbdfteixeira@service0 plc-3.01]$ ./waf install 
Waf: Entering directory `/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/build'
add plik/component_plugin/rel2015/fg2015.c
add plik/component_plugin/rel2015/corrnoise.c
add plik/component_plugin/rel2015/leakage.c
[ 12/141] Processing src/gibbs/comm_lowl_mod_dist.f90
[ 19/141] Compiling src/lenslike/plenslike/plenslike_dat_full.c
/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/src/gibbs/comm_lowl_mod_dist.f90:73.67:

  type(comm_lowl_data), dimension(MAX_N_LOWL), private :: comm_lowl
                                                                   1
Error: Object 'comm_lowl' at (1) must have the SAVE attribute for default initialization of a component

Waf: Leaving directory `/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/build'
Build failed
 -> task in 'gibbs' failed with exit status 1 (run with -v to display more information)
[dbdfteixeira@service0 plc-3.01]$ ./waf install -v
Waf: Entering directory `/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/build'
add plik/component_plugin/rel2015/fg2015.c
add plik/component_plugin/rel2015/corrnoise.c
add plik/component_plugin/rel2015/leakage.c
[ 12/141] Processing src/gibbs/comm_lowl_mod_dist.f90
10:37:26 runner ['/usr/bin/gfortran', '-DGFORTRAN', '-ffixed-line-length-0', '-ffree-line-length-0', '-m64', '-fPIC', '-fopenmp', '-I../include', '-DPYTHONDIR="/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/lib/python2.7/site-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYTHON_H=1', '-DHAVE_LAPACK_CLIK_H=1', '-DHAVE_FITSIO_H=1', '-DHAS_LAPACK', '-DLAPACK_CLIK', '-c', '-o/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/build/src/gibbs/comm_lowl_mod_dist.f90.3.o', '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/src/gibbs/comm_lowl_mod_dist.f90']
/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/src/gibbs/comm_lowl_mod_dist.f90:73.67:

  type(comm_lowl_data), dimension(MAX_N_LOWL), private :: comm_lowl
                                                                   1
Error: Object 'comm_lowl' at (1) must have the SAVE attribute for default initialization of a component

Waf: Leaving directory `/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/build'
Build failed
 -> task in 'gibbs' failed with exit status 1: 
	{task 140734286901072: fc comm_lowl_mod_dist.f90 -> comm_lowl_mod_dist.f90.3.o,comm_lowl_mod_dist.mod}
['/usr/bin/gfortran', '-DGFORTRAN', '-ffixed-line-length-0', '-ffree-line-length-0', '-m64', '-fPIC', '-fopenmp', '-I../include', '-DPYTHONDIR="/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/lib/python2.7/site-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYTHON_H=1', '-DHAVE_LAPACK_CLIK_H=1', '-DHAVE_FITSIO_H=1', '-DHAS_LAPACK', '-DLAPACK_CLIK', '-c', '-o/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/build/src/gibbs/comm_lowl_mod_dist.f90.3.o', '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/src/gibbs/comm_lowl_mod_dist.f90']
[dbdfteixeira@service0 plc-3.01]$ 

P.S. : I have previoulsy installed plc 2018 on my PC and have had no issues. But this is also my first time using a cluster so I'm a newbie on that one :P

**Comment by ivandebono** [comment]
Hi,

Which cluster are you using?

**Comment by DinorahBarbosa** [comment]
> Hi,
> 
> Which cluster are you using?

I'm using NPAD cluster at Federal University of Rio Grande do Norte (UFRN) in Brazil

**Comment by nkhadka21** [comment]
Hi Barbosa,
did you solve this issue? I also got this problem. I would be grateful if you could suggest me the solution.

Thank you,

Narayan

**Comment by DinorahBarbosa** [comment]
Hi @nkhadka21! In my case I later found out that the cluster had Planck 2018 likelihood installed as requested by a fellow researcher. So I abandoned this try and used that one. I recommend you reach out to the support for the cluster you are using since they will most likely know how to solve this type of error quickly.

**Comment by nkhadka21** [comment]
Thanks Dinorah.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
