### ISSUE TITLE
add_derived.py issues: multiprocessing and other

### ISSUE THREAD

**Issue by nblinov** [brinckmann/montepython_public#101]
Hi, 

I've ran into a couple of issues trying to add derived parameters to existing chains. 
1)  Parallel processing in add_derived.run does not work due to the following error
`  File "/home/nblinov/HEP/montepython_public-3.2/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/nblinov/HEP/montepython_public-3.2/montepython/run.py", line 44, in run
    sampler.run(cosmo, data, command_line)
  File "/home/nblinov/HEP/montepython_public-3.2/montepython/sampler.py", line 60, in run
    der.run(cosmo, data, command_line)
  File "/home/nblinov/HEP/montepython_public-3.2/montepython/add_derived.py", line 75, in run
    pool.map(extend_chain_star, args)
  File "/home/nblinov/miniconda3/envs/py27/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/nblinov/miniconda3/envs/py27/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: self._err,self.celf,self.err cannot be converted to a Python object for pickling
`
 I briefly looked into this, and it seems to be due to the fact that the data and cosmo objects passed to extend_chain cannot be pickled. Everything works if one replaces the multiprocessing code with `for elem in chains:
        extend_chain(data, cosmo, command_line, target_folder, elem, new_derived)`
which evaluates one chain at a time.

2) In add_derived.extend_chain, there is a small bug in these lines (also noted in #https://github.com/baudren/montepython_public/issues/66#issue-188023519) 
where elem should be name in the last line
```
for name, value in derived.iteritems():
    data.mcmc_parameters[name]['current'] = value
for name in derived.iterkeys():
    data.mcmc_parameters[elem]['current'] /= data.mcmc_parameters[elem]['scale']
```
Fix:
```
for name, value in derived.iteritems():
    data.mcmc_parameters[name]['current'] = value/data.mcmc_parameters[name]['scale']
```

**Comment by brinckmann** [comment]
Hi,

Thanks, this is fixed for the shortly upcoming version 3.3.

Best,
Thejs
