### ISSUE TITLE
Detecting epty folder, logging parameter file

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#104]
HI guys, 

First time running MP in a cluster, I've been getting the following error upon initialization:

/!\ Detecting empty folder, logging the parameter file

Which has caused my job to timed out (I asked for 2 nodes, 2 tasks per node and 40000 chains, time =12hours). What I don't understand is that even if the time was insufficient, MP should have generated at least some chains. but I've got nothing. I'm copying my .sh file below. Please help me understand what's going on. 

#!/bin/bash
#SBATCH --job-name=Planck_2018
#SBATCH --nodes=2
#SBATCH --time=0-12:0
#SBATCH --ntasks-per-node=2

srun python ~/montepython_public/montepython/MontePython.py run -p ~/montepython_public/input/planck18.param -o ~/montepython_public/chains/planck2018 --conf ~/montepy$ontepython_public/planck18.conf -N 40000

**Comment by brinckmann** [comment]
Hi Dinorah,

This is a common problem when running on some clusters. I can't tell you why it happens, but as a result it is recommended that before submitting a job you create the folder running with the -f 0 flag, i.e.:
`python ~/montepython_public/montepython/MontePython.py run -p ~/montepython_public/input/planck18.param -o ~/montepython_public/chains/planck2018 --conf ~/montepy$ontepython_public/planck18.conf -f 0`

Remember to delete the old folder first. Then you should be able to submit the job as usual.

One other thing, I recommend piping the output to a log file, so you can check the status while it's on-going (also limits the risk of memory issues that may happen on some systems), e.g. add at the end on the same line as your srun command `&> ~/montepython_public/chains/planck2018/output.log`

Best,
Thejs

**Comment by DinorahBarbosa** [comment]
Thanks Thejs! Will try :D

**Comment by DinorahBarbosa** [comment]
Hi Thejs, 

Tried running as you said, but when I run the comand, initialization starts normally

```
python ~/montepython_public/montepython/MontePython.py run -p ~/montepython_public/input/planck18.param -o ~/montepython_public/chains/planck2018 --conf ~/montepython_public/planck18.conf -f 0 
Running Monte Python v3.3.0

with CLASS v2.7.1
 /!\ Running CLASS from a non version-controlled repository

Testing likelihoods for:
 ->Planck_highl_TT, Planck_lowl_EE, Planck_lowl_TT, Planck_lensing, Pantheon, cosmic_clocks_2016, bao_boss_dr12

----
clik version 3be036bbb4f9
  smica
Checking likelihood '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22_TT.clik' on test data. got -380.341 expected -380.341 (diff -1.0822e-08)
----
Initializing SimAll
----
clik version 3be036bbb4f9
  simall simall_EE_BB_TE
Checking likelihood '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version 3be036bbb4f9
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
```

And when it gets here it doesn't do anything. I waited for some time and nothing happened. Perhaps a different problem, as it doesn't happens on my personal computer. 

```
Checking lensing likelihood '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8.clik_lensing' on test data. got -4.42102

```
Bests, 

Dinorah

**Comment by brinckmann** [comment]
Hi Dinorah,

I'm sorry, I wasn't quite clear. Please create the directory with the command above while running on the front end dialog system (i.e. not submitting a job, just running montepython directly). Then you can submit the job as normal. Since it only takes a moment, creating the directory by running on the front end shouldn't be a problem.

Best,
Thejs

**Comment by DinorahBarbosa** [comment]
Hi Thejs, 

I did understand what you meant :). That's exactly what I did. What I mentioned above happens as I run montepython normally, inside the cluster, but without submitting the job. It runs fine and then stays endlessly on the following line:

` Checking lensing likelihood '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8.clik_lensing' on test data. got -4.42102`

Bests, 

Dino

**Comment by brinckmann** [comment]
Oh wow, that's strange. Can you add some prints to see if it gets stuck inside of the Planck likelihoods or after? You want to look at the Likelihood_clik class in montepython/likelihood_class.py that starts on line 858. You see line 883-894 it calls clik. I would put print statements before and after to see if that segment runs normally.

If the code gets stuck here I would also add print statements inside the nested try and except line 885-891 to see which it ends up at. Ultimately I would try to comment the try/except (i.e. comment try, remove the following indent, and comment the except plus the following line(s)), first the nested one on line 885-891 and then the outer one 882-909. The idea here is to get the code to spit out an error if clik is producing one.

If the code gets stuck later we'll have to try to pinpoint where that happens.

Best,
Thejs

**Comment by DinorahBarbosa** [comment]
Hi Thejs, 

I'm not a 100% sure I did it right..You meant for me to print self.clik right? If so, that's what I asked for in Likelihood_clik. Here's the result I've got 

```
[dbdfteixeira@service0 ~]$ python ~/montepython_public/montepython/MontePython.py run -p ~/montepython_public/input/planck18.param -o ~/montepython_public/chains --conf ~/montepython_public/planck18.conf -f 0 
Running Monte Python v3.3.0

with CLASS v2.7.1
 /!\ Running CLASS from a non version-controlled repository

Testing likelihoods for:
 ->Planck_highl_TT, Planck_lowl_EE, Planck_lowl_TT, Planck_lensing, Pantheon, cosmic_clocks_2016, bao_boss_dr12

Traceback (most recent call last):
  File "/home/dbdfteixeira/montepython_public/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/dbdfteixeira/montepython_public/montepython/run.py", line 32, in run
    custom_command)
  File "/home/dbdfteixeira/montepython_public/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/dbdfteixeira/montepython_public/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
  File "/home/dbdfteixeira/montepython_public/montepython/data.py", line 356, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/dbdfteixeira/montepython_public/montepython/data.py", line 485, in initialise_likelihoods
    elem, elem, folder, elem))
  File "<string>", line 1, in <module>
  File "/home/dbdfteixeira/montepython_public/montepython/likelihood_class.py", line 894, in __init__
    print(self.clik)
AttributeError: 'Planck_highl_TT' object has no attribute 'clik'
```

**Comment by brinckmann** [comment]
No I just meant some debugging print statement like
print('Before calling clik')
...
print('After calling clik')

In order to see if the code ever gets past calling clik or if it gets stuck there. But also your error message now makes me wonder what's going on. Did you put that print statement after self.clik is defined?

Best,
Thejs

**Comment by DinorahBarbosa** [comment]
Hi Thejs, 

Oh, I see. Like this?
```

try:
            print('Before calling clik')
            if self.lensing:
                self.clik = clik.clik_lensing(self.path_clik)
                try:
                    self.l_max = max(self.clik.get_lmax())
                # following 2 lines for compatibility with lensing likelihoods of 2013 and before
                # (then, clik.get_lmax() just returns an integer for lensing likelihoods;
                # this behavior was for clik versions < 10)
                except:
                    self.l_max = self.clik.get_lmax()
            else:
                self.clik = clik.clik(self.path_clik)
                self.l_max = max(self.clik.get_lmax())
                print('After calling clik')

```

And here's the result I got: 
```

Running Monte Python v3.3.0

with CLASS v2.7.1
 /!\ Running CLASS from a non version-controlled repository

Testing likelihoods for:
 ->Planck_highl_TT, Planck_lowl_EE, Planck_lowl_TT, Planck_lensing, Pantheon, cosmic_clocks_2016, bao_boss_dr12

Before calling clik
----
clik version 3be036bbb4f9
  smica
Checking likelihood '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22_TT.clik' on test data. got -380.341 expected -380.341 (diff -1.08219e-08)
----
After calling clik
Before calling clik
Initializing SimAll
----
clik version 3be036bbb4f9
  simall simall_EE_BB_TE
Checking likelihood '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
After calling clik
Before calling clik
----
clik version 3be036bbb4f9
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
After calling clik
Before calling clik
Checking lensing likelihood '/home/dbdfteixeira/planck2018/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8.clik_lensing' on test data. got -4.42102
```

**Comment by brinckmann** [comment]
Looks like it gets stuck in the lensing likelihood. You can confirm this by removing the lensing likelihood from your param file and see if it runs. I'm not really sure what's wrong with the likelihood, though, or how to debug it.

Best,
Thejs

**Comment by DinorahBarbosa** [comment]
I'll try to reinstall everything to see if there's any difference. Will post the updates here.

**Comment by DinorahBarbosa** [comment]
Hi Thejs,

Find out that the problem was actualy in CLASS, the cluster I am using wasn't giving permission for classy to write some files in the python path. I simply installed python on my personal environment and everything is running smoothly rn.
