### ISSUE TITLE
Bug in Likelihood_clik class for Planck -- no non-linearities computed

### ISSUE THREAD

**Issue by janinarenk** [brinckmann/montepython_public#105]
Hi Thejs, 

I think there is a bug in the initialisation of the Likelihood_clik class to compute the Planck likelihoods. At least to reproduce what is done in the Planck papers [1502.01589,1807.06209] non-linearities of the power spectrum have to be included to get lensing right. The patch to fix it is attached. 

Cheers,
Janina
[diff-likelihood_class.txt](https://github.com/brinckmann/montepython_public/files/4162459/diff-likelihood_class.txt)

**Comment by brinckmann** [comment]
Hi Janina,

We ended up adding the change to the relevant Planck example param files, where we now ask for non-linear treatment (halofit) and provide a warning.

Best,
Thejs
