### ISSUE TITLE
Run MonthePython with Planck 2018 likelihoods.

### ISSUE THREAD

**Issue by MarisolJC** [brinckmann/montepython_public#106]
Hi!

I'm trying to use the Planck 2018 likelihoods, I have already installed the "clik" library, I typed "source bin/clik_profile.sh" without problems, I also modified the path in default.conf of MontePython as it should be, but when I try to run the likelihood typing:
$ python montepython/MontePython.py run -p base2018TTTEEE.param -o base2018TTTEEE/ -N 5000 --silent
after
$ source /home/marisol/Documentos/code/montepython_public-3.2/planck/code/plc_3.0/plc-3.01/bin/clik_profile.sh

I get the following error message:

/!\ Running CLASS from a non version-controlled repository
Cannot use clik wrapper (cause = 'No module named lkl')
Cannot use clik_lensing wrapper (cause = 'No module named lkl_lensing')
Traceback (most recent call last):
File "montepython/MontePython.py", line 40, in
sys.exit(run())
File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/run.py", line 31, in run
custom_command)
File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/run.py", line 190, in safe_initialisation
cosmo, data, command_line, success = initialise(custom_command)
File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/initialise.py", line 66, in initialise
data = Data(command_line, path)
File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/data.py", line 352, in init
self.initialise_likelihoods(self.experiments)
File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/data.py", line 481, in initialise_likelihoods
elem, elem, folder, elem)
File "", line 1, in
File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/likelihood_class.py", line 870, in init
"and try again.")
montepython.io_mp.MissingLibraryError:

Missing Library Error:
/|\ You must first activate the binaries from the Clik distribution. Please
/o\ run :
]$ source /path/to/clik/bin/clik_profile.sh
and try again.

I made sure to do NOT have any old Planck likelihoods sourced, so... I don't know what else I can do.
COULD YOU PLEASE HELP ME?

Thanks.

**Comment by ivandebono** [comment]
If you look at the Planck .data files in montepython/likelihoods (I'm using one as an example), this line means that Montepython searches for the clik path defined in the .conf file, then climbs up three levels to the folder called "planck", then searches for the file "planck/baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik".

`Planck_highl_TTTEEE.path_clik = os.path.join(data.path['clik'], '../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik')`

If you're using the Montepython Planck likelihood files out of the box, make sure the file structure for your Planck folder is as follows:

If your clik profile is here:

**/home/marisol/Documentos/code/montepython_public-3.2/planck/code/plc_3.0/plc-3.01/bin/clik_profile.sh**

then your Planck data (plik) should be here:
 **/home/marisol/Documentos/code/montepython_public-3.2/planck/baseline/plc_3.0/ etc**

Taking the example above, **plik_rd12_HM_v22b_TTTEEE.clik** should be here:
**/home/marisol/Documentos/code/montepython_public-3.2/planck/baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik**

Your .conf file should contain the line:
`path['clik']        = '/home/marisol/Documentos/code/montepython_public-3.2/planck/code/plc_3.0/plc-3.01'`

**Comment by MarisolJC** [comment]
Hi! 

Thanks for your response. I looked at the Planck .data files in montepython/likelihoods, and made sure that the "Planck_highl_TTTEEE.path_clik=" was searching for the correct files. Even so, I modified (in my opinion, doesn't alter anything) to all the Planck .data files as follows:

**Planck_lowl_EEBB.path_clik = os.path.join(data.path['clik'], '/home/marisol/Documentos/code/montepython_public-3.2/planck/baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EEBB_Aplanck_B.clik')**

My .conf file contain the line:

**root = '/home/marisol/Documentos/code'

path['cosmo']		= root+'/class_public'
path['clik']        = root+'/montepython_public-3.2/planck/code/plc_3.0/plc-3.01'**

I thought the problem might be that I didn't add  **'source /path/to/planck/code/plc_3.0/plc-3.01/bin/clik_profile.sh'** to my **.bashrc** but, when I runned the chains again I got the same error message described above. 

Marisol.

**Comment by ivandebono** [comment]
Hi, 

The line you modified in the Planck .data files means that MontePython will look for the .clik file here:

**'/home/marisol/Documentos/code/montepython_public-3.2/planck/code/plc_3.0/plc-3.01/home/marisol/Documentos/code/montepython_public-3.2/planck/baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EEBB_Aplanck_B.clik**

This is clearly wrong. 

If you modify the line as follows, it should work:

**Planck_lowl_EEBB.path_clik='/home/marisol/Documentos/code/montepython_public-3.2/planck/baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EEBB_Aplanck_B.clik'**

Better still, use this:
**Planck_lowl_EEBB.path_clik = os.path.join(data.path['clik'], '../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EEBB_Aplanck_B.clik')**

**Comment by MarisolJC** [comment]
Now I have:

**Planck_lowl_EE.path_clik = os.path.join(data.path['clik'], '../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik')**

But the problem still there...

**Comment by DinorahBarbosa** [comment]
Hi Marisol!

I also had problems with the plc 2018 lately...Did you take a look at the messages when you install the code, that is, when you type .\waf configure? Also, did you make sure of using the lapack from the mkl package?

**Comment by MarisolJC** [comment]
Hi Dinorah!

When I type **./waf configure --lapack_mkl=${MKLROOT} --install_all_deps**, after a few minutes, it appears to me the following message:

```
No suitable python distribution found 
Cause : 'maximum recursion depth exceeded' 
Compilation will continue without it (but I strongly advise that you install it) 
Add plugin : 'rel2015'                                                     : ok 
*----------------------------------------------------*
   Configure partial.                               
   You can build now but you will be lacking some   
   features.                                        
   run './waf install' now !
```               


I am using Python version 2.7. Do you think the problem is that the configure was partial?

Thanks, 
Marisol.

**Comment by DinorahBarbosa** [comment]
Hi Marisol!

I do think this could be the problem. Can you check on your computer that you have all the needed packages to install the planck likelihood? You can find them listed in the readme file of the code. Also make sure your python version is 2.7.8 minimum!

**Comment by MarisolJC** [comment]
Hi again! 

I checked I did not have Pyfits installed, which I read was optional but it seems that it is not, so, I installed it but, now I get another error when running MontePython:

> 
> /!\ Running CLASS from a non version-controlled repository
> Traceback (most recent call last):
>   File "montepython/MontePython.py", line 40, in <module>
>     sys.exit(run())
>   File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/run.py", line 31, in run
>     custom_command)
>   File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/run.py", line 190, in safe_initialisation
>     cosmo, data, command_line, success = initialise(custom_command)
>   File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/initialise.py", line 66, in initialise
>     data = Data(command_line, path)
>   File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/data.py", line 352, in __init__
>     self.initialise_likelihoods(self.experiments)
>   File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/data.py", line 481, in initialise_likelihoods
>     elem, elem, folder, elem)
>   File "<string>", line 1, in <module>
>   File "/home/marisol/Documentos/code/montepython_public-3.2/montepython/likelihood_class.py", line 864, in __init__
>     import clik
>   File "/home/marisol/Documentos/code/montepython_public-3.2/planck/code/plc_3.0/plc-3.01/lib/python/site-packages/clik/__init__.py", line 10, in <module>
>     from .lkl import clik
>   File "__init__.pxd", line 918, in init clik.lkl
> ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
> 


...

**Comment by ivandebono** [comment]
Hello again,

Could you try running the latest version of MontePython with Python 3? I've had problems with numpy in Python 2 when using other packages.

**Comment by DinorahBarbosa** [comment]
Marisol, can you tell me which compilers (c and python) are you using?

**Comment by MarisolJC** [comment]
Hello!

The problem has been solved. I am using **gcc** and **gfortran** compilers. The solution was, running the latest version of MontePython with Python 3.7.x instead of Python 2.7.17 (in my case).

Thank you so much both for your help! :smiley:
