### ISSUE TITLE
Planck_actspt likelihood giving error

### ISSUE THREAD

**Issue by lmaingi** [brinckmann/montepython_public#11]
When running Monte Python with the Planck_actspt likelihood I get the error:

The path to the .clik file for the likelihood Planck_actspt was not found where indicated: ...

However the .clik file (from http://pla.esac.esa.int/pla/aio/product-action?COSMOLOGY.FILE_ID=COM_Data_Likelihood-actspt_R1.10.tar) is in exactly the location listed by the error, one level up from the directory for the Planck likelihood code. I am using plc v2.0. Is this a bug in Monte Python or an incompatibility between the Planck_actspt likelihood and the 2015 version of the plc?

**Comment by brinckmann** [comment]
Are you sure you sourced everything correctly?
Best,
Thejs
