### ISSUE TITLE
Pantheon supernovae data likelihood is outdated 

### ISSUE THREAD

**Issue by snesseris** [brinckmann/montepython_public#110]
The Pantheon supernovae data likelihood is outdated for a while now, as Scolnic has released (15 months ago!) a new distance file with updated heliocentric redshifts, see [1].

To fix, include the "lcparam_full_long_zhel.txt" in /data/Pantheon and change line 2 in /data/Pantheon/pantheon.dataset  as follows:

`data_file = data/lcparam_full_long.txt`

to 
`data_file = data/lcparam_full_long_zhel.txt`

The effect is <img src="https://render.githubusercontent.com/render/math?math=\delta \chi^2\sim1"> and 0.5% in the parameters.

[1] https://github.com/dscolnic/Pantheon

**Comment by brinckmann** [comment]
Thank you, Savvas! We're putting out a new version this week featuring H0licow, where this will also be updated.

Best,
Thejs
