### ISSUE TITLE
Bug in bao_fs_boss_dr12 likelihood

### ISSUE THREAD

**Issue by franyancr** [brinckmann/montepython_public#112]
There is a bug that was introduced in bringing MontePython compatible with Python 3. In these statements of the bao_fs_boss_dr12 likelihood, we pass a single-entry dictionary where both the key and the value are strings. 

 self.need_cosmo_arguments(data, {'P_k_max_h/Mpc': '1.'})
 self.need_cosmo_arguments(data, {'z_max_pk': '1.'})

The need_cosmo_arguments is a method of the likelihood_class, which has a statement on line 286:

float(data.cosmo_arguments[key]) < value

In Python 3, the value here is literally what was the value in the passed dictionary, which here is a string. So the code is trying to compare a float to a string and crash. So you get a TypeError:

TypeError: '<' not supported between instances of 'float' and 'str'

Changing the string to a float fixes the issue:

self.need_cosmo_arguments(data, {'P_k_max_h/Mpc': 1.})
self.need_cosmo_arguments(data, {'z_max_pk': 1.})

I'm using Python 3.7.4 on linux.

**Comment by brinckmann** [comment]
Thanks, Francis! I'll include the fix in the next version.

Best,
Thejs

**Comment by brinckmann** [comment]
Also note that the chi squared computation on line 96 should NOT have an extra log:
`chi2 = np.log(np.dot(np.dot(data_array,inv_cov_data),data_array))`
should be
`chi2 = np.dot(np.dot(data_array,inv_cov_data),data_array)`
This was fixed for bao_boss_dr12 a long time ago, but somehow I didn't propagate the bugfix to bao_fs_boss_dr12, my apologies!

Best,
Thejs

**Comment by jcolinhill** [comment]
Hi Thejs,
I think it would be important to fix the bug on line 96 in bao_fs_boss_dr12 ASAP, as this has affected multiple papers in the past several months.  The best-fit chi^2 values for this likelihood (in LCDM) should be around ~8, not ~2, which is what the code outputs due to this bug.
Thanks,
Colin

**Comment by brinckmann** [comment]
Hi Colin,

Ah damn, thanks for pointing that out! I should have known better than to assume people would check the issues page. That's my bad. I'll fix it this week.

Best,
Thejs

**Comment by jcolinhill** [comment]
No worries!  I only realized it existed today, myself :-)

Thanks,
Colin

**Comment by brinckmann** [comment]
Okay both bugfixes have (finally) been pushed to 3.3!

Best,
Thejs
