### ISSUE TITLE
Problem with the --extra file

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#113]
Hi, 

I want to plot my chains, and I've modified the example.plot to my dataset. However, I get the following 

`TypeError: file() argument 2 must be string, not dict
`
When running the command info --extra myfile.plot

[planck2018.plot.txt](https://github.com/brinckmann/montepython_public/files/4252027/planck2018.plot.txt)

**Comment by SuvedhaNaik** [comment]
Hello, 

I'm facing the same problem. Anybody fixed this?

**Comment by DinorahBarbosa** [comment]
Hi! I have. My problem was on the input file actually. In particular, my parameter data.over_sampling was in the incorrect order: 

`data.over_sampling=[1, 5, 1]
`

Which I have fixed to:

`data.over_sampling=[1, 1, 5]
`

**Comment by brinckmann** [comment]
@SuvedhaNaik The issue with plot files requires a modification of montepython/analyze.py described in issue #98 . I apologize, due to the pandemic bug fixes are lagging behind. I'll try to have something out in the next weeks that collects all the bug fixes reported on the issues page.

Best,
THejs

**Comment by SuvedhaNaik** [comment]
@brinckmann I did change the montepython/analyze.py file. That fixed the problem. Thanks a lot for your reply. 

Thank you for your reply @DinorahBarbosa
