### ISSUE TITLE
Problem with --extra command

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#114]
Hi, 
I've been trying to plot my data with the info --extra command but I'm getting the following error

`TypeError: open() argument 2 must be str, not dict`

Which seems trivial, but I don't understand why it's happening. My plot file is attached
[planck2018.plot.txt](https://github.com/brinckmann/montepython_public/files/4252950/planck2018.plot.txt)

**Comment by brinckmann** [comment]
Hi Dinorah,

The update to Python3 introduced a bug in the analyze module when trying to use .plot files.

If you change line 2136 from
`exec(open(command_line.optional_plot_file,plot_file_vars).read())`
to
`exec(open(command_line.optional_plot_file).read(),plot_file_vars)`
then it should work.

I apologize for the inconvenience and will add the bugfix in the next update!

Best,
Thejs

**Comment by DinorahBarbosa** [comment]
Solved it. Thanks!
