### ISSUE TITLE
Small bug when reading in the bestfit file with Python 3.

### ISSUE THREAD

**Issue by flo1984** [brinckmann/montepython_public#117]
Hi everyone,

I want to report a minor bug, which occurs when using the -b argument to read-in the best-fit file. It produces an error in the function call 

> sys.stdout.write('from input file    : ', elem, ' = ')

the syntax of which seems to be incompatible with Python 3 (that's my guess). Replacing the commas by "+" resolves the issue. 

Thanks, Florian

**Comment by brinckmann** [comment]
Thank you, it will be fixed for the next release.

Best,
Thejs

**Comment by brinckmann** [comment]
This has (finally) been fixed. Thanks!
