### ISSUE TITLE
How to show chi2 from given model params?

### ISSUE THREAD

**Issue by bnuastro** [brinckmann/montepython_public#12]
Dear MP team,
I want to check the lnL at given param and stop the MCMC.
Is there any way to enable this?
Best,
Bnu

**Comment by brinckmann** [comment]
In run mode use flag --display-each-chi2 , probably with flag -f 0 so you don't make a jump and compute the values for the bestfit or param file values.
Best,
Thejs

**Comment by bnuastro** [comment]
Thank you very much! It works! 
Best!
