### ISSUE TITLE
Process is always sleeping

### ISSUE THREAD

**Issue by Jimmy022** [brinckmann/montepython_public#123]
Hi，

I'm trying to run the program. I used SSH to connect to the remote server to run it. I used the command  "nohup nice -10 mpirun -np 12 python montepython/MontePython.py run -p wcdm2.param -o  plank/wcdm2  -N 1000000 -f 0.8 --update 50 &". But the calculation process often stops by itself before the end. Then I used  "top" to check the status of the process as follows. the state of process is "sleeping".

I tried without "nohup nice -10" and had the same problem.  Without "mpirun -np 12" Then it would be fine (But it would take much more time for calculation of course). I used "strace -p PID" , and the return was "futex(0x366fc14, FUTEX_WAIT_PRIVATE, 688912, NULL".

Does anyone know what causes this? Thanks for help!

  PR  NI    VIRT    RES         SHR S  %CPU %MEM     TIME+  COMMAND
  30  10    9.9g  393740  30896 R  1899   0.0          3898:40  python
  30  10    9.9g  389348  30884 S 699.7   0.0           3445:46  python
  30  10    9.9g  390724  30896 S 499.7   0.0           2970:11  python
  30  10    9.9g  472172  30884 S 399.7   0.0           2672:03  python
  30  10   10.0g 513228  31988 S 300.0   0.0           2977:31  python
  30  10    9.9g  441416  30896 S 300.0   0.0           3028:44  python
  30  10    9.9g  413316  42776 S 299.7   0.0           2910:35  python
  30  10    9.9g  391824  30912 S 199.7   0.0           2994:59  python

Best,
Jimmy

**Comment by brinckmann** [comment]
Hi Jimmy,

I'm a bit at a loss here, it seems to be a server or mpi problem? Do you have mpi4py correctly installed? I.e. start python and try import mpi4py.

Note that MontePython is perfectly capable of running without MPI (as long as you're not trying to use a different sampler like MultiNest), so you could try to launch parallel jobs without mpi. In that case there will be multiple "master" chains, i.e. multiple chains updating the covmat with all of them periodically loading the most recently produced one, irrespective of which chain generated it. However, this doesn't slow down convergence time as any loss in efficiency due to calculating the covmat more often is generally made up for by more efficiently adapting the covmat.

Best,
Thejs

**Comment by Jimmy022** [comment]
Hi Thejs,

Thank you for your advice!
I tried import mpi4py and nothing wrong. Then I tried the other idea by using the command "for n in {1..12}; do nohup python  montepython/MontePython.py run -p wcdm2.param -o plank/wcdm2 -N 1000000 -f 0.8 --update 50 &; done". And It worked. 
But this method seems slow down the calculation a lot. It takes two hours to calculate more than 5000 points for each process, while the MPI method would take less than half an hour. May I ask is the method I used correct ?

Best,
Jimmy

**Comment by Jimmy022** [comment]
> Hi Jimmy,
> I'm a bit at a loss here, it seems to be a server or mpi problem? Do you have mpi4py correctly installed? I.e. start python and try import mpi4py.
> Note that MontePython is perfectly capable of running without MPI (as long as you're not trying to use a different sampler like MultiNest), so you could try to launch parallel jobs without mpi. In that case there will be multiple "master" chains, i.e. multiple chains updating the covmat with all of them periodically loading the most recently produced one, irrespective of which chain generated it. However, this doesn't slow down convergence time as any loss in efficiency due to calculating the covmat more often is generally made up for by more efficiently adapting the covmat.
> Best,
> Thejs

Hi Thejs,

Thank you for your advice!
I tried import mpi4py and nothing wrong. Then I tried the other idea by using the command "for n in {1..12}; do nohup python  montepython/MontePython.py run -p wcdm2.param -o plank/wcdm2 -N 1000000 -f 0.8 --update 50 &; done". And It worked. 
But this method seems slow down the calculation a lot. It takes two hours to calculate more than 5000 points for each process, while the MPI method would take less than half an hour. May I ask is the method I used correct ?

Best,
Jimmy

**Comment by brinckmann** [comment]
Note that MontePython can use both MPI and OMP. Specifically, OMP affects CLASS calculations (up to, I think, 16 cores per process for most modules) and most MontePython likelihood calculations (but not as efficient for the actual sampling, which usually takes much less time than the other two), whereas MPI governs behavior of multiple chains running in parallel.

I'm not familiar enough with terminal/server behavior to know how these two interact with OMP vs MPI when running on multiple cores via mpirun, but it may be that when you're running 12 processes via mpirun they effectively share 12 cores between all the chains (so if one chain isn't using 100% of the CPU, the others take up the unused computational time), whereas running in parallel forces each chain to run on a single core. I'm not sure if that is enough to account for the factor ~4 difference you notice. The other explanation might simply be that someone else might have been running something on the same priority and you were sharing the cores. Would you be able to verify if that was the case?

A priori I would have expected it the two methods to be comparable in computational time to around ~10%

Best,
Thejs

**Comment by Jimmy022** [comment]
> Note that MontePython can use both MPI and OMP. Specifically, OMP affects CLASS calculations (up to, I think, 16 cores per process for most modules) and most MontePython likelihood calculations (but not as efficient for the actual sampling, which usually takes much less time than the other two), whereas MPI governs behavior of multiple chains running in parallel.
> I'm not familiar enough with terminal/server behavior to know how these two interact with OMP vs MPI when running on multiple cores via mpirun, but it may be that when you're running 12 processes via mpirun they effectively share 12 cores between all the chains (so if one chain isn't using 100% of the CPU, the others take up the unused computational time), whereas running in parallel forces each chain to run on a single core. I'm not sure if that is enough to account for the factor ~4 difference you notice. The other explanation might simply be that someone else might have been running something on the same priority and you were sharing the cores. Would you be able to verify if that was the case?
> A priori I would have expected it the two methods to be comparable in computational time to around ~10%
> Best,
> Thejs

Hi Thejs,

I'm sure that it wasn't caused by others , because I tried many times. An alternative I can try is to run multiple chains for as long as mpirun can work and then resume running mpirun. But I don't know if I can start multiple chains (1—12) in parallel at the same time. I used the command like "python montepython/MontePython.py run -r plank/wcdm2/2020-04-23_1000000__1.txt  -N 500000 -f 0.8". 
Is there a way to continue all the chains in one folder at the same time?

Best,
Jimmy

**Comment by brinckmann** [comment]
To use restart in the context of parallel jobs you will need to use the --chain_number flag passing the number indicated at the end of the restarted file, as -r otherwise requires mpi.

Best,
Thejs

**Comment by Jimmy022** [comment]
> To use restart in the context of parallel jobs you will need to use the --chain_number flag passing the number indicated at the end of the restarted file, as -r otherwise requires mpi.
> Best,
> Thejs

It seems that I misunderstood the usage of -r. Do you mean that if I use a command like "mpirun -np 4 python montepython/MontePython.py run -r lcdm/2020-04-25_1000__1.txt  -N 1000 -f 0.8" (I have 4 chains in the folder), it means that I restart the previous 1-4 chains?  I saw in return that "Restarting from lcdm/2020=04-25_1000_1.txt" were repeated four times, and I thought it had started four new chains from 1, instead of restarting previous 1-4 chains.

Best,
Jimmy

**Comment by brinckmann** [comment]
Hi jimmy,

The first time you launch a set of chains you would not run with the -r flag, that is for resuming (restarting) runs.

Assume you have four chains:
lcdm/2020-04-25_1000__1.txt
lcdm/2020-04-25_1000__2.txt
lcdm/2020-04-25_1000__3.txt
lcdm/2020-04-25_1000__4.txt

If you're running with mpi you would write
`mpirun -np 4 python montepython/MontePython.py run -r lcdm/2020-04-25_1000__1.txt  -N 1000 -f 0.8`
and it would restart all four chains, copying them to four new chains with the N number increased by 1000+N:
lcdm/2020-04-29_2000__1.txt
lcdm/2020-04-29_2000__2.txt
lcdm/2020-04-29_2000__3.txt
lcdm/2020-04-29_2000__4.txt
Once the copying is completely done (you can check file size with `ls -l`) it is best to delete the old chains. At the very least this should be done before making any final analysis of the chains (it interferes with R-1 calculation and possibly the plotting).

However, if you are not using mpi, but launched four parallel jobs, you would still have the initial four chains files, but when using restart without mpi you have to also launch in parallel 4 times, so instead you would write (correctly setting them up to be run at the same time):
```
mpirun -np 4 python montepython/MontePython.py run -r lcdm/2020-04-25_1000__1.txt --chain-number 1 -N 1000 -f 0.8
mpirun -np 4 python montepython/MontePython.py run -r lcdm/2020-04-25_1000__2.txt --chain-number 2 -N 1000 -f 0.8
mpirun -np 4 python montepython/MontePython.py run -r lcdm/2020-04-25_1000__3.txt --chain-number 3 -N 1000 -f 0.8
mpirun -np 4 python montepython/MontePython.py run -r lcdm/2020-04-25_1000__4.txt --chain-number 4 -N 1000 -f 0.8
```
Which would then produce the same four restarted chains as mpirun would have.

Best,
Thejs

**Comment by Jimmy022** [comment]
> Hi jimmy,
> The first time you launch a set of chains you would not run with the -r flag, that is for resuming (restarting) runs.
> Assume you have four chains:
> lcdm/2020-04-25_1000__1.txt
> lcdm/2020-04-25_1000__2.txt
> lcdm/2020-04-25_1000__3.txt
> lcdm/2020-04-25_1000__4.txt
> If you're running with mpi you would write
> mpirun -np 4 python montepython/MontePython.py run -r lcdm/2020-04-25_1000__1.txt  -N 1000 -f 0.8
> and it would restart all four chains, copying them to four new chains with the N number increased by 1000+N:
> lcdm/2020-04-29_2000__1.txt
> lcdm/2020-04-29_2000__2.txt
> lcdm/2020-04-29_2000__3.txt
> lcdm/2020-04-29_2000__4.txt
> Once the copying is completely done (you can check file size with ls -l) it is best to delete the old chains. At the very least this should be done before making any final analysis of the chains (it interferes with R-1 calculation and possibly the plotting).
> However, if you are not using mpi, but launched four parallel jobs, you would still have the initial four chains files, but when using restart without mpi you have to also launch in parallel 4 times, so instead you would write (correctly setting them up to be run at the same time):
> python montepython/MontePython.py run -r lcdm/2020-04-25_1000__1.txt --chain-number 1 -N 1000 -f 0.8
> python montepython/MontePython.py run -r lcdm/2020-04-25_1000__2.txt --chain-number 2 -N 1000 -f 0.8
> python montepython/MontePython.py run -r lcdm/2020-04-25_1000__3.txt --chain-number 3 -N 1000 -f 0.8
> python montepython/MontePython.py run -r lcdm/2020-04-25_1000__4.txt --chain-number 4 -N 1000 -f 0.8
> 
> Which would then produce the same four restarted chains as mpirun would have.
> Best,
> Thejs

I see. Thank you very much !

Best,
Jimmy

**Comment by Jimmy022** [comment]
I solved the problem thereafter. In short, I found that the reason for my problem was that I only used the CMB data to constrain wCDM, which was difficult to constrain the correct range of parameter w, and would lead to errors in the calculation process of the program.
