### ISSUE TITLE
SHELL environment issue with clik

### ISSUE THREAD

**Issue by anirbandas89** [brinckmann/montepython_public#126]
Hi,

I am trying to get montepython work with clik on a cluster with tcsh SHELL environment. The clik installation went fine but when I tried to source the clik_profile.sh file-
source bin/clik_profile.sh
I get the following error-
Badly placed ()'s.

I'm guessing it is due to syntax mismatch in tcsh environment. When I do 'echo $SHELL' I get
/bin/tcsh

I was wondering if there is any way to solve this issue. I would appreciate any help regarding this.

Thanks,
Anirban

**Comment by brinckmann** [comment]
Hi Anirban,

I'm not too familiar with tcsh, but e.g. for zsh we have to make some replacements in the clik_profile.sh file to make it compatible with that shell. You most likely have to do something similar for tcsh, making changes where bash and tcsh syntax varies. Note there's already a clik_profile.csh distributed with the Planck likelihood, which may be close enough to tcsh to work, or at least require minimal changes.

Best,
Thejs

**Comment by anirbandas89** [comment]
Thanks Thejs for your reply. I also thought so. I'll try modifying the csh file as sourcing it as it is does not work.
