### ISSUE TITLE
Massive neutrinos

### ISSUE THREAD

**Issue by DavidFigueruelo** [brinckmann/montepython_public#128]
Hello everyone,

I am currently trying to test a cosmological model allowing the possibility of also having usual massive neutrinos. I have no previous constraint on its masses or if they are degenerates so I am thinking which strategy should be used.

-If, for example, I want 3 massive neutrinos with different masses (at least in principle, latter results can point toward the same mass for all) one should only modify the .param file by writing something like this, no?

``data.parameters['m_ncdm__1'] = [0.1,    0.001,1, 0.4,1,   'cosmo']
data.parameters['m_ncdm__2'] = [0.1,    0.001,1, 0.4,1,   'cosmo']
data.parameters['m_ncdm__3'] = [0.1,    0.001,1, 0.4,1,   'cosmo']    ``
`.`
`.`
`.`
``
data.cosmo_arguments['N_ur'] = 0.00641 ``  
`` data.cosmo_arguments['N_ncdm'] = 3 ``
`` data.cosmo_arguments['T_ncdm']` = 0.71611``

-But if one does not care about individual masses but its sum so I want to constraint ∑m_ν, What should I write in the .param file?

The modified CLASS for the model when using MP is not slow in comparison with a LCDM model for example. But if massive neutrinos are added, with any of the previous possibilities, is too expensive in terms of computational time with respect to non massive neutrinos?

_Massive_ thanks!!

**Comment by lesgourg** [comment]
Ola David,
I suggest that you run with 
data.parameters['m_ncdm'] = [0.1, 0.001,1, 0.4,1, 'cosmo']
.
.
.
data.cosmo_arguments['N_ur'] = 0.00641
data.cosmo_arguments['N_ncdm'] = 1
data.cosmo_arguments['deg_ncdm'] = 3
data.cosmo_arguments['T_ncdm']` = 0.71611

It will emulate 3 massive neutrinos, degenerate in mass (hence the degeneracy parameter set to 3). The speed of CLASS scales roughly with N_ncdm, so N_ncdm=1 (like in my recommendation) will be slower than 0 but much faster than 3. Good runs!
Julien

**Comment by DavidFigueruelo** [comment]
Hello Julien,

Thanks for the recommendation!
One minor question about that case you suggest with `data.cosmo_arguments['N_ncdm'] = 1 ` and `
data.cosmo_arguments['deg_ncdm'] = 3` , with three degenerated masses the parameter `m_ncdm` should be understood as the total summed masses of the three (degenerated) neutrinos m_ncdm=∑m_ν or as  the individual mass of each of them and therefore ∑m_ν=3*m_ncdm?

Thanks again!!

**Comment by lesgourg** [comment]
OIa David, 
The second: individual mass, and ∑m_ν=3*m_ncdm. Note that the meaning of all cosmological parameters is explained in your class directory, in explanatory.ini. Best
Julien

**Comment by DavidFigueruelo** [comment]
Perfect!
Thank you!
