### ISSUE TITLE
JLA & pandas-1.0.3: as_matrix error

### ISSUE THREAD

**Issue by carlosggarcia** [brinckmann/montepython_public#129]
In line 2500 of `likelihood_class.py`, `as_matrix` is used. However, that method has been deprecated in newer versions of pandas ([docs](https://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.DataFrame.as_matrix.html#pandas.DataFrame.as_matrix) ). Changing it to `to_numpy`, makes it work again.

```
  File "/home/user/codes/montepython_public_upstream/montepython/likelihoods/JLA/__init__.py", line 64, in __init__
    self.C00 = self.read_matrix(self.mag_covmat_file)
  File "/home/user/codes/montepython_public_upstream/montepython/likelihood_class.py", line 2500, in read_matrix
    matrix = read_table(path).as_matrix().reshape((length, length))
  File "/usr/lib/python3.8/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'
```

**Comment by brinckmann** [comment]
Thanks for reporting this! In issue #98 @antoniuspisa suggested using 
`read_table(path).values.reshape((length, length))`
rather than the one proposed here of
`read_table(path).to_numpy().reshape((length, length))`
@schoeneberg This seems up your alley. Which do you prefer? Thanks!

Best,
Thejs

**Comment by schoeneberg** [comment]
Dear @brinckmann ,

indeed I agree with @carlosggarcia that the .to_numpy() option is preferable, as also officially documented [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html).

Cheers,
Nils Sch.

**Comment by dchooper** [comment]
Hi,

This bugfix has been incorporated into version 3.4, which has now been released.

Best,
Deanna
