### ISSUE TITLE
refereces for likelihood "bao_fs_boss_dr12"

### ISSUE THREAD

**Issue by mahtaparsa** [brinckmann/montepython_public#13]
In order to use the likelihood "bao_fs_boss_dr12", should we reference both papers "arXiv:1607.03155" and "arXiv:1708.09406" for that? Because in the paper "arXiv:1804.07261" both references are mentioned for this likelihood. However, I think the first reference is relevant.

**Comment by brinckmann** [comment]
Hi,
As is explained in the paper we generally encourage people to cite the papers that first used a likelihood, in order to give proper credit to the people who added the likelihood to MontePython.
Best,
Thejs
