### ISSUE TITLE
Pantheon data set update

### ISSUE THREAD

**Issue by jcolinhill** [brinckmann/montepython_public#131]
This is a minor issue to note that the Pantheon data set currently used in Monte Python is out-of-date w.r.t. that used in the Planck 2018 analysis.  As noted on page 24 (footnote 18) of the Planck 2018 parameters paper (https://arxiv.org/pdf/1807.06209.pdf):
"We use the November 2018 data file available from https://
github.com/dscolnic/Pantheon/, which includes heliocentric redshifts and no bulk-flow corrections for z > 0.08."

This data file corresponds to https://github.com/dscolnic/Pantheon/blob/master/lcparam_full_long_zhel.txt

whereas the current MP distribution uses
https://github.com/dscolnic/Pantheon/blob/master/lcparam_full_long.txt

The former file is about 6 months more recent than the latter file.

**Comment by jcolinhill** [comment]
Related to this: Monte Python and CosmoMC/Cobaya yield different values for the Pantheon chi^2, even when using the same Pantheon data file.  For the following cosmological parameters,
   logA = 3.0983
   n_s = 0.9686
   omega_b = 0.02253
   omega_cdm = 0.1177
   tau_reio = 0.085
   H0 = 68.2097

Monte Python yields chi^2_Pantheon = 1027.0.  If I run Cobaya with the same Pantheon data file (lcparam_full_long.txt), I find chi^2_Pantheon = 1036.0.  I use the same theory code in both cases, so the difference can only come from the likelihood implementation.  I note that the latter value is similar to those found for cosmological parameters near these in the Planck 2018 chains (chi^2 ~ 1034-1035 are typical best-fit Pantheon chi^2 values in those chains).  I have been trying to track down the origin of this difference in the two codes, but have not succeeded yet:
Cobaya:
https://github.com/CobayaSampler/cobaya/blob/master/cobaya/likelihoods/_base_classes/_sn_prototype.py
Monte Python:
https://github.com/brinckmann/montepython_public/blob/3.3/montepython/likelihoods/Pantheon/__init__.py

**Comment by brinckmann** [comment]
Hi Colin,

@PoulinV pointed out that our likelihood has an additional nuisance parameter that was not included in the official Pantheon likelihood. The MontePython Pantheon likelihood is an adapted version of the JLA likelihood updated to use Pantheon data. JLA originally had four nuisance parameters and our Pantheon likelihood was left with one, while the Cobaya likelihood based on Dan Scolnic's likelihood has none. It has been a while, but if I remember correctly our likelihood predates the public release of Dan's likelihood and just used the Pantheon data with a simplified JLA likelihood. Vivian was going to reach out to Dan about this for an explanation for why the nuisance parameters were was removed. Do you have an update, Vivian?

It's on my to do list for the next MontePython version to update our likelihood to the latest official version with the latest data, which will hopefully eliminate this kind of confusion.

Best,
Thejs

**Comment by jcolinhill** [comment]
Hi Thejs,
Thanks -- I did notice that in the Cobaya _sn_prototype.py, there are separate likelihood treatments for JLA and for Pantheon (although it's a bit hard to realize immediately), and that Pantheon does not come with nuisance parameters.  Perhaps investigating that implementation would be helpful, but I wasn't able to fully align it with the current Monte Python version.
Thanks,
Colin

**Comment by PoulinV** [comment]
Hi Colin, Thejs,

I haven't yet taken the time to write to Dan Scolnic, but will do so asap! I'll let you know what's the conclusion.

cheers
Vivian

**Comment by PoulinV** [comment]
Hi everyone,

I had a discussion with Dan. It seems that the likelihood is ok, although some further checks would be interesting. The main difference is that there is an analytical marginalization over the magnitude done in the CosmoMC/Cobaya version, as opposed to co-varying that parameter in the MP version.
The difference in chi^2 is a little surprising according to him, but when comparing the posteriors with what is reported in Planck table when combining Planck 18 and Pantheon, we seem to get a very good agreement, below 0.1sigma, so it might not matter that much. 
I’ll perform some explicit comparison between cobaya / MP asap to confirm that.

cheers
Vivian

**Comment by jcolinhill** [comment]
Yes, it seems like it is close to just being a constant offset term in chi^2 (around 6 or 7), which of course does not affect parameter constraints, but only the chi^2 value quoted for a best-fit point (e.g.).  But I have not compared it extremely carefully between the two codes.

**Comment by valerio-marra** [comment]
hi all, when marginalizing analytically there is one (two actually) constant term which should be included depending on the case, please see for instance eq.35 of [1805.09900](https://arxiv.org/abs/1805.09900)

**Comment by brinckmann** [comment]
Embarrassingly, we still need to update the data file! This should be done for the next public version, v3.4.1, which is imminent.

Best,
Thejs

**Comment by mballardini** [comment]
Hi @brinckmann @PoulinV,

it looks to me that the luminosity distance does not take into account the heliocentric redshifts in the Pantheon likelihood in MP being

moduli[index] = cosmo.luminosity_distance(z_cmb)

rather than something like

moduli[index] = (1+z_hel) / (1+z_cmb) * cosmo.luminosity_distance(z_cmb)

**Comment by brinckmann** [comment]
Thanks Mario, that's a big oversight on my part! We'll add the fix in the upcoming version later this month.

Best,
Thejs

**Comment by brinckmann** [comment]
The zhel change was added with version 3.4.

Best,
Thejs
