### ISSUE TITLE
Changes in likelihood_class.py after renaming of the folders containing Planck15 likelihoods in the 'likelihood/' folder

### ISSUE THREAD

**Issue by subhajitghosh-phy** [brinckmann/montepython_public#133]
Hi,

The folders in montepython_public/montepython/likelihoods/
which contain the Planck 2015 likelihood information have been renamed to differentiate from the Planck 2018 likelihoods.

Therefore the following lines in likelihood_class.py also need to be modified. 

[line 917](https://github.com/brinckmann/montepython_public/blob/b47b8d9acefe7376103ab21090c533465d10ffde/montepython/likelihood_class.py#L917):
if (self.name == 'Planck_highl_lite') or (self.name == 'Planck_highl_TTTEEE_lite'):

modification:
if (self.name == 'Planck15_highl_lite') or (self.name == 'Planck15_highl_TTTEEE_lite'):

Similar modification also in [line 1033](https://github.com/brinckmann/montepython_public/blob/3.3/montepython/likelihood_class.py#L1033).

Best,
Subhajit

**Comment by brinckmann** [comment]
Thank you! Indeed the Planck 18 likelihood doesn't even need this fix as it takes either. I've changed it and will update branch 3.3.

Best,
Thejs
