### ISSUE TITLE
Trying to implement a new parameterisation of the equation of state.

### ISSUE THREAD

**Issue by MarisolJC** [brinckmann/montepython_public#134]
Hi! 

I'm trying to implement a new parameterisation of the equation of state with one extra parameter (which I've named **w0_fld**). I introduced the new **w** in CLASS version 2.9.3, and when I type `./class new_eos.ini` it works, but I don't understand yet how Montepython knows which of the three parameterisations (LCDM, CLP, and the new EOS) is going to implement.
In this version of CLASS, I understand that in the file.ini I chose which of the parameterisations the code is going to use (in the code line: `#fluid_equation_of_state = CLP`), but, what about MontePython? 

Marisol.

**Comment by brinckmann** [comment]
Hi Marisol,

MontePython uses the same names as in CLASS and they can be passed with the data.cosmo_arguments structure. You will want to add to your param file the following down by the other cosmo_arguments:
`data.cosmo_arguments['fluid_equation_of_state'] = 'the_new_EOS'`
replacing the_new_EOS with whatever you called your new equation of state.

Best,
Thejs

**Comment by MarisolJC** [comment]
Hi Brinckmann!

Thank you so much! Seems it have worked.
