### ISSUE TITLE
Running on multiple nodes fails

### ISSUE THREAD

**Issue by WHKinney** [brinckmann/montepython_public#14]
I am finding that if I run multiple MontePython processes under SLURM on one cluster node, everything works fine. But if I split those same processes up over multiple nodes, MontePython fails with the following error: 

`io_mp.ConfigurationError: 

Configuration Error:
 /|\   You are running in a folder that was created following a non-successful
/_o_\  initialisation (wrong parameter name, wrong likelihood, etc...). If you
       have solved the issue, you should remove completely the output folder,
       and try again. Alternatively, there could be a problem with cosmo

Test scripts showing the behavior are below. Is this my problem, or is this a bug? Appreciate any feedback on this. 

Will Kinney

This SLURM script works fine:
`#!/bin/sh
#SBATCH --partition=debug
#SBATCH --qos=supporters
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --job-name="Base2015"
#SBATCH --output=Base2015.out
#SBATCH --mail-user=my_mail@localhost
#SBATCH --mail-type=ALL
##SBATCH --requeue

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

module load intel
module load intel-mpi
module load mkl
module load python/anaconda
source /projects/academic/whkinney/PlanckLike/plc-2.0/bin/clik_profile.sh

echo "Launching MontePython"
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
export OMP_NUM_THREADS=4
srun -N 1 -n 2 python ./montepython/MontePython.py run --conf ./default.conf -o ./chains/Base2015/ -p ./input/base2015.param -c ./covmat/base2015.covmat -f 1.5 -N 5000
#
echo "All Done!"
`

But this SLURM script fails:

`#!/bin/sh
#SBATCH --partition=debug
#SBATCH --qos=supporters
#SBATCH --time=00:05:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --job-name="Base2015"
#SBATCH --output=Base2015.out
#SBATCH --mail-user=my_mail@localhost
#SBATCH --mail-type=ALL
##SBATCH --requeue

echo "SLURM_JOBID="$SLURM_JOBID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

module load intel
module load intel-mpi
module load mkl
module load python/anaconda
source /projects/academic/whkinney/PlanckLike/plc-2.0/bin/clik_profile.sh

echo "Launching MontePython"
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
export OMP_NUM_THREADS=4
srun -N 2 -n 2 python ./montepython/MontePython.py run --conf ./default.conf -o ./chains/Base2015/ -p ./input/base2015.param -c ./covmat/base2015.covmat -f 1.5 -N 5000
#
echo "All Done!"
`

**Comment by brinckmann** [comment]
Hi Will,
Can you try to create the folder and log.param before launching the job, e.g. with flag -f 0? This solves some cluster-related issues.
Best,
Thejs

**Comment by lesgourg** [comment]
Hi Will,
Yes I fully second Thejs's advice. Doing a very short run with "-f 0" and/or "-N 1" just creates the log.param file. Then, when you launch all the processes on the cluster, each one will just read the input from this pre-existing log.param.  Otherwise there is a risk that they simultaneously try to read/write in the log.param at the beginning, and this creates a conflict and an error. This problem rarely happens - only on the fastest and most synchronised cluster I would say, but this seems to be  your case! By the way, nice to hear from you, and to know that you are  running with MP. Best wishes and don't hesitate to write again in case of further problems.
Julien

**Comment by WHKinney** [comment]
This does the trick, thanks! I like the software!
