### ISSUE TITLE
Question on Parallelization with MontePython

### ISSUE THREAD

**Issue by DhayaaAnbajagane** [brinckmann/montepython_public#141]
I currently utilize 'mpirun -np 8' to run MontePython sampling across multiple processors. With this command, I can run 8 separate chains; one for each processor.

I am however wondering (i) what command/flag I need in order to use 8 processors to run just one chain, and (ii) if it is more efficient to run 8 chains with N number of steps each or 1 chain with 8*N number of steps.

Thanks for your time!

**Comment by brinckmann** [comment]
Hi,

MontePython is set up to make use of OMP, so if you write:
`export OMP_NUM_THREADS=8`
It should use 8 processes _per chain_

If you only have 8 cores available I suspect the most efficient might be to run with 4 MPI processes with 2 cores per process using OMP, but I haven't tested this.

Best,
Thejs
