### ISSUE TITLE
MultiNest analyze problem if run with Planck 2018

### ISSUE THREAD

**Issue by Uendert** [brinckmann/montepython_public#144]
Hi everyone,

I am running montepython with MultiNest and then analyzing with `info`, but I get an error: `ValueError: invalid literal for float():` 

Below is a summary of the .param:
```
data.experiments=['Planck_highl_TTTEEE', 'Planck_lowl_EE', 'Planck_lowl_TT', 'Planck_lensing']

#data.over_sampling=[1, 5]      (!!! I am neither using oversampling nor covmat and bestfit files since I am not sure if this should be used when running nested sampling with MultiNest - Any word here?).  

data.parameters['omega_b']      = [ 2.2377, 1.875,  2.625,  0.015, 0.01, 'cosmo']
data.parameters['omega_cdm']    = [ 0.12010, 0.01, 0.99,  0.013, 1, 'cosmo']
data.parameters['H0']           = [ 70., 40., 100., 0.1, 1, 'cosmo']
data.parameters['ln10^{10}A_s'] = [ 3.0447, 1.7, 5., 0.015, 1, 'cosmo']
data.parameters['n_s']          = [ 0.9659, 0.7, 1.3, 0.0042, 1, 'cosmo']
data.parameters['tau_reio']     = [ 0.0543, 0.004, 0.1, 0.008, 1, 'cosmo']
```
Example of my Nested sampling running:
```
mpirun -np 12 python montepython/MontePython.py run -p input/cmb.param -o chains/cmb -m NS --NS_max_iter 10000000 --NS_importance_nested_sampling False --NS_sampling_efficiency 0.8 --NS_n_live_points 1000
 ```
```
Running Monte Python v3.2.0

with CLASS v2.7.2

Testing likelihoods for:
 -> Planck_highl_TTTEEE, Planck_lowl_EE, Planck_lowl_TT, Planck_lensing

----
clik version 3be036bbb4f9
  smica
Checking likelihood '/home/uendertandrade/planck/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34055e-07)
----
Initializing SimAll
----
clik version 3be036bbb4f9
  simall simall_EE_BB_TE
Checking likelihood '/home/uendertandrade/planck/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version 3be036bbb4f9
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home/uendertandrade/planck/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Checking lensing likelihood '/home/uendertandrade/planck/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8.clik_lensing' on test data. got -4.42102
 MultiNest Warning: no resume file found, starting from scratch
 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points = ****
dimensionality =   28
 *****************************************************
 Starting MultiNest
----
```
Then it finished with the message:
```
Acceptance Rate:                        0.609919
Replacements:                              29650
Total Samples:                             48613
Nested Sampling ln(Z):             -83513.596480
Acceptance Rate:                        0.609919
Replacements:                              29650
Total Samples:                             48613
Nested Sampling ln(Z):             -83513.596480
 ln(ev)=  -1.9649000000000032      +/-   1.4017489076150561E-002
 Total Likelihood Evaluations:        48613
 Sampling finished. Exiting MultiNest

```
So that I use the command ` python montepython/Montepython info chains/cmb/NS ` to convert the NS output to a regular MP chain. However, I got the following error: ValueError: invalid literal for float().  See below for the full message. 
```
Running Monte Python v3.3.4

 /!\ This call to matplotlib.use() has no effect because the backend has already
     been chosen; matplotlib.use() must be called *before* pylab,
     matplotlib.pyplot,
     or matplotlib.backends is imported for the first time.
     The backend was *originally* set to 'Qt5Agg' by the following code:
     File "montepython/MontePython.py", line 40, in <module>
     sys.exit(run())
     File "/home/uendertandrade/montepython_public/montepython/run.py", line 32,
     in run
     custom_command)
     File "/home/uendertandrade/montepython_public/montepython/run.py", line
     191, in safe_initialisation
     cosmo, data, command_line, success = initialise(custom_command)
     File "/home/uendertandrade/montepython_public/montepython/initialise.py",
     line 31, in initialise
     command_line = parser_mp.parse(custom_command)
     File "/home/uendertandrade/montepython_public/montepython/parser_mp.py",
     line 1043, in parse
     parser = create_parser()
     File "/home/uendertandrade/montepython_public/montepython/parser_mp.py",
     line 860, in create_parser
     from MultiNest import NS_prefix, NS_user_arguments
     File "/home/uendertandrade/montepython_public/montepython/MultiNest.py",
     line 18, in <module>
     from pymultinest import run as nested_run
     File "build/bdist.linux-x86_64/egg/pymultinest/__init__.py", line 27, in
     <module>
     from .plot import PlotMarginal, PlotMarginalModes
     File "build/bdist.linux-x86_64/egg/pymultinest/plot.py", line 6, in
     <module>
     import matplotlib.pyplot as plt
     File "/home/uendertandrade/anaconda2/lib/python2.7/site-
     packages/matplotlib/pyplot.py", line 71, in <module>
     from matplotlib.backends import pylab_setup
     File "/home/uendertandrade/anaconda2/lib/python2.7/site-
     packages/matplotlib/backends/__init__.py", line 16, in <module>
     line for line in traceback.format_stack()
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/uendertandrade/montepython_public/montepython/run.py", line 32, in run
    custom_command)
  File "/home/uendertandrade/montepython_public/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/uendertandrade/montepython_public/montepython/initialise.py", line 59, in initialise
    analyze(command_line)
  File "/home/uendertandrade/montepython_public/montepython/analyze.py", line 98, in analyze
    status = prepare(item, info)
  File "/home/uendertandrade/montepython_public/montepython/analyze.py", line 215, in prepare
    action_done = clean_conversion(module_name, tag, files[0])
  File "/home/uendertandrade/montepython_public/montepython/analyze.py", line 1499, in clean_conversion
    getattr(module, 'from_%s_output_to_chains' % tag)(folder)
  File "/home/uendertandrade/montepython_public/montepython/MultiNest.py", line 426, in from_NS_output_to_chains
    mode_data = np.array(mode_lines[i].split(), dtype='float64')
ValueError: invalid literal for float(): -0.935262757107470655-309

``` 
Any thought why I am getting such error? 

Additionally, what would be the best/recommended nesting sampling flags values for MultiNest NS algorithm when using with Planck data, when one is only worried about posteriors and don't care about evidence?
 
ps: This same procedure works fine for Pantheon, KiDs and BAO data.
ps2: Although I am not using both oversampling and covmat Planck file for the above example I do get the same error (ValueError: invalid literal for float) when I use those.

**Comment by brinckmann** [comment]
Hi Uendert,

I can confirm a few things: MultiNest ignores oversampling, covmats and bestfits, so providing those has no effect.

As for the actual error, it seems like the code tried to produce a 0 at some point and because of machine precision ended up with a very small negative value. However, because of some weird kind of writing of numbers it ended up with -0.935262757107470655-309 instead of -0.935262757107470655e-309 (i.e. the last should be e-309). I'm not sure why this happened, but maybe you can try to look for this value in your output files and change it to 0.0? I do worry if it's a symptom of a greater problem, but I suspect it might just be a strange python i/o malfunction.

For your specific MultiNest parameters question I'm not sure. I usually like to run with `--NS_n_live_points 1000 --NS_evidence_tolerance 0.01` (at least for simple posteriors) in order to get accurate posterior distributions, with the rest of the parameters set to the default values (except NS_multimodal, NS_max_modes and NS_clustering_params, where applicable).

Best,
Thejs

**Comment by Uendert** [comment]
Hi Thejs,

Thanks for your prompt reply!

I did find the value (-0.935262757107470655-309) in the `cmb-.txt` file. And then, replace it with 0.0. However, it gives the same previous error but for a different value (-0.934498165496620193-309). So I realized that there is a lot of values which have the same problem. Values like -0.138856379233383139-308. So it is unpractical to replace all of them by hand. Do you know a better/robust way to do that?
     
Best,
Uendert

--

**Comment by srbND** [comment]
Hi Uendert, 

I am facing similar issues while using MultiNest with Planck data. Even I am getting values similar to what you got. As Thejs suggested, I replaced all such numbers by zero but that led  -loglik = 0, which does not make sense to me.

Did you figure out any solution to this issue or do you have any suggestions?

Thanks
Saurabh

**Comment by Uendert** [comment]
Hi @srbND,

I couldn't find a way to use MultiNest with Planck data. So I used the Metropolis-Hastings algorithm instead.

Did you replace all these weird numbers with zero? How many were there? Did you make it manually?

Cheers,
Uendert

**Comment by srbND** [comment]
Hi @Uendert 

I see, I will probably just use MultiNest in that case. I did replace are the weird numbers by zero, but that didn't help. To replace these number, I found all the numbers with the form -309 or similar at the end, and then did the replacement that these numbers should be equal to zero. I am not sure how many of these there, but it was not super difficult.

One of the reasons I was particularly interested in using MH algorithm is because I wanted to use KiDS data. If I am not mistaken, for KiDS data, it is recommended to use MH algorithm. Let me know if you find a way out.

Thanks
Saurabh

**Comment by srbND** [comment]
Hi @Uendert

I think this issue is specific to MP with Python3. On setting up MP with Python 2.7, I was able to fix this problem. I hope this helps.

Saurabh

**Comment by Xinyi2021** [comment]
Hi @Uendert @srbND,
The "ValueError: invalid literal for float()" could be caused by the writing format of the original Fortran file, it uses "E28.18E3" in both nested.F90 and posterior.F90. This format allows only width three including "E". Changing it into "E28.18E4" works for me. I use the C++ interface of multinest. I hope it helps. 

Xinyi

**Comment by Uendert** [comment]
Hi @Xinyi2021,

Thanks for getting into the bottom line of this issue. However, I'm not familiar neither with Fortran nor with C++. Would you mind sharing the fixes of the files you mentioned? I looked for "E28.18E3" in both [nested.F90](https://github.com/JohannesBuchner/MultiNest/blob/master/src/nested.F90) and [posterior.F90](https://github.com/JohannesBuchner/MultiNest/blob/master/src/posterior.F90) files but couldn't find it.

Cheers,
Uendert

**Comment by Xinyi2021** [comment]
Hi @Uendert,
Did you try just search for "E28"? For me it has 13 matches in nested.F90.
![image](https://user-images.githubusercontent.com/82191884/116330623-7e751200-a800-11eb-9111-98c0cb51598b.png)

**Comment by Uendert** [comment]
Thanks, @Xinyi2021 

I did try to search for that: "E28". And I found 16 matches. But none of that has the structure you first mentioned: "E28.18E3"

Some of these matches even have a number in front of it, like: "**2**E28.18" . So I don't know what should do. I am been pedant just because I know nothing about Fortran, so I don't want to mess with anything.

Also, I guess we're looking at different nested.90 file. This is the one I am looking at [https://github.com/JohannesBuchner/MultiNest/blob/master/src/nested.F90](https://github.com/JohannesBuchner/MultiNest/blob/master/src/nested.F90)

Any help would be really appreciated,

Thanks again for your time.
Uendert

**Comment by Xinyi2021** [comment]
Hi @Uendert 
I use the nested.F90 from 
[https://github.com/farhanferoz/MultiNest/blob/master/MultiNest_v3.12_CMake/multinest/src/nested.F90](url)
You can change all the 19 E28 (including those with a number in front of) associated ".18" into ".18E4", which is a format specification that allows four digits exponential numbers. A reference for this format can be found at: 
[https://www.fortrantutorial.com/documents/IntroductionToFTN95.pdf](url)
section 5.5.3

Cheers,
Xinyi

**Comment by srbND** [comment]
Hu @Xinyi2021 

That worked! 
I changed all the E28.18 to E28.18E4 in nested.F90 file and I don't see any weird numbers anymore. Thanks a lot for figuring this one out!

Cheers,
Saurabh

**Comment by JohannesBuchner** [comment]
I tried applying this solution to MultiNest, but users got errors. This is the pull request https://github.com/JohannesBuchner/MultiNest/pull/6 and this is the problem https://github.com/JohannesBuchner/PyMultiNest/issues/194. Can someone create a PR and test it with pymultinest (e.g., the demo scripts)?
