### ISSUE TITLE
A derivative in w(a)

### ISSUE THREAD

**Issue by progsymrock** [brinckmann/montepython_public#145]
Hi everybody, I have a question:

Is it possible to write a w(a) equation in background.c with a' (first derivative of the scale factor with respect to the conformal time) terms? How it could be written in the code?

Thanks!

**Comment by brinckmann** [comment]
Hi,

This seems to be a CLASS issue. You may have more luck posting on the class page [https://github.com/lesgourg/class_public/issues](https://github.com/lesgourg/class_public/issues)

Best,
Thejs
