### ISSUE TITLE
multiple processors and parallel chains

### ISSUE THREAD

**Issue by talabadi** [brinckmann/montepython_public#146]
Hello,

I have access to multiple processors and I wish to use all of them for MontePython runs.
I understand there are options of:
1) Run the  same chain, using multiple processors.
2) Run multiple chains (1 for each processor).

Is there documentation for such operations?

Thanks.

**Comment by brinckmann** [comment]
MontePython can use standard MPI (via mpi4py) and OMP. MPI governs the number of chains and OMP the number of chains per process.

An example would be:
export OMP_NUM_THREADS=8
mpirun -np 8 python montepython/MontePython.py run -p input/example.param -o chains/testrun/ -N 10000

You may need to create the directory chains/testrun/ first.

Best,
Thejs
