### ISSUE TITLE
removal of non-markovian points for chains generated with --restart

### ISSUE THREAD

**Issue by subhajitghosh-phy** [brinckmann/montepython_public#151]
Hi,

I am using the --restart option to generate longer chains for better R-1. While analysing the chains I stumbled upon an issue.

I understand that the way MontePython (mp) identifies the markovian part is via looking for the last comment in the chain files having the phrase 'update proposal' and noting the no of accepted steps on that line.

However, after the restart of a given chain, it seems like the accepted steps counter is getting set zero.  So the no of accepted steps on the last line does not correctly reflect the non-markovian part.

Is this supposed to happen?

To illustrate this, I will write down some of the comment lines on one of my restarted output chains.

line 1498 :  # After 1497 accepted steps: update proposal with max(R-1) = 1.824181 and jumping factor = 2.400000
line 1783: # After 1781 accepted steps: rescaled jumping factor from 2.400000 to 2.403976, due to updated covariance matrix
line 1784: # After 1781 accepted steps: update proposal with max(R-1) = 1.824181 and jumping factor = 2.403976
.
.
.
line  159183 : # After 159119 accepted steps: rescaled jumping factor from 1.820660 to 1.818612, due to updated covariance matrix
line 159183 : # After 159119 accepted steps: update proposal with max(R-1) = 0.403545 and jumping factor = 1.818612

(now I restart the chain)

line 354304: After 124058 accepted steps: rescaled jumping factor from 1.780915 to 1.492017, due to updated covariance matrix
line 354305:  After 124058 accepted steps: update proposal with max(R-1) = 0.402261 and jumping factor = 1.492017

When I am analysing the chains the code says - 'Removed 124943 non-markovian points, 580 points of burn-in, keep 321516 steps'

But It should remove almost ~350000 non-markovian points - right? 

Can you please help me with this.

Thanks in advance. 

Best,
Subhajit

**Comment by brinckmann** [comment]
That's rather puzzling. Can you send me an email (in my profile) with the chains and the log.param? Perhaps as a dropbox/google drive/etc link since the chains seem to be quite long.

Best,
Thejs
