### ISSUE TITLE
'euclid_lensing' and 'euclid_pk' likelihoods failing python3 syntax check

### ISSUE THREAD

**Issue by janinarenk** [brinckmann/montepython_public#153]
Hey, 

Owing to a very creative mix of the use of tabs and spaces in the `euclid_lensing` and `euclid_pk` likelihoods, they already fail at the syntax check with python3. I've tried to fix it for the lensing one. I've managed to make it run, but TBH I am not sure if it does what it is supposed to as several loops were entirely off, such that I don't fully trust my educated guesses. 

The patch for the working version of the lensing likelihood is attached. According to the file, Tim (@SprengerT) is the last person who modified it, maybe he could have a look to see if it seems reasonable and fix the `euclid_pk`? It's taken me quite some time for the lensing one as I am not familiar with the specific likelihood calculation. 

Thanks for your help!

Cheers,
Janina  

[euclid_lensing_diff.txt](https://github.com/brinckmann/montepython_public/files/5022346/euclid_lensing_diff.txt) (I went for spaces, no tabs)

**Comment by sirichongchitnan** [comment]
Same here. I tried fixing euclid_pk but I've given up.

**Comment by brinckmann** [comment]
Tim sent me an updated version and I just have to test it. Give me a few days and I'll push it if everything is fine.

Best,
Thejs

**Comment by dchooper** [comment]
Hi,

New versions of these two likelihoods are available in MP version 3.4, the issue should now be solved.

Best,
Deanna
