### ISSUE TITLE
Issue with eBOSS_DR14_Lya likelihoods

### ISSUE THREAD

**Issue by MarkMos** [brinckmann/montepython_public#155]
Hi

When trying to use the eBOSS_DR14_Lya likelihoods, I get the error: 

```
Configuration Error:
 /|\   Trying to import the eBOSS_DR14_Lya_cross likelihood as asked in the
/_o_\  parameter file, and failed. Please make sure it is in the
       `montepython/likelihoods` folder, and is a proper python module. Check
       also that the name of the class defined in the __init__.py matches the
       name of the folder. In case this is not enough, here is the original
       message: No module named 'scan_util'
```
 (_auto and _combined give the same error, but with their name instead)

I have been able to solve it by copying scan_util.py from the likelihood directory to the montepython directory (the directory with MontePython.py etc.)

I don't know if it is connected to my version of Python (I am using Python 3.7.6 installed with Anaconda3), or a more general issue, but I  have experienced it on two different machines, so I thought I would let you know.

Best,
Markus

**Comment by dchooper** [comment]
Hi Markus,

Thanks a lot for bringing this to our attention. This is indeed a bug in the eBOSS likelihoods that appears when running with Python 3. The bugfix is in the pipeline and will be deployed in the next release. If you need to address this before the bugfix is deployed, in the corresponding __ init __ .py file you want to change 
`import scan_util as util`
to
`import sys`
`sys.path.append('.')`
`from . import scan_util as util`

This also affects all of the BOSS* likelihoods, as well as the bicep2 likelihood. 

Best,
Deanna
