### ISSUE TITLE
Error while running base2018TTTEEE_lensing.param with covmat 

### ISSUE THREAD

**Issue by ravi398** [brinckmann/montepython_public#156]
montepython/MontePython.py  -p input/base2018TTTEEE_lensing.param -o output28 -N 10000 --update 50 -c covmat/base2018TTTEEE_lensing.covmat -b bestfit/base2018TTTEEE_lensing.bestfit
 /!\ Defaulting to the 'run' command. Please update the call of MontePython. For
     more info, see the help string and/or the documentation
 /!\ Appending to an existing folder: using the log.param instead of
     input/base2018TTTEEE_lensing.param
Running Monte Python v3.3.4

with CLASS v2.9.4

Testing likelihoods for:
 ->Planck_highl_TTTEEE, Planck_lowl_EE, Planck_lowl_TT, Planck_lensing

----
clik version 3be036bbb4f9
  smica
Checking likelihood '/home/ravi/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34054e-07)
----
Initializing SimAll
----
clik version 3be036bbb4f9
  simall simall_EE_BB_TE
Checking likelihood '/home/ravi/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version 3be036bbb4f9
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home/ravi/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Checking lensing likelihood '/home/ravi/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8.clik_lensing' on test data. got -4.42102
Creating output28/2020-08-28_10000__2.txt

Input covariance matrix:
['omega_b', 'omega_cdm', '100*theta_s', 'ln10^{10}A_s', 'n_s', 'tau_reio', 'A_cib_217', 'xi_sz_cib', 'A_sz', 'ps_A_100_100', 'ps_A_143_143', 'ps_A_143_217', 'ps_A_217_217', 'ksz_norm', 'gal545_A_100', 'gal545_A_143', 'gal545_A_143_217', 'gal545_A_217', 'galf_TE_A_100', 'galf_TE_A_100_143', 'galf_TE_A_100_217', 'galf_TE_A_143', 'galf_TE_A_143_217', 'galf_TE_A_217', 'calib_100T', 'calib_217T', 'A_planck', 'z_reio', 'Omega_Lambda', 'YHe', 'H0', 'A_s', 'sigma8']
[[  2.05e-08  -9.28e-08   9.29e-09 ...,   5.44e-05   1.07e-15  -1.05e-07]
 [ -9.28e-08   1.45e-06  -8.47e-08 ...,  -6.24e-04  -1.03e-14   2.10e-06]
 [  9.29e-09  -8.47e-08   8.75e-08 ...,   6.75e-05   9.62e-16   5.14e-08]
 ..., 
 [  5.44e-05  -6.24e-04   6.75e-05 ...,   2.92e-01   4.93e-12  -8.18e-04]
 [  1.07e-15  -1.03e-14   9.62e-16 ...,   4.93e-12   9.53e-22   1.56e-13]
 [ -1.05e-07   2.10e-06   5.14e-08 ...,  -8.18e-04   1.56e-13   3.73e-05]]
OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Aborted (core dumped)

**Comment by dchooper** [comment]
Hi Ravi,

Were you able to solve your problem? This seems like an issue with your OpenMP installation. Does the problem only occur when you load the covmat, or also if you launch a run without a covmat?

Best,
Deanna

**Comment by ravi398** [comment]
Hello madam,
thank you for your reply. This problem occurs only when i load covmat. without covmat it runs fine.
The problem has been solved actually. It was problem in my cluster only not in the code. It was solved when i give running  command with 
KMP_DUPLICATE_LIB_OK=TRUE .(third last line of above error message).


thanking you
Regards
Ravi sharma

**Comment by dchooper** [comment]
Hi Ravi,

Great, thanks a lot for sharing your solution - a lot of people encounter different cluster issues, so this might help someone else with similar issues.

Best,
Deanna
