### ISSUE TITLE
Using density number count Cls and parameter arrays

### ISSUE THREAD

**Issue by DavidFigueruelo** [brinckmann/montepython_public#159]
Hello,

I am working with a likelihood that uses the  density number count  nCl. The question is about the selection_mean (and the other parameter related: bias, magnification bias, non_diagonal, etc) inside the .param file. As I am going to work with several redshift bins, in CLASS I would use something like `selection_mean =0.3,0.65,0.9,1.15,1.6` so in MontePython I would expect something like `data.cosmo_arguments['selection_mean'] = 0.3,0.65,0.9,1.15,1.6` but it does not seem to work. 

I have thought of doing something similar as for different neutrinos `data.cosmo_arguments['selection_mean__1']=0.3` `data.cosmo_arguments['selection_mean__2']=0.65` ... but I am not sure this is an efficient implementation. 
So the question is, how one should write in the .param file the parameters that in the .ini file of CLASS are an array of values?

Thanks for the help!!!

**Comment by brinckmann** [comment]
Hi David,

Can you try passing it as a string?
data.cosmo_arguments['selection_mean'] = "0.3,0.65,0.9,1.15,1.6"

Which error message does it give?

Best,
Thejs

**Comment by DavidFigueruelo** [comment]
Hi,

Yes, the " " was the key point if one wants to use some vector of values `data.cosmo_arguments['selection_mean'] = "0.3,0.65,0.9,1.15,1.6"`, now it gives no error. Thanks for pointing it out! I was using the trick of `data.parameters['selection_mean__1']=[0.3,  None, None, 0.0, 1,   'cosmo'] `which also works, but what you said is quite more elegant and easy to implement.

Another question related to using the number count Cls, the usual function to obtain the TT,EE,TE.... spectra in order to use it inside a likelihood of MontePython is the function `get_cl()` which uses the python CLASS function `lensed_cl()`. In the case of the density number counts (nCl or dCl) I do not find a previously defined function like `get_cl()`, so I suppose I need to create one similar function inside the likelihood_class.py file using the python CLASS function `density_cl()`?

In any case thanks, I really appreciate your help!

Best wishes,
David.

**Comment by brinckmann** [comment]
Hi,

The purpose of get_cl() is to change the units of the power spectra depending on type, otherwise you could call `cosmo.lensed_cl(l_max)` directly. So in your case, you could probably just call density_cl() directly from your likelihood. I.e. call `cosmo.density_cl(l_max)` at any point inside the `loglkl` function in your likelihood. The key is that the wrapper (i.e. `cosmo`) should be available at the point where you need the density cl's (so e.g. if you require it already inside the `__init__` function it would take some clever tinkering).

Best,
Thejs

**Comment by DavidFigueruelo** [comment]
Hello,

Thanks, the explanations were very useful!!
