### ISSUE TITLE
Problem when running Planck likelihood

### ISSUE THREAD

**Issue by feuerfuchszhao** [brinckmann/montepython_public#16]
Dear all,
I am using Planck likelihood and I have already downloaded the plc-2.0 folder, then I installed it using the following command:
```
./waf configure --install_all_deps --lapack_mkl=$MKLROOT
./waf install
```
The installation is successful and then I run the command:
`source ~/test/planck/plc-2.0/bin/clik_profile.sh`
(I put the plc-2.0 folder in a folder called "planck" . This folder is in a folder called "test" together with the folder "hi-class" and "montepython_public-2.2". The conf. file of montepython has also been written as followes:

```
root = '~/test/hi_class/'
path['cosmo']		= root
path['clik']            = '~/test/planck/plc-2.0'
```

Everything is fine until this point, but when I tried to running montepython, it turns out an error:

```

Testing likelihoods for:
 -> Planck_highl_TTTEEE

Cannot use clik wrapper (cause = 'No module named lkl')
Cannot use clik_lensing wrapper (cause = 'No module named lkl_lensing')
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/zhao/test/montepython_public-2.2/montepython/run.py", line 31, in run
    custom_command)
  File "/home/zhao/test/montepython_public-2.2/montepython/run.py", line 188, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/zhao/test/montepython_public-2.2/montepython/initialise.py", line 66, in initialise
    data = Data(command_line, path)
  File "/home/zhao/test/montepython_public-2.2/montepython/data.py", line 340, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/zhao/test/montepython_public-2.2/montepython/data.py", line 460, in initialise_likelihoods
    elem, elem, folder, elem)
  File "<string>", line 1, in <module>
  File "/home/zhao/test/montepython_public-2.2/montepython/likelihood_class.py", line 861, in __init__
    "and try again.")
montepython.io_mp.MissingLibraryError: 

Missing Library Error:
 /|\   You must first activate the binaries from the Clik distribution. Please
/_o_\  run :
       ]$ source /path/to/clik/bin/clik_profile.sh
       and try again.
```

I did run the source things but it does not work. Could anyone help me to find out where the problem is?
In any case, thank you for your help.

**Comment by brinckmann** [comment]
Hi,
Try to have a look at issues [https://github.com/baudren/montepython_public/issues/94](https://github.com/baudren/montepython_public/issues/94) and [https://github.com/baudren/montepython_public/issues/68](https://github.com/baudren/montepython_public/issues/68). Let me know if this doesn't help.
Best,
Thejs

**Comment by feuerfuchszhao** [comment]
> Hi,
> Try to have a look at issues [baudren#94](https://github.com/baudren/montepython_public/issues/94) and [baudren#68](https://github.com/baudren/montepython_public/issues/68). Let me know if this doesn't help.
> Best,
> Thejs

Thank you Thejs, I find the problem may be with ifort.  I wrote the ./waf configure command wrong. Today I tried again and when I am running with the command

`>./waf configure --install_all_deps --lapack_mkl=/opt/intel`

and it turns out an error. The others are OK but there is this:
`Checking for program 'ifort'              : not found 
ifort not found, defaulting to gfortran (cause: 'Could not find the program ['ifort']
(complete log in /home/jiaming/work/COM_Likelihood_Code-v2.0.R2.00/plc-2.0/build/config.log)') 
`
and this
`create specific mkl lib                                            : Command 'gcc -shared -Bdynamic  -u dposv_ -u dtrsv_ -u dpotrf_ -u dpotrs_ -u dpotri_ -u dtrtri_ -u dtrmm_ -u dtrmv_ -u dgeqrf_ -u dormqr_ -u dsyev_ -u dgesvd_ -u dsymv_ -u dgemv_ -u dgemm_ -u dsyrk_ -u dsyr2k_ -u daxpy_ -u dtrsm_ -u dsymm_ -u dsyr_ -u ddot_ -u dsyevd_ -u dlamch_ -u dsyevr_  -Wl,--start-group /opt/intel/lib/intel64/libmkl_intel_lp64.a /opt/intel/lib/intel64/libmkl_intel_thread.a /opt/intel/lib/intel64/libmkl_core.a  -Wl,--end-group -L/home/jiaming/work/COM_Likelihood_Code-v2.0.R2.00/plc-2.0 -liomp5 -lpthread -lm -o "/home/jiaming/work/COM_Likelihood_Code-v2.0.R2.00/plc-2.0/lib/libclik_mkl.so" ' returned 1
`
So maybe the problem is because of the lack of ifort? I found the same situation here:
[https://cosmocoffee.info/viewtopic.php?t=2721](url)

**Comment by feuerfuchszhao** [comment]
Dear all,

I solved the issue. For my situation the issue is solved by using icc and ifort instead of gcc and gfortran. It seems that there will be a conflict between mkl and gcc/gfortran. I don't know if this is just my case, but who met the same problem can have a try and see if it works.
The method using icc and ifort is just write "--icc --ifort" at the end of the ./waf configure command (have a look at the readme.txt)
Thank you for all that helped me.
