### ISSUE TITLE
Unable to restart/resume run with MultiNest

### ISSUE THREAD

**Issue by arsalanadil** [brinckmann/montepython_public#161]
Hello,

I am using MultiNest as the sampling scheme for MontePython. I recently ran a chain which ended successfully and I would like to extend the number of points by resuming this chain from where it last left off to avoid re-sampling unfavored parts of parameter space. This is straightforward if one is using the default MH algorithm by using the -r flag. However, I am unable to do so while using MultiNest. The instructions in the MontePython documentation say that running the same command (for e.g. mpirun -np 4 python montepython/Montepython -o /output/path/ -m NS -N [number of points]) should cause MultiNest to resume the previous run. 
But what I see is that MultiNest detects the previous run saying "resuming from previous job", but then immediately ends returning the usual acceptance rate, total likelihood evaluations etc along with "Sampling finished. Exiting MultiNest".

I have checked that the resume.dat file is present in the /NS/ subfolder. I have also tried this without mpi. Note also that when I attempt this restart, a new .paramnames file is correctly created. 
Has anyone had any success in resuming their runs with MultiNest? Am I just passing some command incorrectly? 

Thanks!
Arsalan

**Comment by brinckmann** [comment]
Hi Arsalan,

I am afraid MultiNest precision settings have to be defined at the start of a run as the information is used throughout. Once MultiNest says a run is done it is done and you have to start over with improved precision settings if convergence was not good enough.

The sampling precision is primarily governed by two parameters: evidence_tolerance and n_live_points, passed with `--NS_evidence_tolerance <float>` and `--NS_n_live_points <int>`

Best,
Thejs

**Comment by arsalanadil** [comment]
Hi Thejs,

Thanks for the reply and apologies for taking so long in getting back to you! It seems like MultiNest itself does allow to resume a run once it has reached the stopping criterion by lowering the evidence tolerance (for example as suggested [here](https://github.com/JohannesBuchner/PyMultiNest/issues/58) ).I was able to resume the run by changing the evidence tolerance in the .arguments file within the NS/ subfolder. Judging from the way MN determines the evidence tolerance (as in section 3.2 of F. Feroz et. al [2019]), this doesn't seem to be an unreasonable thing to do. Have I misunderstood something here?

Some context: I was running using the evidence_tolerance and live_points settings that you suggested [here](https://github.com/brinckmann/montepython_public/issues/144). But the posteriors are complicated and this didn't seem to cut it.

**Comment by brinckmann** [comment]
Hi Arsalan,

By all means, if Johannes Buchner says it's fine to use this workaround then I'd trust that. Thanks a lot for getting back to me, I didn't know it was consistent to change the evidence tolerance during a run and I'll find that useful for my own work.

Best,
Thejs
