### ISSUE TITLE
Issue with CMB noise  file

### ISSUE THREAD

**Issue by Jimmy022** [brinckmann/montepython_public#167]
Hi,

I'm working on a project  using MCMC to do some forecast with CMB likelihood. I want to ask that if there is a explanation on each column of the noise file? Specifically, I have not made clear the meaning of line 8 and line 9 (from 1 to 10 ) of the file "noise_cmb_s4.dat" in /data.

Best,
Jimmy

**Comment by dchooper** [comment]
Hi Jimmy,

Apologies for not getting you an answer sooner. 
The noise files are produced using FuturCMB, modified to produce exactly what MontePython expects to get as an input (this is explained a bit in the release paper of the corresponding likelihoods, [1805.05955](https://arxiv.org/abs/1808.05955)) The ten columns in the noise files are:
1. Multipole number
2. Temperature noise (Nl_T)
3. Polarization noise (Nl_P)
4. Deflection angle noise (Nl_d)
5. Cl_TT spectrum (in muK^2)
6. Cl_TE spectrum (in muK^2)
7. Cl_EE spectrum (in muK^2)
8. Cl_dd spectrum (dimensionless)
9. Cl_Td spectrum (in muK)
10. Sky fraction

Note that none of the spectra have any l(l+1)/2pi factor in front of them.
Best,
Deanna

**Comment by Jimmy022** [comment]
Hi Deanna,

After some days of effort, I can repeat the noise file from the program (noise_cmb_s4.dat, noise_litebird.dat, etc). But I found that the line 8 turn out to be line4* 2*pai/l/(l+1) in these file, and has nothing to do with Cl_dd spectrum.  May I ask that is there a problem or a mistake I made ?

Best,
Jimmy

**Comment by dchooper** [comment]
Hi Jimmy,

That's interesting, you seem to be correct. It's possible that we didn't replace the former column 8 in FuturCMB with the Cl_dd spectrum when we reshuffled all of the columns. In any case, MontePython doesn't read the Cls from the noise file, it uses CLASS for these, so the only significant columns in the noise files are 1-4, which all seem to be fine.

Best,
Deanna

**Comment by Jimmy022** [comment]
Thank you for  your reply Deanna! It solves my confusion.
