### ISSUE TITLE
How to use the restart command

### ISSUE THREAD

**Issue by raziel2646** [brinckmann/montepython_public#17]
Hi,

I am running 5 parallel chains on a cluster but the, unfortunately, the job doesn't finish within the walltime of the cluster. In the paper https://arxiv.org/pdf/1804.07261.pdf it's mentioned that "When chains are restarted in the same directory using the --restart command, this will be done automatically".  However, it is not in the code's documentation how this can be done in practice. 

I am running the chains using
```
srun --ntasks=5 --mpi=pmi2 python montepython/MontePython.py run \
    --conf default.conf -j fast\
	-p $params -o $output -c $covmat --superupdate 20\
	 -N $Nstep --update $updatestep --silent`
```
and the output txt files look like this:

```
2018-10-26_100000__1.txt 
2018-10-26_100000__2.txt  
2018-10-26_100000__3.txt 
2018-10-26_100000__4.txt 
2018-10-26_100000__5.txt
```
Is there a way to quickly restart/continue the chain without using the output file names?

**Comment by brinckmann** [comment]
Hi,

The flag you want to use is
`-r <file>`
which will restart chains from previous run. You must pass the lowest index chains file, e.g. 2018-09-12_10000__1.txt . MontePython will then create copies of all chains index 1 through N (number of MPI processes) with new names 2018-09-12_20000__1.txt etc. Once the chains have been copied the old chains can be moved to a backup folder or deleted. Note they will be automatically deleted at the completion of the run. You should not include the old chains as a part of the analysis.

I will update the help files as it is not very clear. I will also add the alias --restart (which does not currently exist, my apologies!)

For general help on using MontePython our most recent MontePython lecture from the Kavli Institute for Cosmology in Cambridge last month may be useful, you can find them on the [website of Julien Lesgourgues](https://lesgourg.github.io/class-tour/Cambridge/180912_MontePython_Cambridge.pdf).

Best,
Thejs

**Comment by raziel2646** [comment]
Thanks a lot for your prompt reply. I appreciate your help.
