### ISSUE TITLE
Problem with Planck likelihood

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#174]
Hi all, I hope you are okay

So, I have Linux Mint 18 Sarah and after a recent upload + upgrade I haven't been able to use Monte Python with Planck likelihood. The message is the following: 

`Testing likelihoods for:
 ->Planck_highl_TTTEEE, Planck_lowl_EE, Planck_lowl_TT

Cannot use clik wrapper (cause = '/home/dinorah/anaconda2/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/dinorah/planck2018/code/plc_3.0/plc-3.01/lib/libclik.so)')
Cannot use clik_lensing wrapper (cause = '/home/dinorah/anaconda2/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/dinorah/planck2018/code/plc_3.0/plc-3.01/lib/libclik.so)')
 /!\ PyFITS is deprecated, please use astropy.io.fits
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/dinorah/montepython_public/montepython/run.py", line 32, in run
    custom_command)
  File "/home/dinorah/montepython_public/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/dinorah/montepython_public/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
  File "/home/dinorah/montepython_public/montepython/data.py", line 356, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/dinorah/montepython_public/montepython/data.py", line 485, in initialise_likelihoods
    elem, elem, folder, elem))
  File "<string>", line 1, in <module>
  File "/home/dinorah/montepython_public/montepython/likelihood_class.py", line 895, in __init__
    except clik.lkl.CError:
AttributeError: 'module' object has no attribute 'lkl'
`

Note that it flags the problem as missing GOMP_4.0. I have since checked that my gcc and g++ compilers (gcc and g++ version 5.5.0 20171010) contain the libgomp1, however the error remains! I'm unsure of how to proceed, given I've never had such a problem before. 

Thanks in advance

**Comment by brinckmann** [comment]
Hi Dinorah,

I would suggest simply reinstalling the Planck likelihoods from scratch. Pay close attention during the compilation process that it doesn't return any problems.

Best,
Thejs

**Comment by DinorahBarbosa** [comment]
Hi Thejs, 

I tried to reinstall plc code and while ./waf configure says it should be okay to proceed, the installation fails: 

`(base) dinorah@dinorah-270E5J-2570EJ ~/planck2018/code/plc_3.0/plc-3.01 $ ./waf install 
Waf: Entering directory `/home/dinorah/planck2018/code/plc_3.0/plc-3.01/build'
add plik/component_plugin/rel2015/fg2015.c
add plik/component_plugin/rel2015/corrnoise.c
add plik/component_plugin/rel2015/leakage.c
[ 59/141] Compiling build/src/python/clik/lkl.pyx.c
[ 60/141] Compiling build/src/python/clik/lkl_lensing.pyx.c
src/python/clik/lkl_lensing.pyx.c:4:20: fatal error: Python.h: No such file or directory
compilation terminated.

src/python/clik/lkl.pyx.c:4:20: fatal error: Python.h: No such file or directory
compilation terminated.

Waf: Leaving directory `/home/dinorah/planck2018/code/plc_3.0/plc-3.01/build'
Build failed
 -> task in 'lkl_lensing' failed with exit status 1 (run with -v to display more information)
 -> task in 'lkl' failed with exit status 1 (run with -v to display more information)`

Searching for python.h missing error specifically, I've install python-dev version for both python versions (2.7 and 3). However, it didn't seem to solve the issue. 

Best,
Dinorah

**Comment by brinckmann** [comment]
I'm not really able to help with unusual Planck likelihood errors. The best I can say is it seems like a linking issue with your Python version, as if may be you have a dud Python version installed and it finds that one instead of the one you want to use.

@DCHooper have you encountered this issue before?

Best,
Thejs

**Comment by dchooper** [comment]
Hi Dinorah,

I haven't encountered this issue before. 
Were you able to solve the problem? If not, perhaps try running with "./waf configure -v " to get more information about what the exact problem is. 

Best,
Deanna
