### ISSUE TITLE
Intel MKL FATAL ERROR

### ISSUE THREAD

**Issue by ravi398** [brinckmann/montepython_public#177]
Dear Sir
i am getting following error when run motepython.it run upto step deduced starting covariance matrix andthen  show following error
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.

all planck and class installation and compilation doesnot show any error.

thanks in advace
regards
Ravi sharma

**Comment by ravi398** [comment]
Dear sir

@brinckmann  would you  help ?

thanking you in advance.

regards
ravi sharma

**Comment by dchooper** [comment]
Hi Ravi,

This is not a MontePython issue, it's a problem with your python packages. Are you using anaconda? 
Can you check if your numpy version is up-to-date? Sometimes this can trigger the error message you are encountering.

Best,
Deanna
