### ISSUE TITLE
eBOSS problem

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#178]
Hi all, 

Recently through a friend I had access to eBOSS 16 likelihoods and while the BAO data alone runs fine, combined experiments like eBOSS 16 + Planck + Pantheon results in the following error. 

```
Error in Class: spectra_sigma(L:3337) :error in spectra_pk_at_k_and_z(pba,ppm,psp,k,z,&pk,pk_ic,&pk_cb,pk_cb_ic);
=>spectra_pk_at_k_and_z(L:813) :error in spectra_pk_at_z(pba, psp, logarithmic, z, spectrum_at_z, spectrum_at_z_ic, spectrum_cb_at_z, spectrum_cb_at_z_ic);
=>spectra_pk_at_z(L:386) :condition (ln_tau<psp->ln_tau[0]-small_deviation) is true; requested z was not inside of tau tabulation range (Requested 9.1824306428e+00, Min 9.2135468897e+00) 

```

I am aware that the error points to class (more specifically it appears to arise from the nonlinear.c file), but I have tried to fix the recommended solution for class and it hasn't work. Has anyone ever experienced something like this? Could this be an error in the likelihood itself? 

Thanks in advance, 

Dinorah

**Comment by dchooper** [comment]
Hi Dinorah,

It's odd that you only get the error when running the likelihood with other likelihoods: this could indicate that the different likelihoods are passing conflicting information to CLASS. Given the error message you are getting, maybe one of the likelihoods has a hard-coded maximum redshift: you can look for this within the likelihood .data and init file. 
I don't have access to the eBOSS 16 likelihood, so I'm afraid I can't help much more with the debugging/testing.

Best,
Deanna
