### ISSUE TITLE
Primordial inflation solve error , need help

### ISSUE THREAD

**Issue by shan1525** [brinckmann/montepython_public#179]
Hi everyone, 
I am using Monte-python 3.3 with CLASS 2.8.2 version. Firstly I made the Class with 'make' argument to use the python wrapper and set the python module in build file.Then I downloaded the cfitsio_3.47 to configure the planck code . I configured the planck code with lapack 3.7. and then sourced it to run the montepython. I wanted to run the montepython with a trial inflationary model for that I made a param file as below . I wanted to run the m^2*phi^2 model. for that i fixed other values as the following:
data.parameters['omega_b']      = [  2.2377,   None, None,      0.015, 0.01, 'cosmo']
data.parameters['omega_cdm']    = [ 0.12010,   None, None,     0.0013,    1, 'cosmo']
data.parameters['100*theta_s']  = [ 1.04110,   None, None,    0.00030,    1, 'cosmo']
data.parameters['tau_reio']     = [  0.0543,  0.004, None,      0.008,    1, 'cosmo']
data.parameters['V_0']          = [  0.,   None, None,     0.,    1, 'cosmo']
data.parameters['V_1']          = [  0.,   None, None,     0.,    1, 'cosmo']
data.parameters['V_2']          = [  -7,   -10, -3,     0.5,    1e-14, 'cosmo']
data.parameters['V_3']          = [  0.,   None, None,     0.,    1, 'cosmo']
data.parameters['V_4']          = [  0.,   None, None,     0.,    1, 'cosmo']
# Derived parameters

data.parameters['z_reio']          = [1, None, None, 0,     1,   'derived']
#data.parameters['Omega_Lambda']    = [1, None, None, 0,     1,   'derived']
data.parameters['YHe']             = [1, None, None, 0,     1,   'derived']
data.parameters['H0']              = [0, None, None, 0,     1,   'derived']
data.parameters['A_s']             = [0, None, None, 0,  1e-9,   'derived']
data.parameters['sigma8']          = [0, None, None, 0,     1,   'derived']

and I set the cosmo_arguments to run this model as 
data.cosmo_arguments['P_k_ini type'] = 'inflation_V'
data.cosmo_arguments['potential'] = 'polynomial'
data.cosmo_arguments['modes'] = 's,t'
But when I run the montepython with this param file, firstly it generates the covariance matrix and run the click files but I am getting the following error:

#  -LogLkl	1e+02omega_b    omega_cdm       100*theta_s     tau_reio        1e+14V_2        A_cib_217       xi_sz_cib       A_sz            ps_A_100_100    ps_A_143_143    ps_A_143_217    ps_A_217_217    ksz_norm        gal545_A_100    gal545_A_143    gal545_A_143_217gal545_A_217    galf_TE_A_100   galf_TE_A_100_143galf_TE_A_100_217galf_TE_A_143   galf_TE_A_143_217galf_TE_A_217   1e+03calib_100T 1e+03calib_217T A_planck        z_reio          YHe             H0              1e+09A_s        sigma8 
Error in Class: primordial_init(L:368) :error in primordial_inflation_solve_inflation(ppt,ppm,ppr);
=>primordial_inflation_solve_inflation(L:1209) :error in primordial_inflation_find_attractor(ppm, ppr, ppm->phi_pivot, ppr->primordial_inflation_attractor_precision_pivot, y, dy, &H_pivot, &dphidt_pivot);
=>primordial_inflation_find_attractor(L:1961) :error in primordial_inflation_check_potential(ppm,phi_0,&V_0,&dV_0,&ddV_0);
=>primordial_inflation_check_potential(L:2416) :condition (*V <= 0.) is true; This potential becomes negative at phi=0, before the end of observable inflation. It  cannot be treated by this code
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/sampler.py", line 46, in run
    mcmc.chain(cosmo, data, command_line)
  File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/mcmc.py", line 787, in chain
    newloglike = sampler.compute_lkl(cosmo, data)
  File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/sampler.py", line 776, in compute_lkl
    value = likelihood.loglkl(cosmo, data)
  File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/likelihood_class.py", line 953, in loglkl
    cl = self.get_cl(cosmo)
  File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/likelihood_class.py", line 192, in get_cl
    cl = cosmo.lensed_cl(int(l_max))
  File "classy.pyx", line 567, in classy.Class.lensed_cl
classy.CosmoSevereError: 
  But when I run the CLASS independently It is generating the primordial file. Can somebody tell me , what am i doing wrong here ? I will be very thankful. Please help me.

Regards,
shaz.

**Comment by shan15noob** [comment]
Hi @brinckmann  , Can you please suggest what could be the problem ? This would be very helpful.

**Comment by dchooper** [comment]
Hi Shaz,
I tried running CLASS with the values you quote, and I get the same error as you are getting with MontePython - are you sure you tested CLASS with these exact parameters?

The reason CLASS is giving you an error message is that your potential V(phi) is always negative (`data.parameters['V_2'] = [ -7, -10, -3, 0.5, 1e-14, 'cosmo']`). CLASS expects positive potentials - else it cannot find the minimum to determine the end of inflation. This is what CLASS is telling you with the message "This potential becomes negative at phi=0, before the end of observable inflation. It cannot be treated by this code".

For the m^2phi^2 model, you should have a positive V_2 parameter, so you want `data.parameters['V_2'] = [ 7, 10, 3, 0.5, 1e-14, 'cosmo']`.

Best,
Deanna

**Comment by shan1525** [comment]
Thanks a ton @dchooper  for your reply. It means a lot to us when you guys take some part of your time and give us your valuable suggestions. As you suggested I flipped the sign of the parameters and then ran the programme. I got the same error. So, I used your another suggestion about checking this ini file in CLASS and bingo , it was giving the same error. So, what I learned  is that you can't run a single m^2*phi^2 alone. Then I tried another function of phi and it ran in CLASS as well as when coupled with Montepython. Thanks  for the suggestions @dchooper . It worked . I really appreciate that.So anybody having similar issues , try some combinations of phi^2,Phi^0, and  phi^1 and write your param file as I have mentioned in my above comment.

regards,
shan

**Comment by dchooper** [comment]
Glad I could help! And thanks for the nice message!
