### ISSUE TITLE
Planck likelihood installation error

### ISSUE THREAD

**Issue by InterstellarDragon** [brinckmann/montepython_public#18]
I want to run MontePython on a cluster. Since I have no superuser rights, I use an installation of python in my home directory rather than in /usr/. I (seemingly) successfully installed Cython there.
However when attempting to run ./waf configure --install_all_deps I get the following:
`Checking python module 'cython' : ok 
Checking python module 'cython' : ok 
Checking cython version (>0.12) : 0.29 
Checking for program 'cython' : not found 
No suitable python distribution found Cause : '[Errno 2] No such file or directory: '/home/nedelko/planck/plc-2.0/bin/cython'' 
Compilation will continue without it (but I strongly advise that you install it)`

(everything else is fine and green)
So, waf is searching for Cython inside the /plc-2.0/ folder instead of the python installation and I can't figure out why.

Now, it says that I may run ./waf install anyway, but it crashes with this:
`Waf:` Entering directory /home/nedelko/planck/plc-2.0/build
add plik/component_plugin/rel2015/fg2015.c
add plik/component_plugin/rel2015/corrnoise.c
add plik/component_plugin/rel2015/leakage.c
Waf: Leaving directory /home/nedelko/planck/plc-2.0/build' Build failed Traceback (most recent call last): File "/home/nedelko/planck/plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Runner.py", line 150, in task_status return tsk.runnable_status() File "/home/nedelko/planck/plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Tools/fc.py", line 46, in runnable_status ret=tsk.runnable_status() File "/home/nedelko/planck/plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Tools/fc.py", line 40, in runnable_status return super(fc,self).runnable_status() File "/home/nedelko/planck/plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Task.py", line 313, in runnable_status new_sig=self.signature() File "/home/nedelko/planck/plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Task.py", line 302, in signature self.sig_implicit_deps() File "/home/nedelko/planck/plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Task.py", line 386, in sig_implicit_deps if prev==self.compute_sig_implicit_deps(): File "/home/nedelko/planck/plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Task.py", line 424, in compute_sig_implicit_deps upd(k.get_bld_sig()) File "/home/nedelko/planck/plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Node.py", line 459, in get_bld_sig self.cache_sig=ret=self.sig AttributeError: sig`

**Comment by brinckmann** [comment]
Did you source cython correctly?
Best,
Thejs

**Comment by InterstellarDragon** [comment]
> Edit: did you add cython to your PATH and PYTHONPATH? I can't remember exactly which one it needs to be added to.
> Best,
> Thejs

Did that, it now indeed finds Cython. However, it also still crashes with exactly the same error.
