### ISSUE TITLE
get_cl() return nan for TT, TE and EE

### ISSUE THREAD

**Issue by ShazAlvi** [brinckmann/montepython_public#180]
I am having an issue with MontePython v 2.2.2 and MontePython v 3.1.0. In the code I am using the Fake Bluebook likelihood for part of the multipoles and for the other part I am using get_cl() to get the temperature and polarization power spectra but when the fids are produced, I am getting nan for both Planck likelihood fids and those from get_cl() in my code. I checked that CLASSY and CLASS are working as they should i.e. their temperature and polarization power spectra are as they should. Furthermore, when I run this code on the remote cluster with its own version of MontePython (v 3.1.0) and CLASS, everything seems to be fine which means it's my local machine but I am unable to understand from where this problem is originating. Let me know what additional information is needed here (as I am a little clueless as to what I can add here).

**Comment by brinckmann** [comment]
Hi,

Can you check that you can run CLASS via the wrapper (there are some example scripts and ipython notebooks)? Have you had more than one Python version installed at any point? If CLASS was compiled with one version (e.g. Python 3) and MontePython uses another (e.g. Python 2) that would lead to communication problems between them. With multiple Python versions it can be tricky to keep track of which version is _actually_ used.

Best,
Thejs

**Comment by ShazAlvi** [comment]
Hi, 

I have a Conda virtual environment with Python2.7 and I made sure to compile CLASS and MontePython (compiling the setup.py) in the same environment but the problem persists. Furthermore, I am also running the code in the same environment.

**Comment by nblinov** [comment]
I had a seemingly identical issue where cl computation resulted in NaNs. I ended up reinstalling conda and recompiling class. this fixed the issue.
