### ISSUE TITLE
new parameter/Planck_highl_TT

### ISSUE THREAD

**Issue by SafaeCosmology** [brinckmann/montepython_public#182]
Hi !
I am new to using MontePython and CLASS, I have two questions if someone can answer me, please.
my first question, I added a new parameter in CLASS, and I modified only the input.c and background.c files , I didn't modify the perturbations.c file, because I just want to vary the background parameters in  MontePython , is this possible ?

And my second question, I want to use the  Planck_highl_TT data , but I don't want to vary the nuisance parameters, how i can fix these parameters ?.
Thank you
Best regards

**Comment by brinckmann** [comment]
Hi,

Any parameter correctly implemented in CLASS (and the wrapper, as needed), would work in MontePython. My slides from the Cambridge talk clarifies this on slide 30 onwards: [https://lesgourg.github.io/class-tour/Cambridge/180912_MontePython_Cambridge.pdf](https://lesgourg.github.io/class-tour/Cambridge/180912_MontePython_Cambridge.pdf)

If you need to reduce the number of parameters I would suggest using the 'lite' likelihoods, which have only one, as opposed to fixing the nuisance parameters. In this case you would use the likelihood `Planck_highl_TT_lite` in place of `Planck_highl_TT` and remove all nuisance parameters except `A_Planck`, i.e:
data.parameters['A_planck']          = [ 1.00061,   0.9,   1.1,     0.0025,     1, 'nuisance']

Best,
Thejs

**Comment by SafaeCosmology** [comment]
Thank you sir !

**Comment by SafaeCosmology** [comment]
Thank you sir .
