### ISSUE TITLE
Singular covariance matrix produced in run

### ISSUE THREAD

**Issue by alexreevesy** [brinckmann/montepython_public#188]
Dear all, 

I initially ran a small number of montepython steps without a covmat to generate some small chains which I then analysed using monteoython info and the --want-covmat argument. However, when I now try to use this covmat in a much longer run I get an error: 
  File "/rds/user/ar901/hpc-work/MONTE/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/rds/user/ar901/hpc-work/MONTE/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

- Looking at the covmat produced it is clearly singular with a few of the columns being 0s. What's going on? Is there something wrong with how I've set up my param file?

**Comment by brinckmann** [comment]
You probably need to run your chains longer before asking for a covmat. In particular, it's possible your input guesses (mean and/or sigmas) were very poor resulting in a very low acceptance rate.

Best,
Thejs

**Comment by alexreevesy** [comment]
Thanks Thejs!
