### ISSUE TITLE
installation on NERSC machine

### ISSUE THREAD

**Issue by mubecks** [brinckmann/montepython_public#19]
Hi I submitted the issue I've got before on here:
https://github.com/baudren/montepython_public/issues/118

I haven't try to solve the problem yet after then.
But at that time I tried to install montepython on NERSC, I loaded anaconda version for python 2.7+
Because of anaconda, all required package was already set.
But I got the error when I use the command

```
code/montepython> python montepython/MontePython.py --help

[Thu Sep 27 01:38:16 2018] [unknown] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(537):
MPID_Init(246).......: channel initialization failed
MPID_Init(647).......: PMI2 init failed: 1
Aborted (core dumped)
```

**Comment by brinckmann** [comment]
It looks to be MPI related, so I would start there with checking your mpi installation and mpi4py. Maybe have a look at this issue:
https://github.com/hpcugent/vsc-base/issues/216
Best,
Thejs

**Comment by mubecks** [comment]
Thank you for the comment!
I finally installed on my personal machine successfully!
Best,
YBLEE
