### ISSUE TITLE
Planck with dark energy models 

### ISSUE THREAD

**Issue by ShazAlvi** [brinckmann/montepython_public#191]
I am having a consistent problem running dark energy models (w0LCDM, w0waLCDM) with Planck only likelihood. When the chains are run with the covariance update option (default number for the flag --update) the chains stop updating midway. By this, I mean that the run_job.log file in SLURM and the chain files are no longer updated while the job continues. This does not happen when I set the --update flag off by passing --update 0. When updating option is set off, the chains run all the way through the duration of the job but when I restart the chains from the Covmat of the previous run, the chains stop again despite the setting of the update option. So, my question is: Under what circumstances can the chains stop updating like this in any likelihood? 

My priors are the following, 

```
data.parameters['omega_b']      = [ 2.2237,   None, None,  0.028, 0.01, 'cosmo']
data.parameters['omega_cdm']    = [0.1201,   None, None, 0.0027,    1, 'cosmo']
data.parameters['100*theta_s']  = [ 1.04090,   None, None,   3e-4,    1, 'cosmo']
data.parameters['ln10^{10}A_s'] = [ 3.054,   None, None, 0.0029,    1, 'cosmo']
data.parameters['n_s']          = [0.9651,   None, None, 0.0074,    1, 'cosmo']
data.parameters['tau_reio']     = [0.0590,   0.04, None,  0.013,    1, 'cosmo']
data.parameters['w0_fld']       = [-1.0,   None, -0.333,  0.1,    1, 'cosmo']

data.cosmo_arguments['use_ppf'] = 'yes'
data.cosmo_arguments['Omega_Lambda'] = 0
```
```
data.parameters['omega_b']      = [ 2.2237,   None, None,  0.028, 0.01, 'cosmo']
data.parameters['omega_cdm']    = [0.1201,   None, None, 0.0027,    1, 'cosmo']
data.parameters['100*theta_s']  = [ 1.04090,   None, None,   3e-4,    1, 'cosmo']
data.parameters['ln10^{10}A_s'] = [ 3.054,   None, None, 0.0029,    1, 'cosmo']
data.parameters['n_s']          = [0.9651,   None, None, 0.0074,    1, 'cosmo']
data.parameters['tau_reio']     = [0.0590,   0.04, None,  0.013,    1, 'cosmo']
data.parameters['w0_fld']       = [-1.0,   None, -0.333,  0.1,    1, 'cosmo']
data.parameters['wa_fld']       = [0.0,  None, 0.0,  0.1,    1, 'cosmo']
data.cosmo_arguments['use_ppf'] = 'yes'

data.cosmo_arguments['Omega_Lambda'] = 0
```

**Comment by brinckmann** [comment]
Your runs are probably diverging due to poor start guesses and/or poor starting covmat and/or inappropriate parameter boundaries. I'm going to guess the latter. I'd start with the latter and impose lower bounds on w0_fld and wa_fld. I don't quite remember off the top of my head what good values for wa_fld is, but at least setting w0_fld > -3.5 should be good.

Best,
Thejs

**Comment by ShazAlvi** [comment]
Do you mean w_fld > -3.5, the sum of w_0 and w_a?
