### ISSUE TITLE
Problem when running KV450 on wCDM

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#192]
Hi all, 

I have been trying to create chains for the wCDM model on MP with the following datasets: Planck2018+Pantheon+eBOSS+KV450. However, they appear to diverge when I include the KV450. I have no clue what I am doing wrong. I've included my .param as a .txt file below so you can take a look to see if there's any problems. 

Bests,

Dinorah 
[basewcdm.txt](https://github.com/brinckmann/montepython_public/files/6184608/basewcdm.txt)

**Comment by brinckmann** [comment]
w0 is a very poorly constrained parameter. Try setting a wider initial sigma (~0.1-0.5) and pass a Planck LCDM covmat.

Best,
Thejs
