### ISSUE TITLE
Bug in base param files when using CLASS v3.0 or later

### ISSUE THREAD

**Issue by dchooper** [brinckmann/montepython_public#196]
A restructuring in CLASS for the v3 release resulted in the BBN file being moved. As such, running any .param file that currently contains the line
`data.cosmo_arguments['sBBN file'] = data.path['cosmo']+'/bbn/sBBN.dat'
`
will result in an error. 

The fix is to change this line to
`data.cosmo_arguments['sBBN file'] = data.path['cosmo']+'/external/bbn/sBBN.dat'
`

This affects all of the base*.param files. The issue will be addressed asap in the next minor release.

**Comment by brinckmann** [comment]
Maybe we can intercept this error with a try/except so the code on the MontePython side isn't sensitive to the path in CLASS?  After all, we don't want to break backwards compatibility and we know in nearly all cases it will one of two possible paths, and if a user provides a different file they should be able to get the path right. Simply changing the path in the param files would simply move the problem over to anyone using an old class version, which a lot of people do.

Best,
Thejs

**Comment by brinckmann** [comment]
This has been fixed for v3.5.

When a 'sBBN file' is passed via data.cosmo_arguments MontePython will now check the path is compatible with the CLASS version being used and automatically correct it unless a flag `data.custom_bbn_file = True` is passed. So use this flag in case your path or file deviates from the default for your CLASS version. Note it is still possible to not pass a BBN file (and e.g. instead fix or vary YHe). The specifics of the change can be found in montepython/data.py by searching for "bbn".

CLASS 2.10.0 and later requires the path
data.cosmo_arguments['sBBN file'] = data.path['cosmo']+'/external/bbn/sBBN.dat'
CLASS 2.9.4 and earlier requires the path
data.cosmo_arguments['sBBN file'] = data.path['cosmo']+'/bbn/sBBN.dat'

I updated Planck 2018 example input files with:
data.cosmo_arguments['sBBN file'] = data.path['cosmo']+'/external/bbn/sBBN.dat'
\# BBN file path is automatically set to match CLASS version if 'sBBN file' is requested
\# You can force the code to use the exact BBN file passed above with flag
\#data.custom_bbn_file = True

Best,
Thejs
