### ISSUE TITLE
defining Omega_fld when running montepython

### ISSUE THREAD

**Issue by mahtaparsa** [brinckmann/montepython_public#197]
Considering the example.param file, when we define 
"data.cosmo_arguments['Omega_Lambda'] = 0.0",
for running the montepython code for models with dark energy fluid (in which Omega_tot is different from general relativity), how the code define the value of Omega_fld? 
Does it use the definition 
"pba->Omega0_lambda = new Omega_tot -pba->Omega0_k-pba->Omega0_g-pba->Omega0_ur-pba->Omega0_b-pba->Omega0_cdm-pba->Omega0_ncdm_tot-pba->Omega0_dcdmdr;"
in the input.c module for the fluid, or should one put 
""pba->Omega0_lambda = 0"
and then define it directly for Omega_fld instead, like 
"pba->Omega0_fld = new Omega_tot -pba->Omega0_k-pba->Omega0_g-pba->Omega0_ur-pba->Omega0_b-pba->Omega0_cdm-pba->Omega0_ncdm_tot-pba->Omega0_dcdmdr;",
in order to get correct results?

**Comment by brinckmann** [comment]
This is really a class question. On the MontePython side you can simply pass from MontePython any parameter implemented in CLASS.

With the line
`data.cosmo_arguments['Omega_Lambda'] = 0.0`
You are setting Omega_Lambda to 0. The class explanatory.ini file clearly states

# 8a) Dark energy contributions. At least one out of three conditions must be satisfied:
#     i)   'Omega_Lambda' unspecified.
#     ii)  'Omega_fld' unspecified.
#     iii) 'Omega_scf' set to a negative value. [Will be refered to as
#          unspecified in the following text.]
#     The code will then use the first unspecified component to satisfy the
#     closure equation (sum_i Omega_i) equals (1 + Omega_k)
#     (default: 'Omega_fld' and 'Omega_scf' set to 0 and 'Omega_Lambda' inferred
#     by code)

So you need to specify Omega_fld or Omega_scf if you set Omega_Lambad to 0.

In the class code the check in question is performed on line 2270-2778 of source/input.c for class 3.0 (current master), which define which of "flag1", "flag2", and "flag3" are true. 

Line 2805 onwards then specifies what happens depending on what the flags are set to, referring to default values on line 5332-5334 when not specified as input.

In your example I wouldn't expect CLASS to run, as you set Omega_Lambda to 0, while Omega0_fld and Omega0_scf are left at their defeault values.

It also sounds like you're looking for something with curvature, so you probably need to specify Omega_k as well.

Best,
Thejs
