### ISSUE TITLE
Error in Class: No lensed Cl computed

### ISSUE THREAD

**Issue by yashi0195** [brinckmann/montepython_public#198]
I am using Monte Python v3.4.0. When I am using likelihoods Planck_highl_TT, Planck_lowl_EE, Planck_lowl_TT, Planck_lensing, and trying to run with the command:

python montepython/MontePython.py run -p input/base2018TTonly_lensing.param -o chains/output -N 1000 

I am getting some error which says:

Error in Class: background_init(L:769) :condition (pba->shooting_failed == _TRUE_) is true; Shooting failed, try optimising input_get_guess(). Error message:

input_shooting(L:661) :error in input_find_root(&xzero, &fevals, ppr->tol_shooting_deltax_rel, &fzw, errmsg);
=>input_find_root(L:839) :error in input_fzerofun_1d(x1, pfzw, &f1, errmsg);
=>input_fzerofun_1d(L:912) :error in input_try_unknown_parameters(&input, 1, pfzw, output, error_message);
=>input_try_unknown_parameters(L:1285) :error in thermodynamics_init(&pr,&ba,&th);
=>thermodynamics_init(L:278) :error in thermodynamics_helium_from_bbn(ppr,pba,pth);
=>thermodynamics_helium_from_bbn(L:476) :could not open fA with name /mnt/98CA48B2CA488F06/MP_/class_public-master/bbn/sBBN.dat and mode "r"

**Comment by dchooper** [comment]
Hi,

I think your problem might be caused by the bug reported in issue #196, can you check if the solution proposed there solves your problem?

Best,
Deanna

**Comment by yashi0195** [comment]
Thanks a lot @dchooper . That helped!
