### ISSUE TITLE
Normalization for cl_tp in likelihood_class.py

### ISSUE THREAD

**Issue by wlxu** [brinckmann/montepython_public#20]
Hello,

In the get_cl() function in montepython/likelihood_class.py [ln 182-199],  the normalization step fails to account for cl['tp'] needing to be scaled by only one factor of 1.0e6. 

        for key in cl.iterkeys():
            # All quantities need to be multiplied by this factor, except the
            # phi-phi term, that is already dimensionless
            if key not in ['pp', 'ell']:
                cl[key] *= (T*1.e6)**2

As a result, when neglect_TD is turned off  in a mock CMB code (likelihood_mock_cmb) the cl['tp'] term is 6 orders of magnitude too large.

Thanks!

**Comment by brinckmann** [comment]
Hi,
Thanks for bringing this to my attention! It will be corrected for 3.1.
Best,
Thejs
