### ISSUE TITLE
MultiNest Segmentation Fault

### ISSUE THREAD

**Issue by srbPhy** [brinckmann/montepython_public#204]
Hi everyone, 

I am getting the following Segmentation fault on using MultiNest sampling. I have been trying to figure it out for the last few days, but none of my solutions seem to work. The error seems to be closely related to this issue (https://github.com/JohannesBuchner/PyMultiNest/issues/5) on the PyMultiNest page.

I am not sure if this is useful information, but whenever this Segfault occurs, a core.(some_number) file of a few GBs is also created. I am using MontePython 3.4 with MultiNest v3.10 and PyMultiNest v2.11.

Please let me know if you have any ideas to fix this.

Thanks in advance
Saurabh

> [d24cepyc093:14464] Signal: Segmentation fault (11)
[d24cepyc093:14464] Signal code: Address not mapped (1)
[d24cepyc093:14464] Failing at address: 0x2ba323e5b010
[d24cepyc093:14464] [ 0] /lib64/libpthread.so.0(+0xf630)[0x2ba63fcd2630]
[d24cepyc093:14464] [ 1] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/code/plc_3.0/plc-3.01/lib/libclik.so(simall_lkl+0x175)[0x2ba688e847aa]
[d24cepyc093:14464] [ 2] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/code/plc_3.0/plc-3.01/lib/libclik.so(lklbs_lkl+0x1dd)[0x2ba688e3709a]
[d24cepyc093:14464] [ 3] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/code/plc_3.0/plc-3.01/lib/libclik.so(distribution_lkl+0x148)[0x2ba688e495ac]
[d24cepyc093:14464] [ 4] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/code/plc_3.0/plc-3.01/lib/libclik.so(clik_compute+0x4c)[0x2ba688e35bf3]
[d24cepyc093:14464] [ 5] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/code/plc_3.0/plc-3.01/lib/python/site-packages/clik/lkl.cpython-37m-x86_64-linux-gnu.so(+0xa28b)[0x2ba688bfe28b]
[d24cepyc093:14464] [ 6] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/code/plc_3.0/plc-3.01/lib/python/site-packages/clik/lkl.cpython-37m-x86_64-linux-gnu.so(+0x8ac0)[0x2ba688bfcac0]
[d24cepyc093:14464] [ 7] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyObject_FastCallKeywords+0x4dc)[0x2ba63f68edcc]
[d24cepyc093:14464] [ 8] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x5159)[0x2ba63f6dcea9]
[d24cepyc093:14464] [ 9] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x10a)[0x2ba63f67324a]
[d24cepyc093:14464] [10] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x4f4)[0x2ba63f6d8244]
[d24cepyc093:14464] [11] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x10a)[0x2ba63f67324a]
[d24cepyc093:14464] [12] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x482c)[0x2ba63f6dc57c]
[d24cepyc093:14464] [13] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x1f1)[0x2ba63f628a71]
[d24cepyc093:14464] [14] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyFunction_FastCallKeywords+0x2b1)[0x2ba63f6733f1]
[d24cepyc093:14464] [15] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyEval_EvalFrameDefault+0x699)[0x2ba63f6d83e9]
[d24cepyc093:14464] [16] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyEval_EvalCodeWithName+0x1f1)[0x2ba63f628a71]
[d24cepyc093:14464] [17] /opt/crc/p/python/3.7.3/gcc/lib/libpython3.7m.so.1.0(_PyFunction_FastCallDict+0x2d0)[0x2ba63f629dc0]
[d24cepyc093:14464] [18] /opt/crc/p/python/3.7.3/gcc/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(+0x1455d)[0x2ba6588bc55d]
[d24cepyc093:14464] [19] /lib64/libffi.so.6(ffi_closure_unix64_inner+0x1fb)[0x2ba658acebdb]
[d24cepyc093:14464] [20] /lib64/libffi.so.6(ffi_closure_unix64+0x46)[0x2ba658acef54]
[d24cepyc093:14464] [21] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/MultiNest/lib/libmultinest_mpi.so(__cnested_MOD_loglike_f+0x69)[0x2ba684446c92]
[d24cepyc093:14464] [22] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/MultiNest/lib/libmultinest_mpi.so(__nested_MOD_samp+0x4c5)[0x2ba684466d7f]
[d24cepyc093:14464] [23] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/MultiNest/lib/libmultinest_mpi.so(__nested_MOD_clusterednest+0x1b223)[0x2ba68448504e]
[d24cepyc093:14464] [24] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/MultiNest/lib/libmultinest_mpi.so(__nested_MOD_nestsample+0x10d6)[0x2ba684494358]
[d24cepyc093:14464] [25] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/MultiNest/lib/libmultinest_mpi.so(__nested_MOD_nestrun+0x17d6)[0x2ba684495f05]
[d24cepyc093:14464] [26] /afs/crc.nd.edu/user/s/sbansal/Softwares/Cosmo/myLib/MultiNest/lib/libmultinest_mpi.so(run+0x252)[0x2ba684446b27]
[d24cepyc093:14464] [27] /lib64/libffi.so.6(ffi_call_unix64+0x4c)[0x2ba658acedec]
[d24cepyc093:14464] [28] /lib64/libffi.so.6(ffi_call+0x1f5)[0x2ba658ace715]
[d24cepyc093:14464] [29] /opt/crc/p/python/3.7.3/gcc/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x6a6)[0x2ba6588bce16]

**Comment by arsalanadil** [comment]
Hi Saurabh,

I'm wondering if you ever managed to solve this problem? I'm seeing the same issue on my side, where everything seems to work well using the default Metropolis Hastings but this issue pops up with MultiNest. I'd love to hear your insights on this.

Thanks!
Arsalan

**Comment by srbPhy** [comment]
Hi Arsalan @arsalanadil,

I faced a similar issue, unfortunately I was unable to fix it. So I ended up using the default Metropolis Hastings instead of MultiNest. After a lot of digging, my conclusion was that MultiNest was scanning "unphysical" parts of the parameter space, whereas MH was able to avoid those regions. By "unphysical" I mean that the model predictions were so far from the Planck measurements that the code failed. I could be wrong here, but that's the best explanation I could come up with.

One suggestion: Could you try doing the same run, but without using the 'low l' datasets? Please let us know if you get the same error.

Thanks
Saurabh

**Comment by arsalanadil** [comment]
Thanks for the prompt response Saurabh. I didn't expect this issue to be stemming from the Planck likelihoods but that might be a good guess. I'll look into it and get back to you. I've successfully used MultiNest for other projects in the past, but this time a key difference is that CLASS calls my external python code on each run (via the external_Pk feature), but that code uses multiprocessing via Pool which might be causing some confusion with resource allocation. 

Still, this error seems to occur somewhat randomly after a few hundred iterations (which also makes it hard to debug).
