### ISSUE TITLE
Difference in getdist-gui and montepython analyse

### ISSUE THREAD

**Issue by shan1525** [brinckmann/montepython_public#209]
Hi everone,
First of all I wanted to thank the CLASS and Monte Python team for making such a beautiful program ( Although it seems very late to say this, but whatever !) . Because I, being a naive in programming, was able to modify the program thanks to the comments preceding and succeding the programs in all the modules to guide with it. 

Now coming back to query;  I modified the class with a background fluid approach, with a new case of fluid equation of state. ( I am attacing that model below).
[Fld_equation_of_state.pdf](https://github.com/brinckmann/montepython_public/files/6530852/Fld_equation_of_state.pdf)

 Then , I ran the montepython  with Metropolice Hasting algorithm which went quite well .But my problem arises when I analyse those chains in getdist-gui and the montepython analyze module. In getdist-gui I get a multimodel kind of result and when I check it with info of montepython I get a perfect gaussian result. Can somebody enlighten me with the differences ? I am attaching both the outputs below.
![getdist-gui](https://user-images.githubusercontent.com/70058996/119320697-7aba9b00-bc99-11eb-99ce-5960a50abf8e.png)
[shan6_triangle.pdf](https://github.com/brinckmann/montepython_public/files/6530880/shan6_triangle.pdf)

Best regards,
shan.

**Comment by dchooper** [comment]
Hi Shan,
Thanks a lot for your nice comments, and for being so active here with the github issues!

When MontePython produces the final posterior plots, there are several different smoothing methods used to produce actual contours instead of a series of points from the chain files. I think what is happening here is that the chains themselves are finding a slightly multimodal posterior (closer to the getdist output), and the MontePython smoothing options are hiding this.

To see what your chains would look like without any smoothing, you can add the following when running the `info` command:
`--gaussian-smoothing 0 --interpolation-smoothing 1`
(The default values here are 0.5 and 4 respectively).
You could also increase the number of bins to more clearly see where the distributions are (`--bins 30`).

If you don't physically expect a multimodal distribution, I would say your chains are not converged and need more runtime. If you do expect a multimodal distribution, I would propose running with either PolyChord or MultiNest instead of Metropolis Hastings.

Best,
Deanna

**Comment by shan1525** [comment]
Hi @dchooper ,

Thank you for always helping us out about our queries. I tried the smoothing techniques that you mentioned , but still it  didn't match the getdist-gui output. I was going through the issues of montepython , and in one of the issues it was suggested that running info with --keep-non-markovian and --keep-fraction 0.7 will give the default getdist output. But it didn't help either. Anyway I will try a longer run to get a nice convergence. Then I will again compare those chains in info and getdist and see if I get the same result or not. Meanwhile, as you suggested further,  I will also try with the nested sampling and check the output. 
Why I was so persistent with getdist-gui because I wanted to compare two different chains and get a comparison betwwen two contours. By doing so I wanted to check what changes are happening in adding different likelihoods. To be more clear I am attaching a sample output file where two contours are compared. This is what I am talking about.
[getdist.pdf](https://github.com/brinckmann/montepython_public/files/6538977/getdist.pdf)

As I am not familiar enough with info so ,If you don't mind me asking ,can we do this with info? 
And Thanks again @dchooper for your invaluable suggestions.  

Best,
shan.

**Comment by dchooper** [comment]
Hi Shan,
Hmm, odd that the smoothing didn't help. Perhaps aiming for better convergence is the best idea for now.

You can plot multiple contours in the same plot with MontePython by passing different folders when running info. For example:
`python montepython/MontePython.py info chains/run1 chains/run2 chains/run3 ... `
The contours will be plotted in the order you pass them here, so in this case run1 would be in the background and run3 would be in the foreground.

You can also pass an additional plotting file with many more options, even calling an extra python script to add more things to the plots (one classic example is if you want to plot an H_0 or S_8 band in the background) - you can find most of the plotting options in `plot_files/example.plot`, and an example of an additional python script for H_0 and S_8 in the same folder. To pass the extra plotting file, you would use e.g. `--extra plot_files/example.plot.`

Best,
Deanna

**Comment by brinckmann** [comment]
Hi Shan,

A few things play in here regarding getting agreement with GetDist

1) Smoothing
As Deanna mentioned, `--gaussian-smoothing 0 --interpolation-smoothing 1` turns off smoothing in MontePython for the 2d (off-diagonal) elements of the triangle plot. Additionally, `--posterior-smoothing 0` turns off smoothing for the 1d (diagonal) elements.
Note that GetDist also uses smoothing by default, so to get better agreement you'll have to turn that off too.

2) Non-markovian points and removing early part of chains
MontePython uses a tracking scheme to determine which part of the chains is Markovian, which doesn't exist in CosmoMC (and therefore GetDist). To keep that part you use the flag you mentioned
`--keep-non-markovian`
By default GetDist instead removes the first 30% of the chains. This is obtained by the other flag you mentioned
`--keep-fraction 0.7`

3) Burn-in
MontePython has a scheme for removing burn-in, which GetDist also doesn't have (instead relying on removing the first 30% of the chains). This requires modifying montepython/analyze.py where you have the two lines 
`LOG_LKL_CUTOFF = 3`
`# LOG_LKL_CUTOFF = 1e300`
Simply invert the comment as if you were using MultiNest to turn off removing the burn-in.

Best,
Thejs

**Comment by shan1525** [comment]
Hi @dchooper  and @brinckmann , 

Thank you so much for your responses. I will work on what you guys have suggested. You guys are doing an amazing job. I think I can understand the issue now. Thanks again for your help. I will close the issue now.
