### ISSUE TITLE
Bug with the info command 

### ISSUE THREAD

**Issue by LeoVacher** [brinckmann/montepython_public#210]
Hi everyone,

I have been running MontePython with an alternative version of CLASS where I implemented a dark energy model driven by a scalar field. Everything went fine until I tried to get the contour plots using the info command. No matter what I try I get the following error message :

`
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/datadec/users/users/lvacher/downloads/montepython_public/montepython/run.py", line 32, in run
    custom_command)
  File "/datadec/users/users/lvacher/downloads/montepython_public/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/datadec/users/users/lvacher/downloads/montepython_public/montepython/initialise.py", line 59, in initialise
    analyze(command_line)
  File "/datadec/users/users/lvacher/downloads/montepython_public/montepython/analyze.py", line 167, in analyze
    compute_posterior(information_instances)
  File "/datadec/users/users/lvacher/downloads/montepython_public/montepython/analyze.py", line 391, in compute_posterior
    info.define_ticks()
  File "/datadec/users/users/lvacher/downloads/montepython_public/montepython/analyze.py", line 2296, in define_ticks
    if abs(x_range[0]-bounds[0]) < self.span[i]/self.bins:
numpy.core._exceptions.UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')`

Everything was running fine with class_public or another modified class version and I don't know what can be the origin of the problem. Maybe my parameter's name ? Did anyone encountered something similar ? 

Thank you in advance for your help.

Best,

Léo

**Comment by brinckmann** [comment]
Hi Léo,

Can you try first with the info flag `--minimal` and then instead with `--noplot` ? These do different minimal analyses and might help inform us what the problem is, or at least at what point in the analysis it breaks down.

You can also simply change the suspicious parameter name in the log.param, but please make a backup of your original log.param first (that you will need if you restart). Usually modifying the log.param is a bad idea, but it's usually OK for info. You'll just need to restore the original one before continuing a run.

Best,
Thejs

**Comment by LeoVacher** [comment]
Hi Thejs,

Thank you so much for answering so quickly ! The `--minimal` info flag seems to run without problem but the '--noplot' gives back the exact same error message. I will try playing with the log and the parameter names to find if I can find the problematic one.

Best,
Léo

**Comment by shan1525** [comment]
Hi @LeoVacher , 

Can you share your log.param and something.paramnames file with us. It might be helpful in determining the issue. 

Best, 
shan.

**Comment by LeoVacher** [comment]
Hi ! 
Thanks for your answer. For sure ! here is the log.param. All the "cdf" indices are related to the scalar field.
`#------Experiments to test (separated with commas)-----

data.experiments=['Planck_highl_TTTEEE', 'Planck_lowl_EE', 'Planck_lowl_TT', 'Planck_lensing', 'bao_boss_dr12', 'bao_smallz_2014']

#------ Settings for the over-sampling.
# The first element will always be set to 1, for it is the sampling of the
# cosmological parameters. The other numbers describe the over sampling of the
# nuisance parameter space. This array must have the same dimension as the
# number of blocks in your run (so, 1 for cosmological parameters, and then 1
# for each experiment with varying nuisance parameters).
# Note that when using Planck likelihoods, you definitely want to use [1, 4],
# to oversample as much as possible the 14 nuisance parameters.
# Remember to order manually the experiments from slowest to fastest (putting
# Planck as the first set of experiments should be a safe bet, except if you
# also have LSS experiments).
# If you have experiments without nuisance, you do not need to specify an
# additional entry in the over_sampling list (notice for instance that, out of
# the three Planck likelihoods used, only Planck_highl requires nuisance
# parameters, therefore over_sampling has a length of two (cosmology, plus one
# set of nuisance).
data.over_sampling=[1, 5]

#------ Parameter list -------

# data.parameters[class name] = [mean, min, max, 1-sigma, scale, role]
# - if min max irrelevant, put to None
# - if fixed, put 1-sigma to 0
# - if scale irrelevant, put to 1, otherwise to the appropriate factor
# - role is either 'cosmo', 'nuisance' or 'derived'. You should put the derived
# parameters at the end, and in case you are using the `-j fast` Cholesky
# decomposition, you should order your nuisance parameters from slowest to
# fastest.

# Cosmological parameters list

data.parameters['omega_b']      = [  2.2377,   None, None,      0.015, 0.01, 'cosmo']
data.parameters['omega_cdm']    = [ 0.12010,   None, None,     0.0013,    1, 'cosmo']
data.parameters['100*theta_s']  = [ 1.04110,   None, None,    0.00030,    1, 'cosmo']
data.parameters['ln10^{10}A_s'] = [  3.0447,   None, None,      0.015,    1, 'cosmo']
data.parameters['n_s']          = [  0.9659,   None, None,     0.0042,    1, 'cosmo']
data.parameters['z_reio']       = [       8,      1,   50,        0.5,    1, 'cosmo']
#data.parameters['tau_reio']     = [  0.0543,  0.004, None,      0.008,    1, 'cosmo']

data.parameters['phi_prime_ini_cdf'] = [ 0 , -0.1 , 0.1,  0.001,    1, 'cosmo']
data.parameters['Omega_cdf'] = [ 0 , 0  , 1e-8,   1e-11,    1, 'cosmo']
data.parameters['phi_ini_cdf'] = [0,-0.1, 0.1, 0.001  ,    1, 'cosmo']
data.parameters['b_h_cdf'] = [ 0, -0.001 , 0.001,   0.0005,    1, 'cosmo']
data.parameters['b_m_cdf'] = [ 0, - 0.001 , 0.001,   0.0005,    1, 'cosmo']
#data.parameters['cdf_poly_ampl'] = [ 1e-8,  -0.1 , 0.1,   0.0001,    1, 'cosmo']
#data.parameters['cdf_poly_exponent'] = [ 1,  0.99 , 1.11,	0.0001,    1, 'cosmo']
#data.parameters['bbn_alpha_sensitivity'] = [ 1,  0 , 1.5,	0.5,    1, 'cosmo']

# Nuisance parameter list, same call, except the name does not have to be a class name

data.parameters['A_cib_217']         = [    47.2,     0,   200,     6.2593,     1, 'nuisance']
data.parameters['cib_index']         = [    -1.3,  -1.3,  -1.3,          0,     1, 'nuisance']
data.parameters['xi_sz_cib']         = [    0.42,     0,     1,       0.33,     1, 'nuisance']
data.parameters['A_sz']              = [    7.23,     0,    10,     1.4689,     1, 'nuisance']
data.parameters['ps_A_100_100']      = [   251.0,     0,   400,     29.438,     1, 'nuisance']
data.parameters['ps_A_143_143']      = [    47.4,     0,   400,     9.9484,     1, 'nuisance']
data.parameters['ps_A_143_217']      = [    47.3,     0,   400,     11.356,     1, 'nuisance']
data.parameters['ps_A_217_217']      = [   119.8,     0,   400,     10.256,     1, 'nuisance']
data.parameters['ksz_norm']          = [    0.01,     0,    10,     2.7468,     1, 'nuisance']
data.parameters['gal545_A_100']      = [    8.86,     0,    50,     1.8928,     1, 'nuisance']
data.parameters['gal545_A_143']      = [   11.10,     0,    50,     1.8663,     1, 'nuisance']
data.parameters['gal545_A_143_217']  = [    19.8,     0,   100,     3.8796,     1, 'nuisance']
data.parameters['gal545_A_217']      = [    95.1,     0,   400,     6.9759,     1, 'nuisance']
data.parameters['galf_EE_A_100']     = [   0.055, 0.055, 0.055,          0,     1, 'nuisance']
data.parameters['galf_EE_A_100_143'] = [   0.040, 0.040, 0.040,          0,     1, 'nuisance']
data.parameters['galf_EE_A_100_217'] = [   0.094, 0.094, 0.094,          0,     1, 'nuisance']
data.parameters['galf_EE_A_143']     = [   0.086, 0.086, 0.086,          0,     1, 'nuisance']
data.parameters['galf_EE_A_143_217'] = [    0.21,  0.21,  0.21,          0,     1, 'nuisance']
data.parameters['galf_EE_A_217']     = [    0.70,  0.70,  0.70,          0,     1, 'nuisance']
data.parameters['galf_EE_index']     = [    -2.4,  -2.4,  -2.4,          0,     1, 'nuisance']
data.parameters['galf_TE_A_100']     = [   0.114,     0,    10,   0.038762,     1, 'nuisance']
data.parameters['galf_TE_A_100_143'] = [   0.134,     0,    10,   0.030096,     1, 'nuisance']
data.parameters['galf_TE_A_100_217'] = [   0.482,     0,    10,   0.086185,     1, 'nuisance']
data.parameters['galf_TE_A_143']     = [   0.224,     0,    10,   0.055126,     1, 'nuisance']
data.parameters['galf_TE_A_143_217'] = [   0.664,     0,    10,   0.082349,     1, 'nuisance']
data.parameters['galf_TE_A_217']     = [    2.08,     0,    10,    0.27175,     1, 'nuisance']
data.parameters['galf_TE_index']     = [    -2.4,  -2.4,  -2.4,          0,     1, 'nuisance']
data.parameters['calib_100T']        = [  999.69,     0,  3000,    0.61251, 0.001, 'nuisance']
data.parameters['calib_217T']        = [  998.16,     0,  3000,    0.63584, 0.001, 'nuisance']
data.parameters['calib_100P']        = [   1.021, 1.021, 1.021,          0,     1, 'nuisance']
data.parameters['calib_143P']        = [   0.966, 0.966, 0.966,          0,     1, 'nuisance']
data.parameters['calib_217P']        = [   1.040, 1.040, 1.040,          0,     1, 'nuisance']
data.parameters['A_cnoise_e2e_100_100_EE'] = [ 1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_cnoise_e2e_143_143_EE'] = [ 1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_cnoise_e2e_217_217_EE'] = [ 1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_100_100_TT'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_143_143_TT'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_143_217_TT'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_217_217_TT'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_100_100_EE'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_100_143_EE'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_100_217_EE'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_143_143_EE'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_143_217_EE'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_sbpx_217_217_EE'] = [       1,     1,     1,          0,     1, 'nuisance']
data.parameters['A_planck']          = [ 1.00061,   0.9,   1.1,     0.0025,     1, 'nuisance']
data.parameters['A_pol']             = [       1,     1,     1,          0,     1, 'nuisance']

# Derived parameters

#data.parameters['z_reio']          = [1, None, None, 0,     1,   'derived']
data.parameters['Omega_Lambda']    = [1, None, None, 0,     1,   'derived']
data.parameters['YHe']             = [1, None, None, 0,     1,   'derived']
data.parameters['H0']              = [0, None, None, 0,     1,   'derived']
data.parameters['A_s']             = [0, None, None, 0,  1e-9,   'derived']
data.parameters['sigma8']          = [0, None, None, 0,     1,   'derived']
data.parameters['phi_final_cdf']          = [0, None, None, 0,     1,   'derived']

# Other cosmo parameters (fixed parameters, precision parameters, etc.)

#data.cosmo_arguments['sBBN file'] = data.path['cosmo']+'/bbn/sBBN.dat'
data.cosmo_arguments['k_pivot'] = 0.05

# The base model features two massless
# and one massive neutrino with m=0.06eV.
# The settings below ensures that Neff=3.046
# and m/omega = 93.14 eV
data.cosmo_arguments['N_ur'] = 2.0328
data.cosmo_arguments['N_ncdm'] = 1
data.cosmo_arguments['m_ncdm'] = 0.06
data.cosmo_arguments['T_ncdm'] = 0.71611

#Dilaton

data.cosmo_arguments['cdf_poly_ampl'] = 0
data.cosmo_arguments['cdf_poly_exponent'] = 1
data.cosmo_arguments['cdf_potential_type'] ='polynomial'
data.cosmo_arguments['bbn_alpha_sensitivity'] = 1
#data.cosmo_arguments['Omega_cdf'] = 1e-10
#data.cosmo_arguments['phi_prime_ini_cdf'] = 1e5
#data.cosmo_arguments['phi_ini_cdf'] = 0

# These two are required to get sigma8 as a derived parameter
# (class must compute the P(k) until sufficient k)
data.cosmo_arguments['output'] = 'mPk'
data.cosmo_arguments['P_k_max_h/Mpc'] = 1.

# The Planck Lensing likelihood is more precise when the non-linear effects are taken
# into consideration. For this you can use halofit (default) or hmcode.
# If you are running an exotic model for which the non-linearities cannot be
# computed with either of these codes, you are advised to comment out the following line.
data.cosmo_arguments['non linear'] = 'halofit'


#------ Mcmc parameters ----

data.N=10
data.write_step=5
`
Best,
Léo

**Comment by LeoVacher** [comment]
Hi ! 
Thanks for your answer. For sure ! here is the log.param. All the "cdf" indices are related to the scalar field.

[log.param.zip](https://github.com/brinckmann/montepython_public/files/6547183/log.param.zip)

Best,
Léo

**Comment by brinckmann** [comment]
Are you using python 2 or 3? Do you have another system where you could analyze the chains (i.e. different configuration of python packages, not necessarily different python version, but at least different numpy version)? Otherwise you can send your chains directory to the email address on my profile and I'll see if I can analyze it on a different system.

Best,
Thejs

**Comment by LeoVacher** [comment]
Hi Thejs,

I am using python3. Thanks for the good idea ! Sadly, I still obtain the same error when I try to run info on my personal laptop (with a different numpy version). I don't want to take too much of your time so I will try to find another way around this. I'll send my chains by mail if I get completely out of ideas !

Best,

Léo

**Comment by brinckmann** [comment]
There was a spurious space between a minus and the rest of the float in a parameter boundary, i.e. "- 0.001" instead of "-0.001" leading to
1) when analyzing it simply returns an error. Removing the space allows it to analyze the chains, but
2) MontePython treated it as a fixed parameter in the run when it was supposed to have been varied
The solution is to remove the spurious space and start over.

So the issue has been found, but it is probably not something we want to invest time in fixing. I'm just leaving the solution here in case others encounter the problem in the future.

Best,
Thejs
