### ISSUE TITLE
Problems with -- extra option in MontePython.py info 

### ISSUE THREAD

**Issue by am610** [brinckmann/montepython_public#214]
I am trying to feed in an extra file via the --extra option, inside which I list in the changes to the parameters, which I want to label differently in the plots, than that assigned originally. As well as I want to change the colour schemes. Both both of these don't seem to work in the output plots.  My extra file has the following lines :

```
import matplotlib.pyplot as plt
info.to_change = {'w0_fld': 'w_0'}
info.to_plot = {'Omega_m','w_0' }
info.cmaps = [plt.cm.Blues, plt.cm.Greens, plt., plt.cm.winter, plt.cm.Purples, plt.cm.autumn]
info.cm = ['b','r','g','lime', 'seagreen','darkgreen']
```
running the following command : 

`python montepython/MontePython.py info output/test/ --no-mean --extra input/plot.extra --all`

I would still get the w0_fld label in the plot and still the red-themed plots. 
Any help ?
thanks

**Comment by am610** [comment]
Ok worked. I figured out I was missing the `r$$` sign.

**Comment by am610** [comment]
But the color doesnt seem to change

**Comment by dchooper** [comment]
Hi,

I think you are using the wrong syntax for the colours: to my knowledge, montepython doesn't have a info.cm or info.cmaps function. To define your own colours, you can use e.g.:
`info.MP_color = {'Red':['#E37C80','#CE121F'],'Blue':['#7A98F6','#1157EF'],'Green':['#88B27A','#297C09'],'Orange' ['#F3BE82','#ED920F'],'Grey':['#ABABAB','#737373'],'Purple':['#B87294','#88004C']}`
and
`info.MP_color_cycle = [info.MP_color['Green'], info.MP_color['Orange'], info.MP_color['Blue']]`
as shown in the provided example.plot.

Let me know if with this syntax you can change the colours.
Best,
Deanna

**Comment by brinckmann** [comment]
Note it should be fairly straightforward to add color maps by hand if you want different color options and don't want to use hex color codes. You can change `montepython/analyze.py` around lines 2072-2087, which gets used if you don't set `info.MP_color` and `info.MP_color_cycle` in the plot file. You'd want to define the color map prior to this and pass specific colors from the map to `MP_color` using the same syntax but replacing the hex code. Note that a list of two hex codes are passed for each color, as they give the colors for the 1- and 2-sigma contours. `MP_color` defines the colors available, while you pick which colors are used for the plot with `MP_color_cycle`, while `alphas` (or `info.alphas` in the plot file) is a list that sets the transparency of the colors.

Best,
Thejs

**Comment by am610** [comment]
great, thanks a lot. Closing this thread now.
