### ISSUE TITLE
Error in Class: Class did not read input parameter(s): w0_fld

### ISSUE THREAD

**Issue by PhyPy-Dm** [brinckmann/montepython_public#215]
Hi, everyone
    I create my .param file and set `w0_fld` as a 'cosmo' parameter, but when I type `MontePython.py run` to run my chains, the error as following occurs:

```
Cosmological Module Error:
 /|\   Something went wrong when calling CLASS
/_o_\  Error in Class: Class did not read input parameter(s): w0_fld
```
Is there anyone knows how to fix this problem?

Best
PhyPy-Dm

**Comment by PhyPy-Dm** [comment]
Hi, everyone  
  well, I've fixed above problem, but a new problem appears,:

```
for n in {1..4};do python montepython/MontePython.py run -o lcdm/cmbsn -p input/cmb_sn.param -N 10000 -f 1.5 --conf my.conf;done
Running Monte Python v3.4.0

with CLASS v3.0.1

Testing likelihoods for:
 ->distance_prior, JLA

Creating lcdm/cmbsn/2021-05-31_10000__1.txt


Deduced starting covariance matrix:

['omega_b', 'omega_cdm', '100*theta_s', 'w0_fld', 'alpha', 'beta', 'M', 'Delta_M']
[[7.84e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 2.56e-06 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 9.00e-08 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 2.50e-03 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-06 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 4.00e-04 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05]]
Update routine is enabled with value 50 (recommended: 50)
This number is rescaled by cycle length 8 (N_slow + f_fast * N_fast) to 400

#  -LogLkl	1e+02omega_b    omega_cdm       100*theta_s     w0_fld          alpha           beta            M               Delta_M         H0              Omega_m         Omega0_fld      
Segmentation fault (core dumped)
 /!\ Appending to an existing folder: using the log.param instead of
     input/cmb_sn.param

```
who knows how to deal with the erors?

best
PhyPy-Dm

**Comment by shan1525** [comment]
Hi @PhyPy-Dm , 
How did you initialise your parameters?? Can you share your param file?? 

Best, 
Shan.

**Comment by PhyPy-Dm** [comment]
Hi @shan1525 
     Those are my .param file and likelihood file, and for convenience I show my data at the end of the likelihood file.
[cmbsn.txt](https://github.com/brinckmann/montepython_public/files/6570474/cmbsn.txt)
[likl.txt](https://github.com/brinckmann/montepython_public/files/6570479/likl.txt)

Best
PhyPy-Dm

**Comment by shan1525** [comment]
Hi @PhyPy-Dm , 
Have you run the program only with jla and without the distance_prior likelihood?? Just to check if it runs . 

Best, 
Shan.

**Comment by PhyPy-Dm** [comment]
Hi@shan1525
I have run my program ,i .e. `python montepython/MontePython.py run  -o lcdm/jla -p input/jla.param --conf my.conf -N 10000` with  jla (jla.param is the initial file in input file and I did'nt modify it ) and without distance_prior likelihood, there's no errors.

Best
PhyPy-Dm

**Comment by PhyPy-Dm** [comment]
Hi@shan1525
I run the program `python montepython/MontePython.py run -o lcdm/cmbsn -p input/cmbsn.param --conf my.conf -N 20`, the program was aborted with `Segmentation fault (core dumped)`

details are as follows:

```
python montepython/MontePython.py run -o lcdm/cmbsn -p input/cmbsn.param --conf my.conf -N 20
Running Monte Python v3.4.0

with CLASS v3.0.1

Testing likelihoods for:
 ->JLA

Creating lcdm/cmbsn/2021-05-31_20__1.txt


Deduced starting covariance matrix:

['omega_b', 'omega_cdm', '100*theta_s', 'w0_fld', 'alpha', 'beta', 'M', 'Delta_M']
[[7.84e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 2.56e-06 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 9.00e-08 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 2.50e-03 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-06 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 4.00e-04 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05]]
Update routine is enabled with value 50 (recommended: 50)
This number is rescaled by cycle length 8 (N_slow + f_fast * N_fast) to 400

#  -LogLkl	1e+02omega_b    omega_cdm       100*theta_s     w0_fld          alpha           beta            M               Delta_M         H0              Omega_m         Omega0_fld      
Segmentation fault (core dumped)
```
Best
PhyPy-Dm

**Comment by shan1525** [comment]
Hi @PhyPy-Dm , 

So when you run your program with jla.pram, it is running. But when you run only the jla likelihood in cmbsn.param, it is also giving the segmentation fault error as it was giving with the jla+distance_prior likelihood??

**Comment by PhyPy-Dm** [comment]
Hi @PhyPy-Dm
Yes, that's the point.

Best
PhyPy-Dm

**Comment by shan1525** [comment]
Hi @PhyPy-Dm , 

In your cosmological parameters list priors for wa_fluid is missing. Add it, and run it only with jla, check it if it runs.

Best, 
Shan.

**Comment by PhyPy-Dm** [comment]
Hi @shan1525 
I add wa_fid as cosmo_arguments `data.cosmo_arguments['wa_fld'] = 0` in cmbsn.param, Segmentation fault (core dumped).

```
python montepython/MontePython.py run -o lcdm/cmbsn -p input/cmbsn.param --conf my.conf -N 20
Running Monte Python v3.4.0

with CLASS v3.0.1

Testing likelihoods for:
 ->JLA

Creating lcdm/cmbsn/2021-05-31_20__1.txt


Deduced starting covariance matrix:

['omega_b', 'omega_cdm', '100*theta_s', 'w0_fld', 'alpha', 'beta', 'M', 'Delta_M']
[[7.84e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 2.56e-06 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 9.00e-08 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 2.50e-03 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-06 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 4.00e-04 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05]]
Update routine is enabled with value 50 (recommended: 50)
This number is rescaled by cycle length 8 (N_slow + f_fast * N_fast) to 400

#  -LogLkl	1e+02omega_b    omega_cdm       100*theta_s     w0_fld          alpha           beta            M               Delta_M         H0              Omega_m         Omega0_fld      
Segmentation fault (core dumped)
```

and when I add wa_fld as cosmological parameter `data.parameters['wa_fld']      = [-0.1,  -0.5, 0.5, 0.05,      1, 'cosmo']`
the same error raised

```
python montepython/MontePython.py run -o lcdm/cmbsn -p input/cmbsn.param --conf my.conf -N 20
 /!\ Appending to an existing folder: using the log.param instead of
     input/cmbsn.param
Running Monte Python v3.4.0

with CLASS v3.0.1
 /!\ CLASS set to branch b'', wrt. the one used in the log.param: b''.
 /!\ CLASS set to version b'', wrt. the one used in the log.param: b''.

Testing likelihoods for:
 ->JLA

Creating lcdm/cmbsn/2021-05-31_20__2.txt


Deduced starting covariance matrix:

['omega_b', 'omega_cdm', '100*theta_s', 'w0_fld', 'alpha', 'beta', 'M', 'Delta_M']
[[7.84e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 2.56e-06 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 9.00e-08 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 2.50e-03 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-06 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 4.00e-04 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05]]
Update routine is enabled with value 50 (recommended: 50)
This number is rescaled by cycle length 8 (N_slow + f_fast * N_fast) to 400

#  -LogLkl	1e+02omega_b    omega_cdm       100*theta_s     w0_fld          alpha           beta            M               Delta_M         H0              Omega_m         Omega0_fld      
Segmentation fault (core dumped)
```




Best
PhyPy-Dm

**Comment by shan1525** [comment]
Hi @PhyPy-Dm , 
You have to delete the ouput folder complete, and make a new run because it running the old log.param file. See this
 python montepython/MontePython.py run -o lcdm/cmbsn -p input/cmbsn.param --conf my.conf -N 20
 /!\ Appending to an existing folder: using the log.param instead 

And also check this issue #212  carefully. Because you have to set the boundaries for the w's. 

Hope this helps, 
Best Shan.

**Comment by PhyPy-Dm** [comment]
Hi@shan1525
I check the issue #212 and modify cmbsn.param: `data.parameters['w0_fld']      = [  -1.,   -3., -0.3334, 0.2, 1, 'cosmo']  data.parameters['w0wa']        = [  -1.,   -4.,  0.,     0.2, 1, 'cosmo'] `, 
but it doesn't work.
errors raised

```
python montepython/MontePython.py run -o lcdm/cmbsn -p input/cmbsn.param --conf my.conf -N 20
Running Monte Python v3.4.0

with CLASS v3.0.1

Testing likelihoods for:
 ->JLA

Creating lcdm/cmbsn/2021-05-31_20__1.txt


Deduced starting covariance matrix:

['omega_b', 'omega_cdm', '100*theta_s', 'w0_fld', 'w0wa', 'alpha', 'beta', 'M', 'Delta_M']
[[7.84e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 2.56e-06 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 9.00e-08 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 4.00e-02 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 4.00e-02 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.00e-06 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 4.00e-04 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.60e-05]]
Update routine is enabled with value 50 (recommended: 50)
This number is rescaled by cycle length 9 (N_slow + f_fast * N_fast) to 450

#  -LogLkl	1e+02omega_b    omega_cdm       100*theta_s     w0_fld          w0wa            alpha           beta            M               Delta_M         H0              Omega_m         Omega0_fld      
Segmentation fault (core dumped)
```

Best
PhyPy-Dm

**Comment by shan1525** [comment]
Hi @PhyPy-Dm , 

Check issue #124 and similar kind of issue related with segmentation faults, look through them, see if that helps or not. 
Best, 
Shan.

**Comment by PhyPy-Dm** [comment]
Hi @shan1525 
Thank you for your help. But there's no errors when running with planck likelihood, so it's not the same problem as #124.

Best
PhyPy-Dm

**Comment by PhyPy-Dm** [comment]
Hi @shan1525
When I delete the 'cosmo' parameters {'omega_b', '100*theta_s'} but keep 'w0_fld', the program can run with jla likelihood, no segmentation fault.

Best
PhyPy-Dm

**Comment by brinckmann** [comment]
This is very peculiar, I can't make sense of it. I sounds like a class issue, not a MontePython one. But I can tell you I've run w0+wa with Planck + Pantheon with class v3. It returned a few errors seemingly introduced in class v3, but over tens of thousands of steps (i.e. rarely) and never to start a run. You might want to check that you can run class directly with the same set of parameters that is causing the crashes and if you're still getting those issues to post them on the class page.

It's a long shot, but sometimes when I get inexplicable errors it has helped to create a new param file from scratch (or copying one of the example ones) as sometimes some odd formatting is introduced that isn't visible by eye. Sometimes I even type the lines by hand instead of copying. Since your run works without omega_b and omega_cdm (there's no reason for this, that I can tell), those are the suspicious lines and you could start by typing them out manually.

Best,
Thejs

**Comment by PhyPy-Dm** [comment]
Hi @brinckmann

Thank you for your response and advice.

Best
PhyPy-Dm
