### ISSUE TITLE
timings of the Boltzmann call 

### ISSUE THREAD

**Issue by lukashergt** [brinckmann/montepython_public#22]
Hi,

we are currently testing out the PolyChord extension for MontePython. Trying that we stumbled over the timings MontePython takes for the theory calculation, i.e. for the call to `cosmo.compute()` in `sampler.py`. We have compared the timing to single Class/Camb calls and to CosmoMC and the `cosmo.compute()` call by MontePython seems to take about 2 times longer.

Is this expected or must there be something wrong in our setup?

We ran with the input from `base2015.param` with the three Planck likelihoods for high-l, low-l, and lensing. Below you can find the timings we have measured:

--------------------------------------------------
### timings for MontePython:

Time for `cosmo.compute`:  **6.8 s**
Time for Planck_highl:   0.008 s
Time for Planck_lowl:    0.09 s
Time for Planck_lensing: 0.007 s

--------------------------------------------------
### timings for CosmoMC (action 4):

Time for PPS:      2.861022949218750E-006
Time for theory:   2.83309

Time for lowl_SMW_70_dx11d_2014_10_03_v5c_Ap: 9.755587577819824E-002
Time for smica_g30_ftl_full_pp: 4.398822784423828E-004
Time for plik_dx11dr2_HM_v18_TT: 5.431890487670898E-003

Likelihood calculation time (seconds)= 2.9676

--------------------------------------------------
### timings for Class/classy:

Time for `explanatory.ini`: 3.6 s
Time for `cosmo.compute()`: 3.7 s
Time for `cosmo.lensed_cl`: 5 ms

--------------------------------------------------
### timings for pycamb:

Time for `camb.get_results(pars)`: 3.7 s
Time for `results.get_lensed_scalar_cls`: 0.5 ms

--------------------------------------------------

using:
Python      version 2.7.10
MontePython version 3.0.1
classy      version 2.7.0
pycamb      version 0.1.8.1

Many thanks,
Lukas

**Comment by lukashergt** [comment]
Thanks for the quick response, Thejs.

The difference between MontePython and Class seems to be indeed down to mPk and neutrinos. I was surprised to see that the neutrinos make such a difference, since CAMB uses 1 massive neutrino by default, but had similar timings. But maybe that's down to default accuracy settings.

I'm still a bit puzzled that CosmoMC should be so much faster than MontePython (both running with Planck likelihood plc-2.0 and both with neutrinos). I'm not 100% sure what exactly the likelihood calculation time of the `action=4` option in CosmoMC refers to, though.

**Comment by brinckmann** [comment]
I am not sure what settings you are using for CosmoMC, but it is likely due to you asking for the matter power spectrum to be computed when running with the MontePython example file 'base2015.param', but not asking for that when running with CosmoMC. You should disable that if you don't need it and only ask for tCl, pCl, lCl. It's a pity the example param file includes mPk when it's not needed.

Best,
Thejs
