### ISSUE TITLE
Prior

### ISSUE THREAD

**Issue by SafaeCosmology** [brinckmann/montepython_public#228]
hello all,
I have added a new fluid characterized by a new equation of state parameter in CLASS everything works fine, this parameter has a prior of [0, 0.04], but MontePython appears to be sampling the region new_parameter> 0.04 and notably that CLASS does not accept values greater than 0.04 for this parameter, especially at perturbation level.
The line I used in my input file is :
data.parameters ['new_parameter'] = [0.02, 0,0.04, 0.01,1, 'cosmo']

Montepython does not take into account the range mentioned in the input file ?

**Comment by brinckmann** [comment]
It should take that range into account and reject values outside the range before passing the cosmology to CLASS. The only thing I can spot is that the second value is an integer rather than a float and maybe that's causing problems? Can you try with 0.0 instead?

Best,
Thejs

**Comment by dchooper** [comment]
Hi Safae,

One thing that jumps out to me is your sigma value: you are taking a sigma of only 0.01 in the range [0, 0.04], so you're not really letting it take many steps before it hits the boundaries. Perhaps try decreasing your sigma and see if you still have the same problem.

Best,
Deanna

**Comment by SafaeCosmology** [comment]
thank you so much @brinckmann and @dchooper for your answers.
That's exactly what I did, I used the interval suggested by @brinckmann and reduced the sigma to 0.0001, and I get good results for this parameter (best fit, mean value, 1sigma), but for the 1D plot, I don't get a Gaussian. 
Maybe I will decrease the sigma again ?
![NEW_para](https://user-images.githubusercontent.com/78495903/125820874-9893fbf7-69ab-4f0a-ace4-5c8b2a490b28.png)

**Comment by brinckmann** [comment]
If your prior range is [0.0, 0.05] that just looks to me like your parameter is hitting the prior boundary on both sides, changing the sigma shouldn't change that. Is that unexpected behavior? Why were you expecting a Gaussian?

Also, by default MontePython uses aggressive smoothing for the 1d posterior, you might want to try to turn that off by setting
`info.posterior_smoothing = 0`
in a plot file passed with `--extra your_plot_file.plot` . See e.g. the example plotting file `plot_files/example.plot` for more information. Alternatively, it can be passed as a flag `--posterior-smoothing 0` .

Best,
Thejs
