### ISSUE TITLE
constrain S_8 as a derived parameter in montepython

### ISSUE THREAD

**Issue by mahtaparsa** [brinckmann/montepython_public#229]
How can one constrain S_8(=sigma_8*sqrt(omega_m/0.3) as a derived parameter in the MCMC run?
Should it be defined in the CLASS code, or in montepython code?
Thanks.

**Comment by brinckmann** [comment]
You can add S8 during analysis if you have sigma8, please see the example plot file on how to add new parameters. You may need to define Omega_m first in a similar way first, if you don't have it as a derived parameter.

Best,
Thejs

**Comment by mahtaparsa** [comment]
Thanks a lot.
