### ISSUE TITLE
Lyman Alpha constraints

### ISSUE THREAD

**Issue by aghalsas** [brinckmann/montepython_public#230]
Hi,

Can someone explain how the Lyman-alpha constraints are implemented in Monte Python? Is it taking the lyman alpha data and somehow comparing it to the linear power spectrum?

Thanks,
Akshay

**Comment by brinckmann** [comment]
You can generally look for more information in the .data file in the likelihood subdirectory, but if it's not there try the __init__.py file as some older likelihoods have the information there. The likelihood subdirectories are in montepython/likelihoods/ .

E.g. this file describes the Lya_abg likelihood with references to relevant papers, which you'll probably have to go over to understand the approach:
https://github.com/brinckmann/montepython_public/blob/3.4/montepython/likelihoods/Lya_abg/Lya_abg.data

There are also BOSS Lya BAO likelihoods, which are the ones including BOSS and Lya in the name. 

Best,
Thejs
