### ISSUE TITLE
setting priors on w0-wa

### ISSUE THREAD

**Issue by am610** [brinckmann/montepython_public#233]
Computing w0-wa,  we use w0+wa, w0 in the param file and then do transformation to obtain the w0, wa constraints. 

My question is, I need to add priors on w0, wa how can I implement them ? I have a omega_m, w0, wa  prior covariance matrix, how do i apply it ?

**Comment by brinckmann** [comment]
Hi,
If the covariance matrix has the correct format for MontePython then you can pass it with -c your_file.covmat .
Regarding the prior on w0, it depends on what type of prior. If you want to add a top hat prior, e.g. rejecting very high or very low values, you would simply add it has prior bounds when defining your parameter in the param file, e.g.
data.parameters['w0_fld']          = [  -1, -3, -0.334,     0.1,    1, 'cosmo']
where -3 is the lower bound and -0.334 is the upper bound.

If your prior has a different shape (e.g. Gaussian) you will probably need to a a likelihood that adds it, see e.g. montepython/likelihoods/hst/ for an example of a Gaussian prior on H0. See [my MontePython slides](https://lesgourg.github.io/class-tour/Cambridge/180912_MontePython_Cambridge.pdf) from a couple of years ago for how to add a new likelihood (slide 35-39 for how to add a new likelihoods, but 30-34 for MontePython communication with class might also be useful).

Best,
Thejs
