### ISSUE TITLE
Sterile neutrinos

### ISSUE THREAD

**Issue by SafaeCosmology** [brinckmann/montepython_public#237]
Hello everyone, I hope you are well ..
I have a question please,
indeed I am working on the cosmological constraints of the properties of neutrinos on phantom dark energy, in particular on sterile neutrinos.
I want to calculate the ΔNeff = Neff - 3.044 and the  mass of the sterile neutrino m_s_eff.
1st test: I varied the Neff and m_ncdm and I put the deg_ncdm = 1, but I get a small value of Neff <3.044.
2nd test:  I varied Neff and m_s_eff but when I fixed deg_ncdm__2, I get the following error `` deg_ncdm__2 is not read by class '', I adopted on #160 I get the same error.
please if someone can help me or give me an example.
thanks in advance.

**Comment by brinckmann** [comment]
You'll need to precisely specify what is in your param file, otherwise I can only guess. If you followed the rest of the instructions in the other issue then my guess is you didn't set
`cosmo_arguments['N_ncdm'] = 2`
but it's hard for me to say. If you follow the instructions in the last comment by me and have a setup similar to the second to last comment by Ravi that should be all you need.

Best,
Thejs

**Comment by SafaeCosmology** [comment]
Thank you very much for your answers.
I'm currently testing the standard model ''Lambda_CDM'' with three massless neutrinos and one massive neutrino that can be considered a sterile neutrino for this reason. I set **N_ncdm = 1** . plus I varied **Neff**: the effective number of relativistic neutrinos ,  **m_ncdm**: the effective mass of sterile neutrinos and **deg_ncdm** :  the number of sterile neutrinos .  my file.parm  is written as follows:


_data.experiments=['Planck_highl_TTTEEE_lite','Planck_lowl_EE','Planck_lowl_TT','Pantheon','sh0es','bao_boss_dr12']
# Cosmological parameters list
data.parameters['omega_b']   = [0.0225,   0.005, 0.1, 0.0001, 1,'cosmo']
data.parameters['omega_cdm'] = [0.118, 0.001, 0.99, 0.001,1,   'cosmo']
data.parameters['ln10^{10}A_s'] = [ 3.040896,   None, None, 0.0029,    1, 'cosmo']
data.parameters['H0']        = [69,   None, None, 1.2,       1,   'cosmo']
**data.parameters['deg_ncdm'] = [1,  0, None, 0.001, 1, 'cosmo']
data.parameters['m_ncdm'] = [1, 0, 10, 0.001, 1, 'cosmo']
data.parameters['N_eff'] = [3.046,0, 10, 0.01, 1, 'cosmo']**
# Nuisance parameters list
data.parameters['A_planck']          = [99.96745,   90,  110,  0.25,  0.01,'nuisance']  
data.parameters['M']       =  [-19.37840, None, None, 0.004,  1, 'nuisance']_
# Derived parameter list
data.parameters['Omega_m']         = [0,   -1,   -1, 0,     1,   'derived']
data.parameters['sigma8']          = [0, None, None, 0,     1,   'derived']
# Other cosmo parameters (fixed parameters, precision parameters, etc.)
**data.cosmo_arguments['N_ncdm'] = 1**

**Please correct me if there is an error.**

**Comment by brinckmann** [comment]
Does running with N_eff as a cosmological parameter work? I've never tried and I"m not sure what it would do, if it just fills up the rest of the states after the ncdm species with ultra-relativistic species N_ur.

In any case, I'm not sure your set up will map onto sterile neutrinos, it looks more like a normal hierarchy approximation with 1 massive 2 massless active neutrinos, with a varying N_eff.

Best,
Thejs

**Comment by SafaeCosmology** [comment]
Thank you  for your answers. 
I wanted to work with a phantom dark energy model with **_3 massless neutrinos_** and **_one massive neutrino (sterile)_** **_neutrino_** and I wanted to vary the effective number of relativistic neutrinos  **_N_eff_**  and the effective mass of sterile neutrino **_m_s_eff_**  which is normally equal to  **_m_ncdm_**   because  **_deg_ncdm = 1_** .
I don't know if this is true.
