### ISSUE TITLE
Cannot use clik wrapper

### ISSUE THREAD

**Issue by ritase7e** [brinckmann/montepython_public#239]
Hello everyone,

I am trying to run Monte Python with the planck 2018 likelihoods and I'm getting an error both on my laptop and on the cluster:

Running Monte Python v3.4.0

with CLASS v3.0.2
 /!\ Detecting empty folder, logging the parameter file

Testing likelihoods for:
 ->Planck_highl_TTTEEE, Planck_lowl_EE, Planck_lowl_TT

Cannot use clik wrapper (cause = '/home/rneves/software/planck/code/plc_3.0/plc-3.01/lib/python/site-packages/clik/lkl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct')
Cannot use clik_lensing wrapper (cause = '/home/rneves/software/planck/code/plc_3.0/plc-3.01/lib/python/site-packages/clik/lkl_lensing.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct')
Traceback (most recent call last):
  File "/home/rneves/software/montepython_public/montepython/likelihood_class.py", line 892, in __init__
    self.clik = clik.clik(self.path_clik)
AttributeError: module 'clik' has no attribute 'clik'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/rneves/software/montepython_public/montepython/run.py", line 32, in run
    custom_command)
  File "/home/rneves/software/montepython_public/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/rneves/software/montepython_public/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
  File "/home/rneves/software/montepython_public/montepython/data.py", line 356, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/rneves/software/montepython_public/montepython/data.py", line 493, in initialise_likelihoods
    elem, elem, folder, elem))
  File "<string>", line 1, in <module>
  File "/home/rneves/software/montepython_public/montepython/likelihood_class.py", line 894, in __init__
    except clik.lkl.CError:
AttributeError: module 'clik' has no attribute 'lkl'

I have checked that I sourced the planck likelihoods with the correct path, the 'clik' path in the .conf file is correct too. I also checked any warnings that came up during the ./waf configure in the planck part of the readme, and installed anything that was not found, even though at the end it says it is ok to proceed with install.

After searching any related issues here I also did a new install of cfitsio and pointed to it when doing ./waf configure, and I tried installing cfitsio3.49 instead of 4.00 as it seemed to work for someone else.

From another issue someone suggested to run clik_print to check if it might be an issue with the plik code itself independently from MP, and I get this message (both in the cluster and my laptop):

Cannot use clik wrapper (cause = '/home/rneves/software/planck/code/plc_3.0/plc-3.01/lib/python/site-packages/clik/lkl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct')
Cannot use clik_lensing wrapper (cause = '/home/rneves/software/planck/code/plc_3.0/plc-3.01/lib/python/site-packages/clik/lkl_lensing.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct')
usage : %s lkl_file

So is this an issue with the plik code?

Any help would be appreciated.

Thanks in advance,
Rita

**Comment by dchooper** [comment]
Hi,

This issue usually happens when you compile clik with python2 and then try to call it with python3. To test if this is the case, try calling clik with python 2. If it works, I would then propose to reinstall clik using python 3.

Best,
Deanna

**Comment by ritase7e** [comment]
Hi,
Thank you for the quick answer. I get the same error with python 2. I'm pretty sure I have installed everything with python 3.
Rita
