### ISSUE TITLE
Speeding up Convergence w0-wa run

### ISSUE THREAD

**Issue by am610** [brinckmann/montepython_public#245]
I ran the code for estimating dark energy w0, wa  but after 9 days of running, w0, wa are still showing R-1 value ~ 0.85, 2.9. I am wondering what would be the strategy to make them converge quicker ? 

Since I am running on NERSC, so I have a cap of 48 straight hours run time in a single go, as a result I restart my run post the 2 day window, the following strategies I used 

Initial run : 

`python montepython/MontePython.py run -p input/simple_prior_SNANA_DE.param -o output/SNANA_plasticc_zcheat%d   -N 80000"%(mpi_rank) `

Restart runs : 

`python montepython/MontePython.py run -p input/simple_prior_SNANA_DE.param -o output/SNANA_plasticc_zcheat%d  -N 80000 --superupdate 20 --update 50 -f 2.4 -r output/SNANA_plasticc_zcheat%d/2021-11-05_320000__*.txt"%(mpi_rank,mpi_rank)`

Comments : I used `f 2.4` because some threads here mentioned this could be a try to see if convergence could be faster. Perhaps I could also use covariance matrix as an input ? 

screen outputs during info run : 

`
R-1 is 
          0.079272 	for  omega_b

           0.285636 	for  omega_cdm
           0.800651 	for  $w_0$
           2.724697 	for  $w_a$
           0.392826 	for  M
           0.064424 	for  A_planck
           0.064424 	for  H0
           0.245977 	for  Omega_m
           0.245977 	for  Omega0_fld
`

Current estimations would look like 
![Screenshot 2021-11-10 at 11 13 07 AM](https://user-images.githubusercontent.com/6508278/141054046-b25170d8-02b4-41da-a474-8b99d75df03a.png)

My param file looks like 

`data.experiments=['Planck_highl_TT_lite', 'Planck_lowl_TT','Planck_lowl_EE','Planck_lowl_BB','SNANA','Om'] 

data.parameters['omega_b'] = [ 2.2253, None, None, 0.028, 0.01, 'cosmo'] 
data.parameters['omega_cdm'] = [ 0.1120, None, None, 0.0016, 1, 'cosmo']
data.parameters['w0_fld'] = [ -0.995,-3.5, -1, 0.001, 1, 'cosmo']
data.parameters['w0wa'] = [ -1, -3.5,-1, 0.001, 1, 'cosmo']
data.parameters['M']        = [-19.02, None, None, 0.004,  1, 'nuisance']
data.parameters['A_planck'] = [100.028,   90,  110,  0.25,  0.01,'nuisance']
data.parameters['H0'] = [0, None, None, 0, 1, 'derived']
data.parameters['Omega_m'] = [0, None, None, 0, 1, 'derived']
data.parameters['Omega0_fld'] = [0, None, None, 0, 1, 'derived']
data.cosmo_arguments['N_ur'] = 2.0328
data.cosmo_arguments['N_ncdm'] = 1
data.cosmo_arguments['m_ncdm'] = 0.06
data.cosmo_arguments['T_ncdm'] = 0.71611
data.cosmo_arguments['Omega_Lambda'] = 0
data.cosmo_arguments['Omega_k'] = 0.
`

**Comment by brinckmann** [comment]
It looks like you start your run with MultiNest (-m NS) and then continue with Metropolis-Hastings. This is definitely not recommended and you should pick one method and stick with it.

Best,
Thejs

**Comment by am610** [comment]
Ahh, big apology, I pasted the wrong line, now corrected. So yeah definitely not using the NS input, that was a commented line in the original script. Please have a look into it now
