### ISSUE TITLE
order of experiments with Planck and LSS data

### ISSUE THREAD

**Issue by Antara-Dey** [brinckmann/montepython_public#248]
Dear all,
I am trying to use montepython_public-3.4 version with Planck, WiggleZ, bao_boss, sdss_lrgDR7 data, what would be the order of experiments in 'data.experiments=[]' of input parameter file. Thanks in advance.

**Comment by brinckmann** [comment]
The conventional wisdom is to put the slowest likelihoods first, I would put the Planck likelihoods, followed by LSS, and then BAO last. Also note if any likelihoods share nuisance parameters then they should be next to each other. Finally, you might want to think about whether you're double counting information with that combination of LSS and BAO data.

Best,
Thejs
