### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by wilmarcardonac** [brinckmann/montepython_public#25]
Dear Developers, 
I cannot find the pdf documentation mentioned in the description. Moreover, some of the things mentioned do not correspond to the current version of the code (e.g., Planck likelihood, etc). 
Best,

**Comment by brinckmann** [comment]
Hi,

I apologize, I thought I had answered as I actually looked into this and updated the description for the upcoming v3.1 of MontePython to be more informative. I agree the "pdf documentation" is misleading. My guess is there was previously an independent pdf documentation (and indeed there are pdf tutorials), whereas now the only pdf documentation available is a pdf version of readthedocs, which doesn't provide any additional information and is indeed not updated for MontePython 3, for which I also apologize.

In the meantime please consult the help files of the code, which I try to keep detailed and updated. If something is unclear after consulting the help files, the (unfortunately a bit outdated) documentation, and the tutorials on the [course page of the website of Julien Lesgourgues](https://lesgourg.github.io/courses.html) you are always very welcome to ask questions on here.

Best,
Thejs
