### ISSUE TITLE
Tensor to scalar ratio(r) as 'Derived parameter'.

### ISSUE THREAD

**Issue by shan1525** [brinckmann/montepython_public#254]
Hi everyone,
I hope everyone is safe. I wanted to asked  when I am setting r(tensor to scalar ratio) as a cosmological parameter , suggested in #33. It is working. But when I am trying to add it as a derived parameter with analytic_pk method. It is giving me a constant value 1 in my all chains. All the other parameters are varying but it is giving a fixed value. I am attaching the param file as below. Please , reply if you have a suggestion. I am checking it with the base lcdm model. 
[test_r_derived.txt](https://github.com/brinckmann/montepython_public/files/7780238/test_r_derived.txt)
Thanks in advance,
Shan.

**Comment by dchooper** [comment]
For future reference: this was related to a bug in CLASS where r was fixed to 1 when using analytic_pk method.
