### ISSUE TITLE
IndexError for 'external_Pk' and 'analytic_Pk'

### ISSUE THREAD

**Issue by tanmoyyy** [brinckmann/montepython_public#257]
Dear All,

Recently I tried to analyze chains generated with 'external_Pk' and faced some problems for the 'custom' cosmo parameters. The same problem appears for chains generated with 'analytic_Pk' with 'cosmo' parameters A_s, n_s, alpha_s. I get following error when executing '../montepython_public/montepython/MontePython.py info ../montepython_public/extpk/chains/'

Traceback (most recent call last):
  File "../montepython_public/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "../montepython_public/montepython/run.py", line 32, in run
    custom_command)
  File "../montepython_public/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "../montepython_public/montepython/initialise.py", line 59, in initialise
    analyze(command_line)
  File "../montepython_public/montepython/analyze.py", line 151, in analyze
    enumerate(info.chain[info.sorted_indices[0], 2:])]
  File "../montepython_public/montepython/analyze.py", line 150, in <listcomp>
    bestfit_line = [elem*info.scales[i, i] for i, elem in
IndexError: index 4 is out of bounds for axis 0 with size 4

I checked the generated chains and found that 'custom' parameters are sampled properly for 'external_Pk' (and for A_s, n_s, alpha_s for 'analytic_Pk') and plots look fine in GetDist for both cases. Perhaps making a very trivial error but a bit confused since everything works perfectly fine for 'P_k_ini type' = 'inflation_H' with the same setup (MontePython 3.5 and Class  3.1.1). . Thank you in advance.

**Comment by brinckmann** [comment]
Hi,

I'm a bit stumped, especially because you mention you did a previous run with the same setup (except external_Pk, which I'd think shouldn't matter). Was it identical, i.e. the same custom parameters? Sometimes MontePython can act up if the parameter names interfere with analyzing the chains, in those cases they can be changed with a plot file passed with `--extra your_plot_file` , see plot_files/example.plot for information. It might also be an error when writing the data to the files during the run, but then I'm surprised it works for GetDist.

Issue #227 looks like it might be related. @am610 Ayan, can you tell us if you found out what the problem was?

Best,
Thejs

**Comment by tanmoyyy** [comment]
Dear Thejs

It did not work for 'external_Pk' and 'analytic_Pk' at all. Sorry for the confusion. I meant "same setup" as in the versions of MontePython and Class were same when I analyzed for parameters in 'inflation_H' mode. For 'inflation_H' everything works fine. As far as I can see all  parameters are sampled properly for 'external_Pk'  and 'analytic_Pk' as well. Anything I try with 'info'  returns the error.  One thing to point out though. I generated chains with mpirun.  

Regards,
Tanmoy

**Comment by tanmoyyy** [comment]
Hi Thejs,

Figured out the source of this error. The problem was in the 'log.param'. I had a commented out part in the input param file which sampled the parameters properly. But the same line in  'log.param' returned the error while analyzing.
E.g. I had a line like this in my input param file: 
"data.parameters['custom3']          = [  0.9625,   None, None,      0.0005,    1, 'cosmo']         #n_s"   

Once I removed the '#n_s' from that line in the 'log.param' (or from the input param file before sampling) everything worked fine.

Best,
Tanmoy

**Comment by brinckmann** [comment]
Thanks for reporting back! I really need to add a note to the example param files reminding users not to do that, as it's a common problem that users have no way of knowing unless they encountered it before and it's hard to debug unless the param file is copied in the issues report (which is a good idea to do).

Best,
Thejs
