### ISSUE TITLE
Bug when using mock CMB likelihoods with BB spectrum

### ISSUE THREAD

**Issue by brinckmann** [brinckmann/montepython_public#267]
Tanmoy in issue #266 raised the point that there's a couple of problems in montepython/likelihood_class.py when trying to use mock CMB likelihoods with BB spectrum:
Line 1454 and 1463 `self.lmax` should be `self.l_max` .
Line 1455 and 1464 `cl[l]['bb']=cl_unlensed[l]['bb']` should be `cl['bb'][l]=cl_unlensed['bb'][l]`

**Comment by dchooper** [comment]
I have implemented this bugfix, it will be included in MP v3.6.0 (coming soon!). Thanks for pointing it out!
