### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by gmfricke** [brinckmann/montepython_public#269]
As far as I know there is no numpy 1.4.1, it's only up to 1.2.x. The readme tells people to use at least that version. Did you mean pandas 1.4.1?

All the best,

Matthew

**Comment by brinckmann** [comment]
I'm confused, isn't the most recent numpy version 1.22.1? 1.4.1 would be a _very_ old version.

Best,
Thejs

**Comment by gmfricke** [comment]
Ha! Yes you are exactly right. Thanks for catching my error.
