### ISSUE TITLE
Add H0 contour

### ISSUE THREAD

**Issue by SandiCosmo** [brinckmann/montepython_public#270]
Hello, i tried to add a band showing the most recent measurements of H0 in my contours, I activated this line:
**_info.custom2d = ['add_h_contour.py']_**
in my file **_example.plot_**
then I executed **_info_** with the flag **_--extra ......../example.plot_**
but I don't get the band of H0 in my figure.

**Comment by brinckmann** [comment]
1) check that you have the parameter "H_0" in your plots, either by being present _with that exact name_ in the param file or by renaming e.g. "h" or "H0" using the plot file to "H_0" (adjusting value if h, again using the plot file). Alternatively, change the parameter in `add_h_contour.py` .

2) check that the range of the H_0 contours (74.03 +/- 2 x 1.42 by default, but the value can be changed in `add_h_contour.py`) are within the plotting range for "H_0" and adjust plotting range with the plot file if not and you want the band to be visible.

Best,
Thejs

**Comment by SandiCosmo** [comment]
Thank you very much for your answer,  yes I did the same steps you mentioned but unfortunately I get nothing.
