### ISSUE TITLE
Planck lite likelihood not loading correctly

### ISSUE THREAD

**Issue by ash2223** [brinckmann/montepython_public#272]
Hello,

I'm attempting to run chains on the Planck 2018 TTTEEE lite likelihood, but when I start the run I get this error:

<img width="1280" alt="Screen Shot 2022-04-06 at 9 34 57 AM" src="https://user-images.githubusercontent.com/61329093/162809662-a9287585-1a5d-4424-9ddf-4f56fa388862.png">

The batch script I'm submitting looks like this:

```
#!/bin/bash                                                                                                                                                                          
#SBATCH --nodes=1                                                                                                                                                                    
#SBATCH --ntasks-per-node=2                                                                                                                                                          
#SBATCH --cpus-per-task=8                                                                                                                                                            
#SBATCH --mem=6GB                                                                                                                                                                    
#SBATCH --time=48:00:00                                                                                                                                                              

module purge

eval "$(conda shell.bash hook)"

conda activate test

source /home1/adamhe/code/plc_3.0/plc-3.1/bin/clik_profile.sh

mpirun -np 2 python3 montepython/MontePython.py run -o test -p input/base2018TTTEEE_lite.param -N 20000 --update 50 --superupdate 20
```

Help would be much appreciated!

Thanks,
Adam

**Comment by brinckmann** [comment]
Hi Adam,

Sorry for the very late reply, but it looks like an issue with your Planck installation. I can't really recommend anything other than simply reinstalling Planck from scratch, frustrating as that is. It seems something went wrong the first time.

Best,
Thejs

**Comment by ash2223** [comment]
No worries! I tried reinstalling multiple times, to no avail :( but thanks for the advice! Hopefully the issue will resolve in the future.

Thanks,
Adam

**Comment by dchooper** [comment]
Hi Adam,

To me this looks like a problem with the fortran compiler you are using to compile the Planck likelihoods. I would recommend updating your fortran compiler, and then reinstalling the Planck likelihoods from scratch. If you are running on a cluster, perhaps  your local cluster IT support can help. 

Unfortunately as it's not a MontePython error, there's not much else we can do about it.

Cheers,
Deanna

**Comment by ash2223** [comment]
Ah, okay! I'm running on a cluster, so I'll consult my IT about this. Thanks so much Deanna!

-Adam
