### ISSUE TITLE
Planck SZ data

### ISSUE THREAD

**Issue by MarkLinton** [brinckmann/montepython_public#274]
Hi, 
I was wondering if someone could point me to a reference for the Planck SZ data (in montepython_public/montepython/likelihoods/Planck_SZ/Planck_SZ.data).
Thanks.

**Comment by brinckmann** [comment]
Hi Mark,

I believe the reference is the Planck 2013 SZ cluster counts analysis: https://arxiv.org/abs/1303.5080
But I cannot recommend using this likelihood as-is. Not only is there a newer 2015 result (it was not repeated for 2018), but the number quoted is for an analysis that fixed the hydrostatic mass bias to derive this constraint, which is not a good choice. At the very least you'll want to use a result where they marginalized over the hydrostatic mass bias in the analysis - but you're still missing correlations between the hydrostatic mass bias and any new cosmological parameters you might introduce, which may be non-negligible for some models.

At this end of this month, Boris Bolliet and I will make public a full Planck SZ cluster counts likelihood from https://arxiv.org/abs/1906.10359 , where you can marginalize over the hydrostatic mass bias. We'll also make public a Planck thermal SZ power spectrum likelihood.

Best,
Thejs

**Comment by MarkLinton** [comment]
Ok thanks.
And thanks for getting back to me so quickly!
Mark
