### ISSUE TITLE
BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES, KILLED BY SIGNAL: 11

### ISSUE THREAD

**Issue by Jimmy022** [brinckmann/montepython_public#286]
Hi, 

Recently I'm using Montepython + Class to run some mcmc projects. But I always met a BAD TERMINATION like this:

=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 25766 RUNNING AT node03
=   KILLED BY SIGNAL: 11 (Segmentation fault)

I'm using fake likelihood for CMB. Using different computing machines and different models (such as add massive neutrinos, add B mode and constrain r in the input file, etc.) will encounter this problem in the calculation for the same (actually the program runs smoothly for a short time before BAD TERMINATION). I wonder what reason might it be causing this problem, please help me solve this.

Best wishes,
Jimmy

**Comment by dchooper** [comment]
Hi,

There really isn't enough information here to debug this. What parameter file are you running? What class and MontePython versions are you using? Are you running with Nested Sampling or Metropolis Hastings? 

In general, seg faults do not come from MontePython, these are either caused by CLASS, MultiNest, or the Planck likelihoods. 

Cheers,
Deanna

**Comment by Amlan1996** [comment]
Hi @dchooper ,

I also need help with this kind of problem. I am using the class version 3.2.0 and montepython version 3.5.0. I have modified the class to a new dark energy model where two of the 'scf_parameters' are my model parameters in addition to the lambda CDM parameters. I have been running the montepython code in the default metropolis hasting method repeatedly with a new covmat and bestfit file from the previous run. The code ran up to 2 successive runs very smoothly, but after that, when I tried to run the chain files stopped producing any output after a certain amount of time, and I was not getting enough accepted points to analyze the chains properly. The error file is not showing any error; instead, the '.out' file shows this error 'Bad termination ....." 

So it would be great if you could help me out with this.     

Best,
Amlan
