### ISSUE TITLE
Precision settings

### ISSUE THREAD

**Issue by stefanmarinus** [brinckmann/montepython_public#297]
Can precision settings as e.g. "perturb_integration_stepsize" be changed within the .ini file?
Where can the standard internal precision settings of montepython be found?

**Comment by brinckmann** [comment]
Hi Stefan,

Any parameter in CLASS can be passed as a cosmo argument in the param file, e..g in this case
`data.cosmo_argumeents['perturbations_integration_stepsize'] = 0.5`

I'm not sure what you mean by standard internal precision settings of montepython? Do you mean the CLASS precision settings? The default values are set in CLASS in `your_class_directory/include/precisions.h` not in MontePython, but can be changed from MontePython in the aforementioned way, similar to how you can change them in an ini file.

Best,
Thejs
