### ISSUE TITLE
Wrong function call in prior.py

### ISSUE THREAD

**Issue by nraffuzz** [brinckmann/montepython_public#298]
At line [79](https://github.com/brinckmann/montepython_public/blob/4f010ad7ede7306ada811de80cad8369dbd6338f/montepython/prior.py#L79) of `montepython/prior.py` the function `calue_within_prior_range` has been called, instead of `value_within_prior_range`, defined a few lines below. 
I think this might be a typo, which should be corrected in my opinion.

**Comment by brinckmann** [comment]
Thank you, Nicolò, you're correct! It'll go in the pile of fixes for the next version!

Best,
Thejs
