### ISSUE TITLE
Question about Likelihood_mock_cmb(Likelihood)

### ISSUE THREAD

**Issue by raziel2646** [brinckmann/montepython_public#3]
Hi,

Could you please provide a source/paper for the likelihood used in `class Likelihood_mock_cmb(Likelihood)`. I cannot find an equivalent of the `det_mix` in Hamimeche & Lewis 2008. 

Thanks.

**Comment by brinckmann** [comment]
Hi,
I'm sure there's a better reference, but off the top of my head we explained the likelihood in the CORE-M5 papers, so have a look at those and references therein. Specifically, det_mix is given by equation 2.5 in the cosmological parameters paper.
Cosmological parameters paper: https://arxiv.org/abs/1612.00021
Inflation paper: https://arxiv.org/abs/1612.08270
Best,
Thejs

**Comment by raziel2646** [comment]
Thanks a lot! Unfortunately, the equation doesn't have a reference, but this is very helpful.

**Comment by brinckmann** [comment]
The references in the cosmological parameters paper point to Perotto et al. 2006, where the equations are introduced, where eq. 3.4 is det_mix. You can find the paper here:
https://arxiv.org/abs/astro-ph/0606227
Best,
Thejs

**Comment by raziel2646** [comment]
Thank you so much! This is perfect. 

I sincerely appreciate your help.
