### ISSUE TITLE
problem with Planck 2018 likelihood 

### ISSUE THREAD

**Issue by okamatu-fumiya** [brinckmann/montepython_public#306]
Hello everyone, 

I want to run montepython v3.5 with class_clumpy-main using Planck 2018 likelihoods.
I think that Planck2018 likelihoods have been successfully installed.
But, when I run montepython using Planck_high_TTTEEE etc, errors show the following.

clik version 3be036bbb4f9
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/sc/home/fumiya.okamatsu/plc-3.01/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Checking lensing likelihood '/sc/home/fumiya.okamatsu/plc-3.01/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8.clik_lensing' on test data. got -4.42102
free(): invalid pointer
free(): invalid pointer
free(): invalid pointer
free(): invalid pointer
srun: error: cn0133: task 3: Aborted (core dumped)
  -4.63e-05  1.92e-05  1.18e-05  7.80e-04  1.00e-06  2.08e-07 -1.91e-06 -2.20e-06 -4.76e-07  6.21e-06 -5.10e-06  1.00e-05  5.79e-06]]srun: error: cn0133: tasks 0-2: Aborted (core dumped)

I have reinstalled the Planck 2018 likelihood to solve this error, but it doesn't work well.

I want to resolve this error.
If anyone has any ideas, please let me know.

Best regards,
Fumiya

**Comment by dchooper** [comment]
Hi Fumiya,

We need to narrow down the source of the problem. Can you try running "clik_print" (in any directory), after sourcing the planck binary files, and let us know the output.

When you install the Planck likelihoods, are you sure it's pointing to the right compilers? (To check this, look out for any error messages or warnings when compiling them).

Deanna

**Comment by okamatu-fumiya** [comment]
Dear Deanna C. Hooper

Thank you for your reply.
I tried running "clip_print" and then the error shows the following:

Traceback (most recent call last):
  File "/sc/home/fumiya.okamatsu/plc-3.01/lib/python/site-packages/clik/miniparse.py", line 6, in <module>
    import pyfits as pf
ModuleNotFoundError: No module named 'pyfits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sc/home/fumiya.okamatsu/plc-3.01/bin/clik_print", line 6, in <module>
    import clik
  File "/sc/home/fumiya.okamatsu/plc-3.01/lib/python/site-packages/clik/__init__.py", line 25, in <module>
    from .miniparse import miniparse
  File "/sc/home/fumiya.okamatsu/plc-3.01/lib/python/site-packages/clik/miniparse.py", line 9, in <module>
    from astropy.io import fits as pf
ModuleNotFoundError: No module named 'astropy'

However, I have installed modules "astropy" and "pyrites".

Just be sure, when I tried ./waf configure --install_all_deps, I show the output:

Setting top to                           : /sc/home/fumiya.okamatsu/plc-3.01 
Setting out to                           : /sc/home/fumiya.okamatsu/plc-3.01/build 
Checking for program 'gcc, cc'           : /usr/bin/gcc 
Checking for program 'ar'                : /usr/bin/ar 
Check gcc version                        : 8.5.0 
Compile a test code with gcc             : yes 
Setting architecture flag to             : ['-m64'] 
Checking for program 'ifort'             : /sc/system/ap/intel/compilers_and_libraries_2020.4.304/linux/bin/intel64/ifort 
Checking for program 'xiar'              : /usr/bin/ar 
Checking for program 'ar'                : /usr/bin/ar 
Check ifort version                      : 19.1.3.304 
Compile a test code with ifort           : yes 
retrieve ifort link line                 : ok 
fortran link line                        : -L/sc/system/ap/intel/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin -L/sc/system/ap/intel/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin/ -L/lib -L/lib64 -lintlc -lifcoremt -liomp5 -lirc -lifport -limf -lsvml -lpthread 
Setting install root to                  : /sc/home/fumiya.okamatsu/plc-3.01 
Setting install bin directory to         : /sc/home/fumiya.okamatsu/plc-3.01/bin 
Setting install lib directory to         : /sc/home/fumiya.okamatsu/plc-3.01/lib 
Setting install include directory to     : /sc/home/fumiya.okamatsu/plc-3.01/include 
check compatibility of ifort and gcc versions : ok 
Checking for program 'python'                 : /home/uchu/fumiya.okamatsu/.conda/envs/fumiyaenv/bin/python 
Checking for python version                   : 3.6.9 
python-config                                 : /home/uchu/fumiya.okamatsu/.conda/envs/fumiyaenv/bin/python3.6-config 
Asking python-config for pyembed '--cflags --libs --ldflags --embed' flags : not found 
Asking python-config for pyembed '--cflags --libs --ldflags' flags         : yes 
Testing pyembed configuration                                              : yes 
Checking for library dl                                                    : yes 
checking for RTLD_DEFAULT in dl                                            : no 
compile with debug option                                                  : OFF 
Checking for program 'pmc-config'                                          : not found 
Checking for library pmc                                                   : not found 
Check mkl version                                                          : 10.3 
create specific mkl lib                                                    : /sc/home/fumiya.okamatsu/plc-3.01/lib/libclik_mkl.so 
Checking for library ['clik_mkl', 'iomp5', 'pthread', 'm']                 : yes 
checking for function 'dposv'                                              : yes 
checking for function 'dtrsv'                                              : yes 
checking for function 'dpotrf'                                             : yes 
checking for function 'dpotrs'                                             : yes 
checking for function 'dpotri'                                             : yes 
checking for function 'dtrtri'                                             : yes 
checking for function 'dtrmm'                                              : yes 
checking for function 'dtrmv'                                              : yes 
checking for function 'dgeqrf'                                             : yes 
checking for function 'dormqr'                                             : yes 
checking for function 'dsyev'                                              : yes 
checking for function 'dgesvd'                                             : yes 
checking for function 'dsymv'                                              : yes 
checking for function 'dgemv'                                              : yes 
checking for function 'dgemm'                                              : yes 
checking for function 'dsyrk'                                              : yes 
checking for function 'dsyr2k'                                             : yes 
checking for function 'daxpy'                                              : yes 
checking for function 'dtrsm'                                              : yes 
checking for function 'dsymm'                                              : yes 
checking for function 'dsyr'                                               : yes 
checking for function 'ddot'                                               : yes 
checking for function 'dsyevd'                                             : yes 
checking for function 'dlamch'                                             : yes 
checking for function 'dsyevr'                                             : yes 
Checking for library ['cfitsio']                                           : yes 
checking for function 'fits_init_cfitsio'                                  : yes 
Python version allows for automatic install                                : yes (3.6.9) 
Checking for program 'python'                                              : /home/uchu/fumiya.okamatsu/.conda/envs/fumiyaenv/bin/python 
Checking python module 'numpy'                                             : ok 
Checking python module 'astropy'                                           : ok 
Checking for program 'python'                                              : /home/uchu/fumiya.okamatsu/.conda/envs/fumiyaenv/bin/python 
Checking python module 'cython'                                            : ok 
Checking python module 'cython'                                            : ok 
Checking cython version (>0.20)                                            : 0.29.13 
Checking for program 'cython'                                              : /home/uchu/fumiya.okamatsu/.conda/envs/fumiyaenv/bin/cython 
Add plugin : 'rel2015'                                                     : ok 

*----------------------------------------------------*
|                                                    |
|   Configure step ok.                               |
|                                                    |
|   run './waf install' now !                        |
|                                                    |
*----------------------------------------------------*

'configure' finished successfully (8.401s)

If you have any ideas, please let me know.

Best regards,
Fumiya

**Comment by dchooper** [comment]
Hi Fumiya,

This looks to me like a conflict in python environments: the one that is called when you install the planck likelihoods seems to be a specific conda environment, and I imagine this is not the same python environment that is called when you opened the python terminal (or indeed when you run MontePython). 

You can type in your terminal `which python` to see where it is pointing: from the Planck installation scripts, it looks like you want to use `/home/uchu/fumiya.okamatsu/.conda/envs/fumiyaenv/bin/python`. If the `which python` is pointing somewhere else, then you need to force it find the right python path.

Cheers,
Deanna
