### ISSUE TITLE
How to include foreground model in a fake CMB likelihood?

### ISSUE THREAD

**Issue by Jimmy022** [brinckmann/montepython_public#307]
Hi all,

I would like to ask, if I want to add foreground parameters (such as "BB_dust") for the parameter constraints with a fake CMB likelihood, how should I set it? Thanks for any help！

Best wishes
Jimmy

**Comment by brinckmann** [comment]
Hi Jimmy,

Sorry for the slow reply. This is not a feature in the mock CMB likelihoods in MontePython and would have to be implemented, which might be a bit tricky as you probably would need to implement a dust template tied to the nuisance parameter. What people usually do when they want to include the effect of foregrounds is the include estimate of the effective foreground noise on the CMB spectra relevant to the experiment that they add to the detector white noise estimate. E.g. Simons Observatory did something along these lines for their forecast likelihood, if I remember correctly.

Best,
Thejs
