### ISSUE TITLE
Chains are not converging

### ISSUE THREAD

**Issue by RahulDhyani1103** [brinckmann/montepython_public#308]
I am running montypython (in 4 cores) using Planck_high_TTTEEE with eight parameters open . It's been more than 10 days but the plot hasn't converged yet. What could be the possible reason for this delay?

**Comment by dchooper** [comment]
Hi,

When you say 4 cores, do you mean you are running four chains, or are you running one chain on four cores? Ideally, you want to run multiple chains (e.g. 4-8) on several cores each (8-12) - the former is to speed up MontePython convergence, while the latter speeds up the cosmology part. 

When using Planck_high_TTTEEE you have order 30 nuisance parameters by default, plus your eight parameters - so you are actually fitting ~40 parameters. If you want to speed up the process, you can try running with Planck_lite, in which all the nuisance parameters (except one) are marginalised over beforehand. 

Hope this helps!
Deanna

**Comment by rahuldhyani11** [comment]
Thank you for your response, Yes I meant one chain on four cores. In total, I was running 6 chains on a total of 24 cores. I 
will try using Planck_lite.
