### ISSUE TITLE
Using gaussian prior with cosmological parameters

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#310]
Hello everyone, 

I am trying to reproduce an article with class and monte python. In the original work the authors use a gaussian prior on H0, which is a cosmological parameter in this particular case, however they don't use monte python and use the combo CAMB+ CosmoMC. I wonder if there is a way to apply gaussian prior for cosmological parameters in monte python as well, but can't find it anywhere. 

Thanks in advance, 

Dinorah

**Comment by lesgourg** [comment]
Dear @DinorahBarbosa , in MontePython, a gaussian prior on a parameter is equivalent to a gaussian likelihood. You can activate your gaussian prior on H0 by adding to the list of likelihoods one of 'hst' or 'sh0es'. If you look at the file associated to this likelihood, e.g. in montepython/likelihoods/sh0es/sh0es.data, you will see which central value and which standard deviation are used, and you can change them if you wish.
