### ISSUE TITLE
S_8 prior

### ISSUE THREAD

**Issue by SafaeCosmology** [brinckmann/montepython_public#324]
Dear All,
I wanted to add a prior on S8, the first step: I defined the S8 parameter in the **Montepython/data.py** file then I created a folder in MontePython/Likelihood/... as in the case of SH0ES, but when I run my MCMC I get the following error
**_'' S8 = cosmo.S8()
AttributeError: 'classy.Class' object has no attribute 'S8' ''_**
Can someone help me to solve this problem?
Thanks in advance,
Best regards.

**----------------------------------------------------------------------------------------------------------------**

![S8_data_py (1)](https://user-images.githubusercontent.com/78495903/233323731-58aff4e7-b7ee-4fef-8381-e1067ebdc46e.PNG)

**----------------------------------------------------------------------------------------------------------------**

![S8_init_py (1)](https://user-images.githubusercontent.com/78495903/233323758-0d330e91-c334-4184-8557-09b35ca52f94.PNG)

**Comment by brinckmann** [comment]
Hi Safae,

I can understand the confusion. data.py modifies cosmo_arguments on the MontePython side, which are passed to CLASS, while cosmo is the CLASS wrapper, i.e. what comes back from CLASS after it's called. So defining S8 in data.py gives you a way to sample S8 as a parameter and then pass omega_b, omega_cdm and sigma8 to CLASS, but it doesn't teach CLASS what S8 is, so S8 is still not available via cosmo. What you need to do is to define S8 based on sigma8 and Omega_m in your prior likelihood and then apply your prior as you do now. 

Best,
Thejs

**Comment by SafaeCosmology** [comment]
Dear Dr. Thejs Brinckmann,
Thank you very much for your answer.
I have made the following modifications 


**---------------------------------------------------------------------**

![1](https://user-images.githubusercontent.com/78495903/233511580-9efff38e-6d10-4bc2-9945-19782c724fe9.png)

**---------------------------------------------------------------------**

![2](https://user-images.githubusercontent.com/78495903/233511583-731bc116-48f9-4c4e-bbd1-c6a85de01af5.png)

**---------------------------------------------------------------------**

Please let me know if this is correct or not.
Best regards

**---------------------------------------------------------------------**

**Comment by brinckmann** [comment]
Hi Safae,

This is how I would have done it. Make sure your cosmo_arguments for P_k_max_h/Mpc or P_k_max_1/Mpc is large enough to accurately compute sigma8. I think about P_k_max_h/Mpc = 2.0 is enough.

Best,
Thejs

**Comment by SafaeCosmology** [comment]
Ok, thank you very much, sir.
