### ISSUE TITLE
MultiNest analyze issue--chains not created

### ISSUE THREAD

**Issue by ash2223** [brinckmann/montepython_public#327]
Hello!

I'm running into an issue when I try to analyze MultiNest output--instead of creating chains that can then be analyzed, MontePython gives this error:

![Screen Shot 2023-05-05 at 11 18 13 AM](https://user-images.githubusercontent.com/61329093/236537087-e9ba5c99-d5d6-47ce-a5b3-3e14bc731a84.png)

It seems this error has previously been [reported](https://github.com/brinckmann/montepython_public/issues/5)--the solution in this case was to remove the trailing dash, which is not working for me. I also tried solutions offered in [#125](https://github.com/brinckmann/montepython_public/issues/125), which didn't work either. Any input would be greatly appreciated!

Thanks,
Adam

**Comment by brinckmann** [comment]
Hi Adam,

Thank you very much for reporting the solution and I'm glad it's resolved!

Best,
Thejs
