### ISSUE TITLE
Problem running sample scripts. Error with class File(file)

### ISSUE THREAD

**Issue by zboero** [brinckmann/montepython_public#337]
Hi, I'm trying to use the code. 
After installation get the following error: 

Traceback (most recent call last):
  File "montepython/MontePython.py", line 12, in <module>
    import io_mp       # all the input/output mechanisms
  File "/user/codes_cosmo/MONTEPYTHON/montepython/io_mp.py", line 428, in <module>
    class File(file):
NameError: name 'file' is not defined

after trying to run:

python montepython/MontePython.py run -p input/lcdm.param -o chains/planck/lcdm -N 5

Appreciated for your help.

**Comment by dchooper** [comment]
Hi,

This seems to be a problem with using the wrong python version. What version of python and MontePython are you using? And what do you mean by "after installation"? Technically MontePython does not require any installation.

Cheers,
Deanna
