### ISSUE TITLE
Latex error in plotting

### ISSUE THREAD

**Issue by mohit93725** [brinckmann/montepython_public#34]
I am trying to use BK14 data to plot cosmological parameters. But instead I am getting an error

RuntimeError: latex was not able to process the following string:
'$BB\\\\alphadust$'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/home/mohit/.cache/matplotlib/tex.cache/4177339663be02fb03cef3e5448c3192.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.

Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

) (./4177339663be02fb03cef3e5448c3192.aux)
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Undefined control sequence.
l.13 ...000000}{20.000000}{\sffamily $BB\alphadust
                                                  $}
No pages of output.
Transcript written on 4177339663be02fb03cef3e5448c3192.log.

Please Help!!!

**Comment by brinckmann** [comment]
I'm sorry, this is a known error with some versions. Did you find a solution?
Best,
Thejs

**Comment by mohit93725** [comment]
Unfortunately I could not find any alternative. Please suggest me.
Thanks

**Comment by brinckmann** [comment]
It seems like pdflatex doesn't like the name of one of your parameters when MontePython does its automatic conversion to '$BB\\alphadust$'. I suggest to pass a .plot file converting your parameter name manually, see plot_files/example.plot for an example:
`info.to_change = {'rs_d': 'r^s_d', 'omega_cdm': '$\Omega_\mathrm{m}$'}`
In your case you would e.g. replace 'rs_d' with the name of your parameter in the log.param file and 'r^s_d' with a suitable latex name.

Best,
Thejs

**Comment by dchooper** [comment]
In a forthcoming release, MontePython will have a more rigorous treatment of latex symbols, which should avoid this type of issue.

In the meantime, when using the BK14 likelihood, it is recommended to use the `BK14.plot` file provided as an example (or copy the `info.to_change` line within that plotting file to your own plotting file).
