### ISSUE TITLE
Where can I find the .tar.bz2 file?

### ISSUE THREAD

**Issue by SSMATHJU** [brinckmann/montepython_public#341]
I see in the ReadMe that I need to untar the .tar.bz2 file but I could not find it. May I get some help?

**Comment by brinckmann** [comment]
I think this is if you download the code from the website, if you just cloned it with git you're already done. I should update this, thanks!

Best,
Thejs

**Comment by SSMATHJU** [comment]
Thanks for the help. Two more issues have arisen.

*1. When I execute MontePython.py, I encounter the following problem. Since
I am not much familiar with terminal, I have no idea what these things
mean. Is it executing correctly or do I need to have scipy installed?*
***@***.***:~$ cd montepython_public
***@***.***:~/montepython_public$ cd montepython
***@***.***:~/montepython_public/montepython$ sudo chmod +x
MontePython.py
***@***.***:~/montepython_public/montepython$ sudo
./MontePython.py
/usr/bin/env: ‘python’: No such file or directory
***@***.***:~/montepython_public/montepython$ python3
./MontePython.py
Traceback (most recent call last):
  File "/home/dell/montepython_public/montepython/./MontePython.py", line
13, in <module>
    from run import run
  File "/home/dell/montepython_public/montepython/run.py", line 8, in
<module>
    from initialise import initialise
  File "/home/dell/montepython_public/montepython/initialise.py", line 10,
in <module>
    from data import Data
  File "/home/dell/montepython_public/montepython/data.py", line 20, in
<module>
    from scipy.optimize import fsolve
ModuleNotFoundError: No module named 'scipy'
***@***.***:~/montepython_public/montepython$

*2. I couldn't find the class directory. Also how do I make clean and then
make? No idea whatsoever.*

Thanks and regards,
Subhajit..

**Comment by dchooper** [comment]
Hi Subhajit,

I would recommend that you familiarise yourself with the overall structure and purpose of MontePython and CLASS before running. Perhaps some of the course notes [here](https://lesgourg.github.io/courses.html) would be useful (for example, the Cambridge ones).

Then you can install CLASS following the instructions here: https://github.com/lesgourg/class_public/wiki/Installation

After you have done that, you can come back to the MontePython README (starting from [here](https://github.com/brinckmann/montepython_public#prerequisites)) and follow the detailed installation and running steps.

Cheers,
Deanna

**Comment by SSMATHJU** [comment]
Dear Deanna,

Thank you very much for your kind suggestions.

Regards,
Subhajit..
