### ISSUE TITLE
Import clik erro

### ISSUE THREAD

**Issue by JeremiasBezerra** [brinckmann/montepython_public#345]
Hello,

i'm testing if i can use Planck likelihood by running base2018TTTEEE.param, then i get this error:
`Cannot use clik wrapper (cause = 'libcfitsio.so.8: cannot open shared object file: No such file or directory')`
`Cannot use clik_lensing wrapper (cause = 'libcfitsio.so.8: cannot open shared object file: No such file or directory')`
Here's an image:
![image](https://github.com/brinckmann/montepython_public/assets/38176291/c1f022b2-1901-4df0-b858-c592443223e5)
Even following the Planck likelihood part (`./waf configure --lapack_mkl=${MKLROOT} --install_all_deps` and `source bin/clik_profile.sh`), when I try to import click, I get an error:
![image](https://github.com/brinckmann/montepython_public/assets/38176291/4e3b2c9c-0fe3-4a1d-add5-ab49a093ba17)

**Comment by brinckmann** [comment]
Hi,

It looks like something went wrong with your Planck installation. You will likely have to reinstall it and pay attention o the output to understand what's going wrong. From your error I wonder if maybe it's not correctly finding or using cfitsio, which is necessary, so you might look into that.

Best,
Thejs
