### ISSUE TITLE
Problems regarding plot generation.

### ISSUE THREAD

**Issue by Physics16** [brinckmann/montepython_public#346]
Hi everyone,
                       When I am trying to generate the histograms of the parameters for Lambda-CDM model, it shows an error regarding the lateX. At first, I give this command: "python montepython/MontePython.py info aurindam/2023-10-18_1000_* --want-covmat". Then it shows the following error:
--------------------------------------------------------------------------------------------------------------
**RuntimeError: latex was not able to process the following string:
'80.1'**

**Here is the full report generated by latex:
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/home/pamu11/.cache/matplotlib/tex.cache/f32a1de88930617cbbe6dbfef0ca2277.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-01-21>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))**

**! LaTeX Error: File `type1cm.sty' not found.**

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)
Enter file name: 
! Emergency stop.
<read *>        
l.4 ^^M      
No pages of output.
Transcript written on f32a1de88930617cbbe6dbfef0ca2277.log.**
--------------------------------------------------------------------------------------------------------------
But **pdfTeX** is already installed on my desktop. I don't understand why this problem happens with me. Can anybody help me out in reducing this problem.

**Comment by dchooper** [comment]
Hi, 

this is not a MontePython problem, this appears to be an issue with your latex installation (perhaps you recently did a system update and packages changed?). I would recommend checking that you have `texlive-latex-extra` and `texlive-fonts-recommended` installed, as these are needed to generate matplotlib plots that contain latex text.

As this is not a MontePython issue, I don't think we can really help more here.

Cheers,
Deanna

**Comment by Physics16** [comment]
Hi Deena,
                 Actually there is some problem with my Ubuntu OS. That's
why I couldn't get the proper installation of Latex. But later I resolved
this issue. And very very thanks for your reply.

Best wishes,
Aurindam
