### ISSUE TITLE
MPI running multiple instances

### ISSUE THREAD

**Issue by LordKaos39** [brinckmann/montepython_public#347]
running the code with mpirun -np 4 makes the entire process repeat 4 times instead of distributing it across 4 cores.

**Comment by brinckmann** [comment]
This is intended behavior, using MPI will create one chain per MPI process. If you would like to use multiple cores per process you have to use OMP, i.e:
OMP_NUM_THREADS = 4
Note it is generally recommended to do Metropolis-Hastings MCMC with at least four chains.

Best,
Thejs
