### ISSUE TITLE
How to do Fisher analysis in Montepython?

### ISSUE THREAD

**Issue by Amlan1996** [brinckmann/montepython_public#354]
Hi,

I modified the class for a new dark energy model and wanted to do some fisher analysis to forecast the upcoming CMB S4 experiment. I saw that Monte Python has a Fisher module, but I couldn't find any example param file on how to write the param file and run it explicitly for this. 

It would be great if anyone could guide me through this process of writing the parameter files, including CMB noise etc. 

Best regards,
Amlan

**Comment by brinckmann** [comment]
Hi Amlan,

The param file is the same as for MCMC. There are some instructions on how to run the code with the Fisher method in the second MontePython article: https://arxiv.org/abs/1804.07261

Best,
Thejs

**Comment by Amlan1996** [comment]
Dear Thejs,

Thanks for your prompt response. I will look into the paper more thoroughly and do it. I will ask you again if I get stuck somewhere down the line.

Best regards,
Amlan
