### ISSUE TITLE
velocity power spectrum

### ISSUE THREAD

**Issue by mahtaparsa** [brinckmann/montepython_public#37]
Is it possible to get the velocity power spectrum for dark matter or baryons from the CLASS code? I need the velocity perturbations in term of k.

**Comment by brinckmann** [comment]
You can retrieve the velocity transfer functions from CLASS with the command
cosmo.get_transfer(z)
Remember you have to add vTk to your output, i.e.
`data.cosmo_arguments['output'] = 'vTk'`
Is this what you were looking for?

Best,
Thejs

**Comment by mahtaparsa** [comment]
Thanks for your reply. Actually I need velocity perturbations of dark matter (and other components) in term of the wave number k. In the CLASS code it is possible to derive perturbations in term of conformal time, but I do not know how we can derive perturbations in term of k. (Like the matter power spectrum in term of k, but it is velocity power spectrum.)
It would be better that I ask this question in class_public. Sorry for this mistake.
