### ISSUE TITLE
computing histograms

### ISSUE THREAD

**Issue by mubecks** [brinckmann/montepython_public#38]
When I try with this command below,
`montepython/MontePython.py info $SCRATCH/montepython_output/test_planck/high_l+lowl/ $SCRATCH/montepython_output/test_planck/planck_bao/ --extra plot_files/base2015TTTEEE.extra --want-covmat --bins 10`

I got this error message so I cut down the bin number but same.
`-> Computing histograms for  n_s

 /!\ could not derive minimum credible intervals for this multimodal posterior

 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)`

**Comment by brinckmann** [comment]
Can you try using options `--keep-non-markovian` `--keep-fraction 0.7` ?
There was an issue affecting v3.0 making this necessary for analyzing. This is fixed in v3.1, which will be made public shortly.

Best,
Thejs

**Comment by brinckmann** [comment]
Alternately, update to the latest version 3.1 and the default analyze option should now be good enough! If you still get the same message you will probably need to run your chains for longer, in order to have them properly converged.

Best,
Thejs

**Comment by mubecks** [comment]
Thank you for your answer.
I will update to the latest version then try again.

Best,
yblee

**Comment by dchooper** [comment]
Hi,

For future reference: the easiest way to update MontePython is to pull the newest version from github.

Best,
Deanna
