### ISSUE TITLE
Question about the calculation of -log(Likelihood)

### ISSUE THREAD

**Issue by feuerfuchszhao** [brinckmann/montepython_public#39]
Dear all,
I am a Master student who is working on cosmology. I am doing some work about the constrains on alpha parameters in Horndeski gravity using the code MontePython together with hi_class. In these days I found something which made me confused. 

The problem is about the calculation of the -log(Likelihood) in MontePython. When we start to run a chain, the code will calculate and list the value of -log(Likelihood) for each step. For example, if there are two parameters to constrain, the output will be like this:

No.ofstep             -log(Likelihood)               parameter1            parameter2
2                            3000                                0.50                         0.40
5                            2900                                0.52                         0.42
...

Theoretically, the calculation of -log(Likelihood) should be related to the covariance matrix following this equation:

-ln(Likelihood)=0.5*d_a*(C)^(-1)_{ab}*d_b

So theoretically, if the covariance matrix is different, the -log(Likelihood) for the same point in the parameter space should be different. But when I run MontePython, I found that the value of -log(Likelihood) is the same even we choose different covariance, which made me really confused. 

My running step is as follows: 

`python montepython/Montepython.py run -p inputfile.param -o outputfolder -c convariancematrixNo1.covmat -f 0 -N 1`

when we run this, the code will calculate the -log(Likelihood) for the starting point and we didn't change anything but the covariance matrix.

`python montepython/Montepython.py run -p inputfile.param -o outputfolder -c convariancematrixNo2.covmat -f 0 -N 1`

and the -log(Likelihood) we got will be exactly the same value, even if the covariance matrix are totally different. 

Did I do something wrong or got a wrong understanding about the code? Thank you so much in advance.

**Comment by brinckmann** [comment]
Hi,

The covariance matrix input with -c is for determining the proposal distribution, i.e. steps are performed along the eigenvectors of this covmat, with the amplitude modulated by a randomly generated number between 0 and 1, as well as the jumping factor provided with -f or optimized with --superupdate .

This input covmat does not figure in the likelihood calculation otherwise, which is a different covariance matrix either provided to the likelihoods directly or computed by MontePython during the likelihood evaluation. Some likelihoods allow for specifying a covmat in the .data file, e.g.
`montepython/likelihoods/sdss_lrgDR7/sdss_lrgDR7.data`

Best,
Thejs

**Comment by feuerfuchszhao** [comment]
> Hi,
> 
> The covariance matrix input with -c is for determining the proposal distribution, i.e. steps are performed along the eigenvectors of this covmat, with the amplitude modulated by a randomly generated number between 0 and 1, as well as the jumping factor provided with -f or optimized with --superupdate .
> 
> This input covmat does not figure in the likelihood calculation otherwise, which is a different covariance matrix either provided to the likelihoods directly or computed by MontePython during the likelihood evaluation. Some likelihoods allow for specifying a covmat in the .data file, e.g.
> `montepython/likelihoods/sdss_lrgDR7/sdss_lrgDR7.data`
> 
> Best,
> Thejs

Thank you so much Thejs, this helps me a lot.
