### ISSUE TITLE
Planck 2018 data

### ISSUE THREAD

**Issue by mahtaparsa** [brinckmann/montepython_public#41]
Is it possible to constrain cosmological models with Planck 2018 data (specially polarization data) using MontePython? I mean that if it needs to define a new likelihood, because for Planck 2015 data the file plc-2.0 were available to use the corresponding data. And also, should we define new nuisance parameters (different from 2013 or 2015 data)?

**Comment by brinckmann** [comment]
Hi,
No, the Planck collaboration have not yet published their 2018 likelihoods.
Best,
Thejs

**Comment by mahtaparsa** [comment]
Thanks for your reply.

**Comment by surgithub** [comment]
Hi, When MontePython will be updated with the recently released Planck 2018 likelihood?

**Comment by brinckmann** [comment]
I apologize for the delay, I just got back from holiday. I have just released v3.2 which includes all the Planck 2018 likelihoods and example param files (thanks to Deanna Hooper), as well as new KiDS+VIKING-450 and KiDS-450 correlation function likelihoods and BOSS DR12 and eBOSS DR14 Lya and QSO BAO likelihoods. Enjoy!

**Comment by surgithub** [comment]
Thank you!
