### ISSUE TITLE
Maximum Likelihood of Run

### ISSUE THREAD

**Issue by lanny222** [brinckmann/montepython_public#42]
How do you exactly extract the maximum of likelihood of a simulation, i only seem to receive the min, help appreciated

**Comment by brinckmann** [comment]
Hi,
When you get the best fit you are getting the minimum of minus one times the log of the likelihood likelihood, i.e. -log(L), which is the maximum of the likelihood.
Best,
Thejs

**Comment by lanny222** [comment]
Im seeing -Log(L) being listed when the simulation is running yet when i analyze the chains, in the bestfit file it outputs i seem to get no -Log(L)

**Comment by brinckmann** [comment]
The .bestfit file only contains the parameters, if you look at the .log file you will see the -log(L) value for the best fit.
Best,
Thejs

**Comment by lanny222** [comment]
Hey Thejs, it still only seems to be outputting the min i attached a screenshot of the .log file

<img width="855" alt="Screenshot 2019-03-15 at 00 22 21" src="https://user-images.githubusercontent.com/43097202/54397943-8a50f900-46b8-11e9-81d9-862369b23f63.png">

**Comment by brinckmann** [comment]
As I said, the minimum of the -log(L) is the maximum of the likelihood L. Is this not what you're after?
Best,
Thejs

**Comment by lanny222** [comment]
Oh, i must have misunderstood, yes that it cheers for the help
