### ISSUE TITLE
Chi squared issue

### ISSUE THREAD

**Issue by lanny222** [brinckmann/montepython_public#43]
Im testing some extended teleparallel theories (f(T)) that approach Lambda CDM in some limit, using Plack 2015 + JLA + WiggleZ likelihoods, is it normal to be getting such a high value for chi square (in the range 10000)? or do i simply need to compare that value relative to the standard model's with the same likelihoods, as in various papers im seeing a chi squared min of the range 700-1000

**Comment by dchooper** [comment]
Hi,

The individual chi^2 values don't really tell you much, it's always more informative to compare them among different models (with the same likelihoods). So as you say, you want to compare your model's chi^2 to lcdm chi^2 using, in your case, Planck 2015 + JLA + WiggleZ likelihoods.

Best,
Deanna
