### ISSUE TITLE
H prime at current times

### ISSUE THREAD

**Issue by lanny222** [brinckmann/montepython_public#44]
In a few of my models i needed to amend class to be able to input the Hubble constant at current times. I simply copied the code of H0 in order to implement this but just wanted to make sure i'm doing it correctly. Has anyone had previous experience with this? Thanks in advance

**Comment by dchooper** [comment]
Hi,

This seems to be a CLASS question, rather than a MontePython question. But indeed, it's usually recommended to find a similar parameter already in CLASS and use that to implement your parameter.

Best,
Deanna
