### ISSUE TITLE
Question about add a new parameter to montepython

### ISSUE THREAD

**Issue by Annemxj** [brinckmann/montepython_public#45]
Hello，We added a new parameter "X" about Dark Energy to the CLASS. Now we want to constrain X using montepyhon, how can we change the montepython ? I was wondering if it would be possible to share the specific instructions? @brinckmann

**Comment by lesgourg** [comment]
1) First, remember that once you have added your new parameter to the C part of CLASS, you must add it consistently in the CLASS python wrapper. Usually this just requires one extra line in python/cclassy.pxd, in which you just redeclare the variable inside the wrapper. If for instance your new parameter is a new field in the background structure, that you declared in background.h as

double X;

and that is called in the rest of the code as pba->X, then you must do the following in python/cclassy.pxd:

* localise the place where other background variables are redeclared:

    cdef struct background:
        ErrorMsg error_message
        int bg_size
        int index_bg_ang_distance
        int index_bg_lum_distance
        int index_bg_conf_distance
        int index_bg_H
        [etc.]

* in this list, just redeclare your new variable:
        double X;

After recompiling, you should be able to pass X as a new input parameter when you call CLASS through a python script or a notebook.

2) the reason for which we don’t have like for CosmoMC a place explaining how to define new parameters in MontePython is that there is no need to do anything inside the MontePython code! Any parameters known by CLASS can be used directly in MontePython without any new line of code.  You just need to say in your input file that you want to vary X. For instance, after the line

data.parameters['tau_reio']    	= [0.085,  -1,-1, 0.0044,1,   'cosmo']

you could have a new line

data.parameters[‘X']    	= [0.5,  0, 1,  0.2, 1,   'cosmo’]

and the new parameter will be varied (in this example, in the range [0,1], starting from 0.5, and with an initial sigma of 0.2).
If the MontePython stops and complains that CLASS does not know X, it means that you did not finish step 1) correctly (which you would have also seen when trying to call CLASS from a python script/notebook).

**Comment by Annemxj** [comment]
Thanks for you reply, the problem has been totally solved at your suggestion.
