### ISSUE TITLE
Mock CMB Temperature Only?

### ISSUE THREAD

**Issue by syasini** [brinckmann/montepython_public#46]
I am running parameter estimation using the `Likelihood_mock_cmb` likelihood class and my input files include the TT, EE, and TE power spectra. Is there a quick way to turn off polarization and only include TT in the likelihood without changing the input files?

**Comment by brinckmann** [comment]
Hi,
Unfortunately there's not a flag to control this, but it shouldn't be too hard to add. Look at what is done with the `self.ExcludeTTTEEE` flag, which is for running with lensing extraction only ('pp'). I don't think you need to modify the fiducial file read/write, which makes it easier. You should double check, but I think this means the change amounts to modifying the code in two places:

In the compute_lkl function (line 1468-1473 on branch 3.1):
```
         if not self.ExcludeTTTEEE:
             num_modes=2
         # default 0 if excluding TT EE
         else:
             num_modes=0
```
To something like
```
         if not self.ExcludeTTTEEE:
             if self.OnlyTT:
                 num_modes=1
             else:
                 num_modes=2
         # default 0 if excluding TT EE
         else:
             num_modes=0
```

Normally if you have no lensing extraction and no B modes, you will find yourself in this part in the compute_lkl function (line 1542-1548 on branch 3.1):
```
            else:
                Cov_obs = np.array([
                    [self.Cl_fid[0, l], self.Cl_fid[2, l]],
                    [self.Cl_fid[2, l], self.Cl_fid[1, l]]])
                Cov_the = np.array([
                    [cl['tt'][l]+self.noise_T[l], cl['te'][l]],
                    [cl['te'][l], cl['ee'][l]+self.noise_P[l]]])
```
And you want to add a new part before this with something like
```
            elif self.OnlyTT:
                Cov_obs = np.array([[self.Cl_fid[0, l]]])
                Cov_the = np.array([[cl['tt'][l]+self.noise_T[l]]])
```
If you want lensing extraction or B-modes there's an extra step and you should have a look at the preceding code segment. Also, you may want to add some minor things for consistency, like making sure self.OnlyTT is always defined, that self.OnlyTT and self.ExcludeTTTEEEE can't be used together etc.

Best,
Thejs

**Comment by syasini** [comment]
Thanks for your quick and detailed reply, Thejs. 

If you think it'd be helpful I can create a pull request or send you the modified likelihood file after I implement the changes and run some tests.

**Comment by brinckmann** [comment]
Thanks I have added this for v3.2.
