### ISSUE TITLE
Small bugfix for PolyChord.py

### ISSUE THREAD

**Issue by fkoehlin** [brinckmann/montepython_public#49]
Hi Thejs, all,

Great to see that PolyChord is now available as sampler choice, quite timely! While trying it out I ran into an "invalid index to scalar variable" error.

It's caused by line 360 in `PolyChord.py`:
`logl = sampler.compute_lkl(cosmo, data)[0,0]`

And resolved by naively removing the square bracket expression: 
`logl = sampler.compute_lkl(cosmo, data)`

Cheers,

Fabian

**Comment by brinckmann** [comment]
Thanks I have added your pull request for v3.2.
