### ISSUE TITLE
Chain restart issue with commented last line

### ISSUE THREAD

**Issue by anirbandas89** [brinckmann/montepython_public#56]
Hi all,

Recently I ran into a problem with restarting a chain with the -r <chain_file> option. The error was the following.

rank =  0
Traceback (most recent call last):
  File "../montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/user1/anirban/bdm_class/montepython_public-3.0/montepython/run.py", line 44, in run
    sampler.run(cosmo, data, command_line)
  File "/user1/anirban/bdm_class/montepython_public-3.0/montepython/sampler.py", line 44, in run
    mcmc.chain(cosmo, data, command_line)
  File "/user1/anirban/bdm_class/montepython_public-3.0/montepython/mcmc.py", line 418, in chain
    sampler.read_args_from_chain(data, command_line.restart)
  File "/user1/anirban/bdm_class/montepython_public-3.0/montepython/sampler.py", line 100, in read_args_from_chain
    chain_file.tail(1)[0].split('\t')[i])
IndexError: list index out of range

In line 100 of sampler.py, the code reads the last line of the <chain_file> to use it as the starting point for the new chain using the tail() command. In my case, the last line happened to be a comment-

"# After 5624 accepted steps: stop adapting the..."

which was creating the problem. Maybe some filtering with '#' is needed to read the last sample point.

Thanks,
Anirban

**Comment by brinckmann** [comment]
Thank you for reporting this Anirban! I'll add the bugfix in the next version.

Best,
Thejs

**Comment by lesgourg** [comment]
Hi Thejs,
Looking forward to see you are CCA in 4 weeks! I think I won’t make it to StonyBrooke, becuase I don’t have so much time available and need to collaborate with Yacine at NYU. But many thanks for the proposal.
Deanna and Nils told me that your storage on the cluster cannot be accessed anymore. They are about to write to the Helpdesk to get this fixed. Nils urgently need this space for the new project. Once it is accessible again (hopefully this afternoon), is it OK if I just delete your data? You must have transferred it by now?
Cheers
Julien

**Comment by brinckmann** [comment]
Thanks @anirbandas89 I have added a bugfix for v3.2.
