### ISSUE TITLE
How to use "Derived" sampling method?

### ISSUE THREAD

**Issue by ClaudioNahmad** [brinckmann/montepython_public#61]
Hello Thejs,

I have finished running a couple of long chains which have converged properly (R-1 << 0.1 and Acceptance rate ~ 25%), however, i forgot to ask MP to calculate some derived parameters. 

i.e. the code ran and found best-fits for w_cdm(=\Omega_cdm*h^2) and w_baryons (these parameters are 'cosmo' parameters), but i need to report \Omega_matter (=\Omega_cdm+\Omega_b) instead of w_cdm and w_b separately.

I read the paper (arXiv:1804.07261) but couldn't find a clear method for using the Derived method. Could you give me a hand?

Thanks in advance!

**Comment by lukashergt** [comment]
Hi Claudio,

check out the file `plot_files/example.plot`. In there it actually shows how you can turn `omega_cdm` into `Omega_m`. Check out the `info.redefine` and `info.to_change` commands in particular. You can pass this plot file to the `info` command via the `--extra` option:
```bash
python montepython/MontePython.py info --extra plot_files/example.plot <chain files>
```

You might also find the MontePython documentation on [Analyzing chains and plotting](https://monte-python.readthedocs.io/en/latest/getting_started.html#analyzing-chains-and-plotting) helpful.

Best,
Lukas

**Comment by ClaudioNahmad** [comment]
Thank you Lukas!
