### ISSUE TITLE
Polychord and parallelisation

### ISSUE THREAD

**Issue by ivandebono** [brinckmann/montepython_public#62]
PolyChordLite (the current public version of PolyChord) can be parallelised by running with mpirun or mpiexec. No problems there.

But how is it parallelised in MontePython? If I understood the code correctly, when you use mpiexec -np N to run MontePython, N instances of the sampler are launched. Polychord is launched by the line:
`polychord_run(loglike, nDims, nDerived, settings, prior)`.

Is this parallelised?

Also, what does this message mean: "PolyChord: MPI is already initi[a]lised, not initialising, and will not finalize" ?

Finally, is it normal for MontePython to stop outputting anything to the output folder a few hours into a PolyChord run? The jobs in question (on a cluster) are still running, so I assume it's not an error. Aborting the run and restarting didn't change anything.

**Comment by brinckmann** [comment]
Hi Ivan,

I apologize for the delayed reaction. I am not very familiar with the PolyChord implementation, but maybe @williamjameshandley or @dchooper have some input on this? Thanks Will and/or Deanna!

Best,
Thejs

**Comment by williamjameshandley** [comment]
>Is this parallelised?

Yes.

However, you should note that PolyChord run's best with no openMP parallelisation, only pure MPI parallelisation (i.e. you should set `OMP_NUM_THREADS=1`, or equivalent, and devote all cores to MPI). PolyChord is parallelised up to the number of live points, and for test runs you should set nlive to be pretty low (10-50), before scaling up for your final publication-quality runs (run time is linear in the number of live points).

>Also, what does this message mean: "PolyChord: MPI is already initi[a]lised, not initialising, and will not finalize" ?

This is a harmless warning indicating that MontePython must handle cleaning up MPI (which it does)

>Finally, is it normal for MontePython to stop outputting anything to the output folder a few hours into a PolyChord run? The jobs in question (on a cluster) are still running, so I assume it's not an error. Aborting the run and restarting didn't change anything.

That is a little unusual. Is this a modified version of MontePython? Are you able to give us any information as to what kind of physical models you're running? @lukashergt has seen similar behaviour in the past with curvature based models.

**Comment by lukashergt** [comment]
>> Finally, is it normal for MontePython to stop outputting anything to the output folder a few hours into a PolyChord run?
>
>  @lukashergt has seen similar behaviour in the past with curvature based models.

I think I might know what @ivandebono is referring to. I get this blank period after things have been set up and before the actual sampling happens (independent of which models I run). I think the duration of this blank period might scale with cores/tasks and can last over an hour until sampling eventually starts and we get output again. I would be quite curious to know what is causing this, too. 

Might this be related to using PolyChord with Planck? Does PolyChord have to read in Planck data files for every task?

**Comment by williamjameshandley** [comment]
It does, and this can take a while for certain architectures, although it does seem to take a lot longer with MontePython in comparison with cosmomc. @brinckmann: is similar behaviour seen in MontePython, but with fewer MPI cores?

**Comment by ivandebono** [comment]
I'll try to provide as full an answer as possible.

My cosmological model is LCDM with features in the primordial power spectrum. The model contains massive neutrinos. The data set is Planck 2015. With Metropolis-Hastings it takes quite some time to achieve convergence for the chains, so I know the computation time for the likelihoods is quite heavy.

Since I posted the issue on Github, I've had an email exchange with @williamjameshandley (whom I wish to thank), and I followed his suggestions on the best settings for running on a cluster. I used these parameters:

-pe openmpi 16
export OMP_NUM_THREADS=1
mpiexec -np 16
--PC_nlive 50

The other Polychord parameters take the default values.

I managed a complete run this way. I was still getting updates in the relevant files (phys, phys-live, dead, dead-birth, and sometimes stats) only every four hours or so.

However, the plots were not quite publication-quality, so I reran with --PC_nlive 200. 

Lo and behold, I got the same stalled runs.

I tried a different run with --PC_nlive 100 (and slightly wider priors for some of the parameters to improve the parameter estimation and the plots). The run was completed within 48 hours, with no errors. The plots were still not quite what I wanted, so I reran in the same folder, this time with the default nlive (it's 850) and --PC_precision_criterion 0.0009. Again, it stalled.

The last output message I got was:

```
Run Settings
nlive    :     850
nDims    :      34
nDerived :       4
Doing Clustering
Generating equally weighted posteriors
Generating weighted posteriors
Clustering on posteriors
Writing a resume file tohndl_btrprs/PC/hndl_btrprs.resume

Resuming from previous run
number of repeats:           14         352
started sampling
```
So it seems the runs stall at the point where sampling is about to start.

I'm not quite sure how to tackle the problem. Few live points? The purpose of my work is to find whether the posterior is multimodal, so I need the runs to be as accurate as possible.

Could it be down to the compiler?

I'd be happy to provide any further details if it helps.

**Comment by williamjameshandley** [comment]
From my experience, for a default cosmology run I would usually expect <2 hours per live point, although this is with cosmomc (@lukashergt What is total run time per live point for your MontePython runs? i.e. `wall_time * number_of_cores / nlive`). You seem to currently be running at ~ 8 hours per live point. This difference could be down to cluster differences, or the fact that you've added quite a few extra slow parameters (given that ndims is 34). 

@brinckmann has there been any work on semi-slow parameters/a more general parameter speed hierarchy? (we have discussed this in the past)

Given that run time is linear in the number of live points, and your 100 point live run took 48 hours, I would expect the 850 nlive run to take ~ 17 days. You can reduce this walltime by using more cores, but that is dependent on how much cluster time that you have. You also might like to increase the frequency of updates by reducing the compression factor. It's default is exp(-1), but you might like to set it to closer to 1 (say 0.95). It would then update every (1-compression_factor)*nlive iterations.

>The plots were still not quite what I wanted, so I reran in the same folder, this time with the default nlive (it's 850) and --PC_precision_criterion 0.0009.

If you mean you re-started the lower live point run with a higher set of live points, I wouldn't advise changing the number of live points dynamically unless you've given these papers a thorough read
- [Skilling's original nested sampling paper](https://projecteuclid.org/euclid.ba/1340370944)
- [Dynamic nested sampling](https://arxiv.org/abs/1704.03459)

**Comment by ivandebono** [comment]
I'll get back to you with the information you need.

I'm not sure I understand your last poibt. How should I rerun Polychord to obtain better plots once the run run is complete? i.e. Is there a way of reusing the contents of previous runs instead of starting from scratch?

**Comment by williamjameshandley** [comment]
> I'm not sure I understand your last poibt. How should I rerun Polychord to obtain better plots once the run run is complete? i.e. Is there a way of reusing the contents of previous runs instead of starting from scratch?

Re-using the contents of runs properly with nested sampling is non-trivial (and does form part of my ongoing research programme). The issue with re-starting at the end is that the live points have evolved to very close to the likelihood peak, so the method that you propose above wouldn't generate any usable points. You would have to restart somewhere in the middle, which is not something that the current resume strategy supports.

You can combine the outputs of full completed runs (from start to finish), by re-scaling the weight column so that the total sum of each run is proportional to the evidence.

However, in practice, what I tend to do is to do experiment with a few low nlive point runs (~100) and then do a full publication run (~1000). The benefit that you would get from including the low nlive runs is thus pretty marginal (~10% improvement).

**Comment by ivandebono** [comment]
Just a little update.

I tried the following options and it worked like a charm:

**--PC_precision_criterion 0.0005** #I just wanted to push the limits for the sake of testing 
**--PC_nlive 850** #I could probably go up to 1000 or more
**--PC_compression_factor 0.95** #The chain files are now being updated far more frequently, so I can monitor the progress of the runs a lot better. This parameter seems to make all the difference.

I'm running Montepython with mpiexec -np 16.

Thank you @williamjameshandley and @brinckmann for your invaluable advice.
