### ISSUE TITLE
External power spectrum: incorrect use of inline comments

### ISSUE THREAD

**Issue by SuvedhaNaik** [brinckmann/montepython_public#64]
I was trying to include a power spectrum template in CLASS using external_Pk command. I want to explore the parameter space involved in this Power spectrum template using MontePython. I have followed the exact steps given in the external_Pk README file. I tried with the already available power spectrum file given in CLASS (i.e. generate_Pk_example.py). I'm getting a zero division error.
 I checked for all the scenarios that could result in such error. But I couldn't fix it.
Any references involving such example will also be helpful.

📌Attachments:
i) Input parameter file used along MontePython command
ii) External power spectrum template as defined in CLASS
iii) Error log
[Attachments.zip](https://github.com/brinckmann/montepython_public/files/3337982/Attachments.zip)

**Comment by lukashergt** [comment]
Hi,
which version of python are you using?

Two things:
1. I would keep the ordering of the input parameter file clean, i.e. put the `cosmo_arguments` where the other `cosmo_arguments` are. I'm not sure whether this is important for the `cosmo_arguments`, but I have run into problems before when mixing `cosmo`, `nuisance`, and `derived` parameters.
2. Since you are using `custom2` and `custom3` as parameters you shouldn't be using `ln10^{10}A_s` and `n_s`.

Maybe this already helps.
Best,
Lukas

**Comment by SuvedhaNaik** [comment]
Hi Lukas,

First of all thanks a bunch for responding.

I'm using python 2.7.12.

I do get the power spectrum values when I run `generate_Pk_example.py` from terminal without any error. 

Regarding the things you have mentioned to follow:
1. I changed the ordering of different kinds of parameters as you mentioned. But I'm still getting Zero Division Error. This is evidently because the parameter values written in the input file are not being passed to the code. (I verified this by printing the values of k_0, A_s, n_s in the python file). This is where I'm clueless. 

2. I have already commented out ln10^{10}A_s and n_s in my parameter file. Still didn't work.

It would be really great if you could point out any other possible mistake. 

Thanks again, 
Best regards,
Suvedha

**Comment by lukashergt** [comment]
Hi Suvedha,
if I remember correctly you are **not allowed to do inline comments in the input parameter files**, i.e. change e.g.
```
data.cosmo_arguments['custom1'] = 0.05		#k_pivot
```
to e.g.
```
# custom1 = k_pivot
data.cosmo_arguments['custom1'] = 0.05
```
Hope this'll do the trick.
Best,
Lukas

**Comment by SuvedhaNaik** [comment]
Hi Lukas, 

You are right. I should not have put the comments with those commands. Thanks a lot for finding it out. I really appreciate your patience and time you spent. Thanks again Lukas. 

Best Wishes, 
Suvedha

**Comment by lukashergt** [comment]
Great! I'm glad that solved it. Possibly worth adding something like "(incorrect use of inline comments)" to the title to make it more specific and such that other people can resolve similar issues more quickly.

It would also be good if you could close the issue now that it's solved.
