### ISSUE TITLE
Non-flat priors in montepython

### ISSUE THREAD

**Issue by amontiela** [brinckmann/montepython_public#69]
Hi,

I am trying to implement non-flat priors for a spectral index running parameter. Can anyone guide me on how to implement this in montepython?

Any suggestions will be appreciated.

Thank you!

**Comment by amontiela** [comment]
Update:

I have seen that I could do something similar to Anze Slosar suggests in the following link: 
https://cosmocoffee.info/viewtopic.php?f=11&t=914&p=2845&hilit=non+flat+priors#p2845

Does anyone know how implement this in montepython?

**Comment by lukashergt** [comment]
Hi @amontiela ,

on [this website](https://lesgourg.github.io/courses.html) you can find an overview of lectures and workshops on CLASS and MontePython. In your case the [MontePython Exercise 2](https://lesgourg.github.io/class-tour/Cambridge/180912_MontePython_exercises.pdf) on adding a new likelihood from the Kavli workshop in Cambridge should be helpful.

Best,
Lukas

**Comment by amontiela** [comment]
Thank you, @lukashergt but I'm afraid I didn't explain it very well. I want to use Planck 2015 and the problem is I don't know how modify (if I had to do) the Likelihood_clik to implement non-flat priors on the spectral index running parameter .

**Comment by lukashergt** [comment]
Why wouldn't it work the way it is described in Exercise 2, where it explains how to set a Gaussian prior on the physical baryon density? In the same way you could create a new likelihood that sets a prior of your choice on the running of n_s and add that likelihood to the Planck likelihoods in your input params file.

**Comment by lukashergt** [comment]
In a bit more detail how to create a Gaussian prior on the running of the spectral index:

* In your input param file add the new likelihood called `alpha_s_prior` (or any other name that you would prefer, but then replace accordingly in the following) to the Planck likelihoods in `data.experiments`, e.g.:
```python
data.experiments = ['alpha_s_prior', 'Planck_highl', 'Planck_lowl', 'Planck_lensing']
```

* In `montepython/likelihoods` copy the folder `hst` to a new folder called `alpha_s_prior`. 

* In your new folder `alpha_s_prior` rename `hst.data` to `alpha_s_prior.data`.

* In `alpha_s_prior.data` change all instances of `hst` to `alpha_s_prior`. Change the little Hubble `h` to the running `alpha_s` and change the  numeric values for mean and sigma to the ones for the running:
```python
# Values for Planck 2015
alpha_s_prior.alpha_s = -0.0084
alpha_s_prior.sigma = 0.0082
```

* In `__init__.py` rename all instances of `hst` to `alpha_s_prior` and all instances of little Hubble `h` to `alpha_s`:
```python
import os
from montepython.likelihood_class import Likelihood_prior


class alpha_s_prior(Likelihood_prior):

    # initialisation of the class is done within the parent Likelihood_prior. For
    # this case, it does not differ, actually, from the __init__ method in
    # Likelihood class.
    def loglkl(self, cosmo, data):

        alpha_s = cosmo.alpha_s()
        loglkl = -0.5 * (alpha_s - self.alpha_s) ** 2 / (self.sigma ** 2)
        return loglkl
```

Note: I haven't actually tested this, but I think this should work.

**Comment by amontiela** [comment]
Hi, @lukashergt! Thank you so much for your so detailed answer, I really find it very useful.

Regarding to my question, I wanted to know how to put non-rectangular boundaries for one parameter (alpha_s) and not how to put a gaussian prior or another (sorry for that, I made a mistake in the original explanation). The idea is pretty similar to the one posted in

https://cosmocoffee.info/viewtopic.php?f=11&t=914&p=2845&hilit=non+flat+priors#p2845

So, I am interested in to obtain constraints for some parameters, say, A, B and alpha_s. Two of them - A and B - have rectangular boundaries, so I can define them as usual in the .param file. But the third - alpha_s - have boundaries which are functions of, say, A. I figured out that I needed to modify at some level the likelihood of Planck but I didn't know how.

What I did is something similar to Anze Slosar's suggestion:
- First, I put a very large flat prior on alpha_s. In the likelihood_class.py file, I duplicated the likelihood for clik and I renamed it; before the `return lkl`, I put the condition I need to fulfill to guarantee that when the exploration is out of boundaries determined by the condition (related to the A parameter), the code returns a value to discard:
```
###################################
# CLIK TYPE LIKELIHOOD
# -> clik_fake_planck, clik_wmap, etc.
###################################
class Likelihood_clik_alpha (Likelihood):

.
.
.
        condition for alpha
        return lkl
```
- After that, I think it is just needed to call the  **Likelihood_click_alpha** in the respective Planck Likelihood. The `__init __. Py` should be:
```
from montepython.likelihood_class import Likelihood_clik

class Planck_highl_TTTEEE(Likelihood_clik):
    pass
```
