### ISSUE TITLE
Planck likelihood download link broken

### ISSUE THREAD

**Issue by eddedmondson** [brinckmann/montepython_public#7]
There's a link in README.rst to the Planck likelihood download - 
http://www.sciops.esa.int/index.php?project=planck&page=Planck_Legacy_Archive

This is unfortunately returning at 404 so I'm guessing the link needs updating.

**Comment by ivandebono** [comment]
Try this link:
[http://pla.esac.esa.int/pla/#cosmology](url)

**Comment by brinckmann** [comment]
This has been fixed in v3.1, thanks!

Best,
Thejs
