### ISSUE TITLE
How change the sampling distribution of a parameter

### ISSUE THREAD

**Issue by Jugabuntu** [brinckmann/montepython_public#71]
Hi everyone,
I'm kind of new to Montepython and coding in general, so I'll try to explain at my best. What I need to do is to change the sampling distribution of two parameters I defined in CLASS (in particular in the input file energy_injection.c contained in HyRec), the target is to change the prior distribution into a Jeffreys' distribution.
 
My doubts are:

1) is it correct that it is assumed as default an uniform distribution for these parameters? If yes, where do I see this?
2) where can I change this distribution? 

Thank you all!

**Comment by brinckmann** [comment]
Hi,

You have a few different options for modifying the proposal/prior distribution of MontePython, but we don't have a streamlined way of doing this.

Option A, modify at the step proposal:
In `montepython/mcmc.py` you can modify the place where the steps are proposed. The default option is 'fast' sampling:
```
    elif data.jumping == 'fast':
        #i = k % len(vector)                                                                                                                                                     
        j = k % len(data.over_sampling_indices)
        i = data.over_sampling_indices[j]
        ###############                                                                                                                                                          
        # method fast+global                                                                                                                                                     
        for index, elem in enumerate(data.block_parameters):
            # When the running index is below the maximum index of a block of                                                                                                    
            # parameters, this block is varied, and **only this one** (note the                                                                                                  
            # break at the end of the if clause, it is not a continue)                                                                                                           
            if i < elem:
                if index == 0:
                    Range = elem
                    Previous = 0
                else:
                    Range = elem-data.block_parameters[index-1]
                    Previous = data.block_parameters[index-1]
                # All the varied parameters are given a random variation with a                                                                                                  
                # sigma of 1. This will translate in a jump for all the                                                                                                          
                # parameters (as long as the Cholesky matrix is non diagonal)                                                                                                    
                for j in range(Range):
                    sigmas[j+Previous] = (math.sqrt(1./Range)) * \
                        rd.gauss(0, 1)*data.jumping_factor
                break
            else:
                continue
```
Here steps are generated from a Gaussian distribution `rd.gauss(0, 1)`, so you could modify this part for the parameters you want to sample differently. The randomly generated number is then multiplied with the jumping factor and the inverse square root of the dimension. The array produced is then multiplied with the Cholesky decomposition of the covariance matrix. Before starting you may want to read the section on fast sampling in the MontePython 3 paper Brinckmann & Lesgourgues 1804.07261. This will require paying careful attention to the indices and finding a way to select the ones corresponding to your model.

Option B, modify parameter after sampling:
Another option (the one I usually use) is to introduce a dummy sampling parameter by modifying `montepython/data.py`, which then modifies the sampled parameter into the one passed to CLASS. An example is log sampling:
```
            elif elem == 'log10N_dg':
                self.cosmo_arguments['N_dg'] = 10**(self.cosmo_arguments[elem])
                del self.cosmo_arguments[elem]
```
where I introduced the dummy parameter 'log10N_dg', from which 'N_dg' = 10**('log10N_dg') is constructed and passed to CLASS.

Option C, the -T option or adding a likelihood:
The third option is to use the temperature option -T or to create something similar by modifying the likelihood directly. Along the same vein if your change to Jeffrey's Prior sampling can be expressed in terms of an additive likelihood you can create a new likelihood applying the change. See the MontePython resources on Julien Lesgourgues' course page for how to add likelihoods: [https://lesgourg.github.io/courses.html](https://lesgourg.github.io/courses.html) .

I hope this helps!

Best,
Thejs

**Comment by Jugabuntu** [comment]
Thank you so much! It is actually much more clear now!
