### ISSUE TITLE
1-sigma value in the parameter file

### ISSUE THREAD

**Issue by SuvedhaNaik** [brinckmann/montepython_public#73]
Hello,  

I want to understand more clearly what does `1-sigma` value in `.param` file do exactly in `MontePython`. From the documentation I understand that it is the guess for standard deviation of posterior distribution. In the situations, where I have no clue about it, what values shall I give?

Thanks in advance, 
Suvedha

**Comment by brinckmann** [comment]
Hi Suvedha,

The 1-sigma value is used to determine the magnitude of the jump in cases where you do not provide an input covariance matrix. Specifically, a diagonal covariance matrix is constructed where the diagonal elements are given by the variance of each parameter.

Try to provide an educated guess, but if you have absolutely no idea I would suggest something along the lines of 10% of the prior range. E.g. if you have a parameter that is allowed to take values from 0 to 1, and you have no idea what might be preferred, I'd set it to 0.1. The better starting guess you can give MontePython the better chance your initial run is successful. If you have little prior information you may need to try a few times, perhaps extracting some information about the parameter from previous runs that did not converge.

Best,
Thejs

**Comment by SuvedhaNaik** [comment]
Hi Thejs, 

That was very helpful. Thank you very much.

Regards,
Suvedha
