### ISSUE TITLE
Transparency of contour plots

### ISSUE THREAD

**Issue by Jugabuntu** [brinckmann/montepython_public#74]
Hi everyone! I'm trying to custom my triangle plots by plotting 3 different cases in the same figure with the command --extra. Do you know how can I have the transparency for the plots so that I don't see only the superior contour?
Thanks in advance!

**Comment by brinckmann** [comment]
Hi,

This is controlled via info.alpha in the .plot file passed with `--extra plot_files/example.plot`, where the format should be a list with the same number of entries as the number of runs/contours. E.g:
`info.alpha = [1.0,0.7,0.4]`

Best,
Thejs

**Comment by Jugabuntu** [comment]
I am sorry I don't understand this. I am considering in info.plot of the example.plot 3 parameters and with --extra I am combining three cases I have been running separately. So I should consider something like this?

info.alpha = [1.0,0.7,0.4,1.0,0.7,0.4]

It is really not clear what to write in the list anyway, to have transparency between the different contours.
Sorry, I am quite new to Montepython, still trying to understand how it works.
