### ISSUE TITLE
chi-squared issues

### ISSUE THREAD

**Issue by ClaudioNahmad** [brinckmann/montepython_public#75]
Hello, here asking some questions again.

I am testing a model with MP3.1, i used the following datasets:
-CMB:Planck (TT+lowP) 
-Supernovae: JLA  sample
-BAO: BOSS DR12 sample

I ran the model with MP and used the chains in the following manner:
1) BAO + SN
2) BAO + SN + CMB

in which i got the following min(-loglike):

1) min(-loglike) (BAO+SN) = 342.92
2) min(-loglike) (BAO+SN+CMB) = 5987.82

The calculation of the chi^2(BAO+SN) and chi^2(BAO+SN+CMB) is direct: x^2=2(-loglike).

I am being asked to report the chi^2 in SEPARATE, i.e. 
a) chi^2(BAO) 
b) chi^2(SN) 
c) chi^2(CMB)

My question here is the following: if i didn't run specific chains with ONLY bao, sn and cmb (in separate) is it possible to "separate" the chi^2 contributions of e.g. BAO from the chi^2 of BAO+SN? or do i need to run the model again using only BAO, only CMB and only SN, respectively ?

Thank you in advance, greetings!

-Claudio Nahmad

**Comment by brinckmann** [comment]
Hi Claudio,

Do you need this for all points in the chains or only for the best fit? For the best fit (or any arbitrary point you want) you can extract this information very simply with the flag `--display-each-chi2 ` . Note that this is a `run` flag, i.e. you do something like
`python montepython/MontePython.py run -p input/your_param_file.param -o chains/chisq2_check -b chains/your_chains/your_chains.bestfit -f 0 --display-each-chi2`
where the `-f 0` is to make sure the run does not make a jump away from the bestfit that you are passing with `-b chains/your_chains/your_chains.bestfit` .

Best,
Thejs

**Comment by ClaudioNahmad** [comment]
Thank you very much, that's exactly what i was looking for!
