### ISSUE TITLE
Minimum credible intervals

### ISSUE THREAD

**Issue by ivandebono** [brinckmann/montepython_public#78]
Have you a reference for the method used to derive the minimum credible interval in analyze.py? The name should be Jan Hamann, with a double N.

I came up against the problem of mulimodal posteriors and I'd be interested in exploring different methods.

**Comment by brinckmann** [comment]
Thanks, I fixed the typo in Jan's name!

Your question probably isn't relevant anymore, but usually something like MultiNest, PolyChord or emcee (CosmoHammer) works better for multimodal posteriors than Metropolis-Hastings, which is the default MCMC algorithm in MontePython. You can change the method with e.g. `-m NS` for MulitNest.

Best,
Thejs
