### ISSUE TITLE
Bug when running info 

### ISSUE THREAD

**Issue by AngusWright** [brinckmann/montepython_public#80]
Commit c33dbae05bb1faf55608ab0cd06e600495d68d25 introduced a bug in montepython/analyze.py (line 1465 in the 3.2 branch). The current code fails to match subfolders when a trailing slash is included in the folder path.

**Comment by brinckmann** [comment]
Thank you, I will look at how to fix this for the next version!

Best,
Thejs

**Comment by brinckmann** [comment]
This should be fixed for the shortly upcoming version 3.3.

Best,
Thejs
