### ISSUE TITLE
Numbers of cores

### ISSUE THREAD

**Issue by DavidFigueruelo** [brinckmann/montepython_public#82]
Hello everyone,

I am having some kind of strange problem while running MP. I am running it on a  AMD RYZEN THREADRIPPER 2990X SKT TR4 250W processor that has 32 cores.  I have tested it in a personal laptop and no problem appears.

When i run it, after a few steps (~10 to 200) the computer stops in a weird way, every USB port just switches off(mouse, monitor,..)  while the light of the CPU continue to be on. I have to restart the computer, and when I open the file of that run there is a message saying it is damaged and another one saying there was a problem with one program.

I have found that by disabling the SMT mode in the BIOS, this problem does not happen all the times and It can reach sometimes chains of 50000 or 100000 steps, but it continues to happen too many times.

One option is that MP is not able to detect the number of cores of this computer as it has a particular architecture, so if there is a way to tell MP the number of cores and not letting it to detect them it would help?

Any other idea will be very appreciated, thanks everyone!

**Comment by brinckmann** [comment]
Hi David,

This is quite far beyond my expertise, but in principle MontePython should adhere to the number of cores passed with MPI and OMP arguments, e.g.
```
export OMP_NUM_THREADS=4
mpirun -np 4 python montepython/MontePython.py run ...
```
Should launch 4 chains each running on 4 cores. There may be some added complication if you use hyperthreading or virtual cores, which I'm not sure how MontePython would interact with. Also note that when using the Metropolis-Hastings method (default) you can run without MPI by simply launching parallel runs in the same directory and using OMP to control the number of cores used per chain.

Best,
Thejs

**Comment by DavidFigueruelo** [comment]
It was a issue with hyperthreading and using MPI and OMP seems to work, thanks!!
