### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by zhangruipku** [brinckmann/montepython_public#87]
I'm trying to use these following likelihoods: 

data.experiments=['Planck_lowl_TT','Planck_lowl_EE','Planck_highl_TTTEEE','Planck_lensing',"Pantheon"]

I use all the 47 nuisance parameters of planck. And for Pantheon, I copy the nuisance parameters "M" from pantheon.param. But finally an IndexError is returned. 

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/D/zhangrui/montepython_public/montepython/run.py", line 44, in run
    sampler.run(cosmo, data, command_line)
  File "/home/D/zhangrui/montepython_public/montepython/sampler.py", line 44, in run
    mcmc.chain(cosmo, data, command_line)
  File "/home/D/zhangrui/montepython_public/montepython/mcmc.py", line 779, in chain
    data, sigma_eig, U, k, Cholesky, Rotation) is True:
  File "/home/D/zhangrui/montepython_public/montepython/mcmc.py", line 143, in get_new_position
    rd.gauss(0, 1)*data.jumping_factor
IndexError: index 34 is out of bounds for axis 0 with size 34

I have checked that it's ok if I don't add Pantheon or I use only Pantheon. So I guess the problem is too many parameters? But it seems the length of sigma depends dynamically on numbers of parameters. 

Is it correct to use these likelihoods in this way? Thanks!

**Comment by brinckmann** [comment]
Hi,

Do you have all your parameters correctly grouped in the param file, i.e. 'cosmo' followed by 'nuisance', followed by 'derived'? Also make sure the nuisance parameters are grouped by likelihood, i.e. all Planck ones together followed by the Pantheon one.

If none of that works, please copy your param file here.

Best,
Thejs

**Comment by zhangruipku** [comment]
Thank you very much! 
I wrote the parameter 'M' after the Planck parameters... 
It's OK now!
