### ISSUE TITLE
Plotting two models in a single contour plot

### ISSUE THREAD

**Issue by AlejandroJR** [brinckmann/montepython_public#89]
Hi, i'm working on a model that includes some changes on the base inflationary model, now i've made some runs of the standard inflationary model and some other runs of my modified model, the thing is that i want to make a single plot including contours of both models in order to compare the parameters that both models share, is there a way to make it with plot options? or how can i make it?
  
Thanks
Alejandro

**Comment by brinckmann** [comment]
Hi Alejandro,

You just pass both chains directories to MontePython at the same time using the info command:
`python montepython/MontePython.py info chains_dir1 chains_dir2 --no-mean`
The last flag `--no-mean` just removes the dashed lines, which you probably don't need.

Best,
Thejs

**Comment by AlejandroJR** [comment]
Hi Thejs, that was exactly what i wanted to do,
Thank you very much for your quick answer,
Alejandro
