### ISSUE TITLE
Add pantheon likelihood

### ISSUE THREAD

**Issue by kangjg** [brinckmann/montepython_public#9]
Hi,
 How   to add  SNe pantheon likelihood according to JLA likelihood which papers is arxiv.org 1710.00845 ?

**Comment by brinckmann** [comment]
Hi,
You can see how to add likelihoods in MontePython from my talk at the CosmoTools18 school
[https://indico.cern.ch/event/688110/timetable/#20180425](https://indico.cern.ch/event/688110/timetable/#20180425)
and you can find additional material on Julien's website
[https://lesgourg.github.io/courses.html](https://lesgourg.github.io/courses.html)
as well as the MontePython documentation
[https://monte-python.readthedocs.io/en/latest/](https://monte-python.readthedocs.io/en/latest/)

Specifically for the Pantheon likelihood I don't know the details. You will have to follow their instructions in the Appendix A of their paper, which refers to the website
[https://archive.stsci.edu/prepds/ps1cosmo/index.html](https://archive.stsci.edu/prepds/ps1cosmo/index.html)

I hope this helps! Let me know if you manage to add the likelihood and would like to include it in the public MontePython version.

Best,
Thejs

**Comment by kangjg** [comment]
Thanks，I try do.

**Comment by kangjg** [comment]
Respected Prof.  Thejs,
        
        I will appreciate you if you send it ,I haven't added it in montepython with many error  presently.
 
Best,
Kang

**Comment by brinckmann** [comment]
You can download the likelihood at:
https://www.dropbox.com/s/n7k3t10d3er4t98/pantheon.tar.gz?dl=0
Let me know if you encounter any issues.
Best,
Thejs

**Comment by kangjg** [comment]
OK，thanks！

**Comment by brinckmann** [comment]
The Pantheon likelihood has now been added in v3.1.

Best,
Thejs

**Comment by kangjg** [comment]
Thanks！

在2019-02-14 13:49:29，Thejs Brinckmannnotifications@github.com写道：

The Pantheon likelihood has now been added in v3.1.

Best,
Thejs
