### ISSUE TITLE
Log scale in param file?

### ISSUE THREAD

**Issue by DavidFigueruelo** [brinckmann/montepython_public#91]
Hello everyone,

In the model I am exploring with MP, there is one parameter whose boundaries are 0.00001-100. It is clearly a logscale range of values, so I am wondering if in the scale of the .param file instead of 1, there is an option of log scale or in any other part of the code?
Also thinking about the 1-sigma initial proposal can be tricky just to chose it as 0.1 for example, maybe it will not explore all the logarithmic range?

Thank for your help!!!!

**Comment by brinckmann** [comment]
Hi David,

With some minor modification to montepython/data.py you can introduce a log scale for your parameter. See e.g. the example parameters 'f_nadm':
```
            elif elem == 'log10fn':
                self.cosmo_arguments['f_nadm'] = 10**(self.cosmo_arguments[elem])
                del self.cosmo_arguments[elem]
```
Simply replace f_nadm with your parameter and log10fn with some new name of your variable. Then in your param file you put log10fn or the new name and set the boundaries on a log10 scale.

Best,
Thejs

**Comment by DavidFigueruelo** [comment]
Hi, thanks for your help!!

Then just in the param file it should be something like 
`data.parameters['log10fn'] = [-4.0, -6.0,4.0, 0.1,1,   'cosmo']` 
if one want MP to explore f_nadm from 10**-4 to 10**4, no?

Thanks!!!

**Comment by brinckmann** [comment]
Yes, exactly!

**Comment by DavidFigueruelo** [comment]
Thank you!
