### ISSUE TITLE
Dealing with single files in analyze.py: cheese should be ham?

### ISSUE THREAD

**Issue by ahallcosmo** [brinckmann/montepython_public#92]
In the remove_bad_points function of analyze.py, lines 1860-1862 where the case of a single file is dealt with, I believe the lines

bacon = np.copy(cheese[::3, :])
egg = np.copy(cheese[1::3, :])
sausage = np.copy(cheese[2::3, :])

should actually be

bacon = np.copy(ham[::3, :])
egg = np.copy(ham[1::3, :])
sausage = np.copy(ham[2::3, :])

because ham has had non-Markovian and burn-in points removed while cheese contains everything. Thus when bacon, egg and sausage are appended to spam (words I never thought I would write), they have brought with them the burn-in of cheese.

I discovered this when running a single chain with the fake_planck_bluebook data, following the supplied example.param. The header of the fiducial data file data/fake_planck_bluebook_fiducial.dat suggests that the fiducial (i.e. 'true') value of A_s is 2.43e-09. When I analyzed the chain however the best-fit value of A_s was more like 2.16e-09 and many sigma away from 2.43e-09. Additionally the posteriors of tau_reio and A_s were both artificially truncated in the plots, even though no prior boundaries were imposed -- plotting the raw .txt chain values indicated nothing was wrong with the samples. A quick comparison of a model with the best-fit A_s (all other parameters were very close to those in the header of the fiducial data file) visually gave a much better fit to the fiducial data file than 2.43e-09. The input starting mean of the proposal for A_s was 2.42e-09.

I think what has happened is that because the starting position of A_s was so far away from the best-fit, the burn-in featured values of A_s (and hence tau_reio) which were many sigma away from the peak -- since I was only running one chain/file, the above code meant that this burn-in was never discarded and so when binned in the default 20 bins the histograms in A_s and tau_reio were mostly zero (since eventually the chain found its way to the peak and most points are there). The interpolation of the histograms seems to have then caused the truncation I saw. When I substitute cheese for ham as above, the posterior plots all look correct -- I can only assume that data/fake_planck_bluebook_fiducial.dat was in fact generated with 2.16e-09 rather than 2.43e-09.

Best regards,
Alex

**Comment by brinckmann** [comment]
Hi Alex,

Thank you, you are correct, it should be ham rather than cheese (also RIP Terry Jones, thanks for the laughs!). I have fixed this in the shortly upcoming version 3.3.

Best,
Thejs
