### ISSUE TITLE
`mpirun -np 8 python montepython/MontePython.py run` faces "Configuration Error:"

### ISSUE THREAD

**Issue by deltasata** [brinckmann/montepython_public#93]
I have installed Montepython 3.2 with CLASS 2.8.2 on our cluster. 

1. But whenever I try to run multiple chains using:
`mpirun -np 8 python montepython/MontePython.py run -p input/sata_input/base2015.param -o satadru_outputs/24dec_cmb_base2015_sata -N 10000`

I get the following multiple warnings/errors:

Traceback (most recent call last):
  File "montepython/MontePython.py", line 41, in <module>
  File "/caefs/user/satadru/MontePython/montepython_public/montepython/run.py", line 31, in run
    sys.exit(run())
  File "/caefs/user/satadru/MontePython/montepython_public/montepython/run.py", line 31, in run
    custom_command)
  File "/caefs/user/satadru/MontePython/montepython_public/montepython/run.py", line 190, in safe_initialisation
................................many warnings/errors like this from different processes......................................

Configuration Error:
 /|\   No information on Planck15_highl likelihood was found in the
/_o_\  satadru_outputs/24dec_cmb_base2015_sata/log.param file.
       This can result from a failed initialization of a previous run. To solve
       this, you can do a
       ]$ rm -rf satadru_outputs/24dec_cmb_base2015_sata
       Be sure there is noting in it before doing this !

................................many warnings/errors like this from different processes......................................
............................................................................................................................................

**The output directory was not created before the command.** I think the error appears because the first process creats the output directory and the rests find that it already exists. When I just run 1 chain the code does well.
`python montepython/MontePython.py run...` 

I am not sure the warnings described above are affecting my results.

2. With the `mpirun -np 8  .... -N 10000` I expect to have 8 chains with 10000 steps. But in reality I have sometimes 1 chain, sometimes 4 chains...why? Also most of the times, the chains contain too few samples. Even if most of the new proposals are not selected, the old points in the parameter space should be there, is not it? Anyway, my bigger problem is that I am not getting desired number of chains. Has it anything to do with the 1st problem?

**Comment by deltasata** [comment]
Is the following the standard way of running montepython?
1. Run a single short chain with `-p \some.param -o \some\output\directory` at first
2.  Once the log.param is created in `\some\output\directory`, now run with `mpirun -np 100` but now without the  `-p \some.param` option.

Is this the most efficient method? Or, am I still making mistake understanding montepython workflow?

**Comment by Uendert** [comment]
Hello @deltasata ,

Did you have mpi4py install in your cluster? `conda install -c anaconda mpi4py'`
