### ISSUE TITLE
Primordial power spectrum contours

### ISSUE THREAD

**Issue by AlejandroJR** [brinckmann/montepython_public#94]
Hi again, 
As i told in a past issue, i'm working on a modified inflationary model, i already have all my parameters confidence intervals, but now i want to make a plot of the confidence intervals of the primordial power spectrum resulting from my parameters (like this one from Planck) 
![Figures_1TT_fgivenx](https://user-images.githubusercontent.com/36173411/71546267-2eafdd80-2963-11ea-90a4-3ab8bb5175d8.png)
Is there a way of getting this Plot with Montepython?
PD: sorry for asking things that are probably obvius but i'm new on Montepython and i didn't found answers for this at guides.

Thanks again!

Alejandro J.

**Comment by dchooper** [comment]
Hi,

This is not something you can directly get MontePython to do for you, however you can use the chain files to produce a similar plot yourself. One way would be to calculate the chi2 difference that corresponds to 1, 2, and 3 sigma bounds, and use that to parse the chain files (or a subset of them) and find the corresponding points in the chain file. You can then use these points to reconstruct the primordial power spectrum at different confidence levels.

Best,
Deanna
