### ISSUE TITLE
Covariance matrix is not created

### ISSUE THREAD

**Issue by deltasata** [brinckmann/montepython_public#95]
I am using Montepython 3.2. In the documentation, you said:

> If I had been running without a covariance matrix, the results would probably be bad, with a very low acceptance rate
> and few points. It would have however created a covariance matrix chains/planck/lcdm/lcdm.covmat. I can decide to copy it in order to keep track of it even after analysing future runs,
> cp chains/planck/lcdm/lcdm.covmat chains/planck/lcdm/lcdm_run1.covmat

Also:

> The covariance matrix of the run is written in chains/myrun/myrun.covmat. 

However, when I run, no covariance matrix is being created! My command is:
`python montepython/MontePython.py run -p input/sata_input/base2018TTTEEE.param -o chains/sata_outputs/30DEC_BASE2018_SataF_NEW -N 1000 -c covmat/base2018TTTEEE.covmat`

It does not create any covariance matrix, neither it updates the one I used. I am utterly confused.
Please help.

Thank you.

**Comment by AlejandroJR** [comment]
Hi, runs will only create covmat matrix automaticaly if you are using update or superuptade options, also it have some criteria with the acceptance rate, so for example, if superupdate see that your acceptance rate is too low, it will create a new covmat and update your old one,
However, you can manually ask for your covmat when analysing your chains with --want-covmat, for example:
$ python (...)/Montepython.py info chains/yourchain --want-covmat

Hope it helps you

Alejandro J.

**Comment by deltasata** [comment]
Hi,

Thank you.  I was also thinking the same as you said. First of all, this is not consistent with the documentation. Secondly, even if I give the update option, still run is not writing any covmat matrix anywhere. 

I have another question, when I include more parameters in the background, say A,B,C..., should I put the values corresponding to A,B,C... in the covariance matrix? If yes, how do I know the correlation between A,B,C... with the other parameters beforehand?

**Comment by deltasata** [comment]
On a sidetrack I am also facing problems analysing a model where I modified the background. I have 3 more parameters than LCDM. The chains run fine with the base2018TTTEEE.covmat (which of course does not have values of the extra parameters). Now when I run 
`python montepython/MontePython info` I am getting the following error:

`Traceback (most recent call last):
  File "montepython/MontePython.py", line 41, in <module>
    sys.exit(run())
  File "/caefs/user/satadru/MontePython/montepython_public/montepython/run.py", line 31, in run
    custom_command)
  File "/caefs/user/satadru/MontePython/montepython_public/montepython/run.py", line 190, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/caefs/user/satadru/MontePython/montepython_public/montepython/initialise.py", line 58, in initialise
    analyze(command_line)
  File "/caefs/user/satadru/MontePython/montepython_public/montepython/analyze.py", line 148, in analyze
    compute_posterior(information_instances)
  File "/caefs/user/satadru/MontePython/montepython_public/montepython/analyze.py", line 368, in compute_posterior
    info.define_ticks()
  File "/caefs/user/satadru/MontePython/montepython_public/montepython/analyze.py", line 2183, in define_ticks
    if abs(x_range[0]-bounds[0]) < self.span[i]/self.bins:
TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')`

I found that this error is generic when there is subtraction between different data types. But in this context I have no idea how to fix that or suspect where the problems might be. I am pretty sure I modified the CLASS correctly, because I tested that CLASS background results (with the modification) match well with the analytical results.

**Comment by deltasata** [comment]
I went back to `montepython 2.2.2` and run with and without the input covmat. None of the runs write any covmat in the output directory as said in the documentation. It is telling me 
`Step  290  chain  0 : Failed to calculate covariant matrix`
 Now, I don't have any idea how montepython works, sorry.
