### ISSUE TITLE
w0 and Omega_fld was not found in output

### ISSUE THREAD

**Issue by Jimmy022** [brinckmann/montepython_public#96]
Hi,

I'm trying to run Montepython to constrain the w0 parameter of wCDM. But I found that there is no w0 and Omega_fld parameters in the output. I want to ask that what else do I need to modify?

My input file is as follows. I added w0 as "cosmo",  changed the Omega_Lambda in "derived" to Omega_fld, and added the line  "data.cosmo_arguments['Omega_Lambda']     = 0".

# Cosmological parameters list
data.parameters['omega_b']      = [  2.2377,   None, None,      0.015, 0.01, 'cosmo']
data.parameters['omega_cdm']    = [ 0.12010,   None, None,     0.0013,    1, 'cosmo']
data.parameters['100*theta_s']  = [ 1.04110,   None, None,    0.00030,    1, 'cosmo']
data.parameters['ln10^{10}A_s'] = [  3.0447,   None, None,      0.015,    1, 'cosmo']
data.parameters['n_s']          = [  0.9659,   None, None,     0.0042,    1, 'cosmo']
data.parameters['tau_reio']     = [  0.0543,  0.004, None,      0.008,    1, 'cosmo']
data.parameters['w0_fld']       = [      -1,   None, None,       0.05,    1, 'cosmo'] 

# Nuisance parameter list, same call, except the name does not have to be a class name
...

# Derived parameters
data.parameters['z_reio']          = [1, None, None, 0,     1,   'derived']
data.parameters['Omega_fld']      = [1, None, None, 0,     1,   'derived']  
data.parameters['YHe']             = [1, None, None, 0,     1,   'derived']
data.parameters['H0']              = [0, None, None, 0,     1,   'derived']
data.parameters['A_s']             = [0, None, None, 0,  1e-9,   'derived']
data.parameters['sigma8']          = [0, None, None, 0,     1,   'derived']

# Other cosmo parameters (fixed parameters, precision parameters, etc.)

data.cosmo_arguments['sBBN file'] = data.path['cosmo']+'/bbn/sBBN.dat'
data.cosmo_arguments['k_pivot'] = 0.05
data.cosmo_arguments['Omega_Lambda']     = 0

data.cosmo_arguments['N_ur'] = 2.0328
data.cosmo_arguments['N_ncdm'] = 1
data.cosmo_arguments['m_ncdm'] = 0.06
data.cosmo_arguments['T_ncdm'] = 0.71611

data.cosmo_arguments['output'] = 'mPk'
data.cosmo_arguments['P_k_max_h/Mpc'] = 1.

Thanks!
Jimmy

**Comment by brinckmann** [comment]
Hi Jimmy,

Can you make sure you're not running in an old folder with an old log.param? If you create a new directory running with a param file as containing the above I would expect it to work.

Best,
Thejs

**Comment by Jimmy022** [comment]
> Hi Jimmy,
> 
> Can you make sure you're not running in an old folder with an old log.param? If you create a new directory running with a param file as containing the above I would expect it to work.
> 
> Best,
> Thejs

HI Thejs,

Thank you for your quick reply.  I checked and confirmed that I used a new output folder when running the program. The content of log.param file is  the same as the input file. And the .paramnames in the output folder is as follows. No w0 and Omega_fld  at all. It confuse me...

omega_b      10^{-2}\omega_{b } 
omega_cdm    \omega_{cdm } 
100theta_s   100\theta_{s } 
ln10^{10}A_s     ln10^{10}A_{s } 
n_s      n_{s } 
tau_reio     \tau_{reio } 
A_cib_217    A_{cib 217 } 
xi_sz_cib    xi_{sz cib } 
A_sz     A_{sz } 
ps_A_100_100     ps_{A 100 100 } 
ps_A_143_143     ps_{A 143 143 } 
ps_A_143_217     ps_{A 143 217 } 
ps_A_217_217     ps_{A 217 217 } 
ksz_norm     ksz_{norm } 
gal545_A_100     gal545_{A 100 } 
gal545_A_143     gal545_{A 143 } 
gal545_A_143_217     gal545_{A 143 217 } 
gal545_A_217     gal545_{A 217 } 
galf_TE_A_100    galf_{TE A 100 } 
galf_TE_A_100_143    galf_{TE A 100 143 } 
galf_TE_A_100_217    galf_{TE A 100 217 } 
galf_TE_A_143    galf_{TE A 143 } 
galf_TE_A_143_217    galf_{TE A 143 217 } 
galf_TE_A_217    galf_{TE A 217 } 
calib_100T   10^{-3}calib_{100T } 
calib_217T   10^{-3}calib_{217T } 
A_planck     A_{planck } 
z_reio   z_{reio } 
YHe      YHe 
H0   H0 
A_s      10^{-9}A_{s } 
sigma8   \sigma8 

Bests,
Jimmy

**Comment by Jimmy022** [comment]
I later found out that I made the mistake by adding a note after the statement when I modified it in the input file. I wrote the error out for other people who might have made such a mistake.
