### ISSUE TITLE
Imposing a constrain between two parameters

### ISSUE THREAD

**Issue by deltasata** [brinckmann/montepython_public#97]
Hi,

I am using montepython 3.2 with Planck 2018 likelihood. For a particular purpose, I want to fix **$\Omega_b + \Omega_cdm=0.27$** always, so I want just one free parameter among those. I may sample $\Omega_b$ freely and set the value  **$\Omega_cdm=0.27 - \Omega_b$**. Unfortunately, I did not find a way of implementing that in montepython. Is there a simple way of imposing the constrain in montepython that **$\Omega_b + \Omega_cdm=0.27$** always.

I am very new to parameter estimation, so I may be asking silly questions here, sorry! Please help me.

**Comment by brinckmann** [comment]
Hi,

You can add this yourself in `your_montepython_directory/montepython/data.py`, where you can look to do something similar to the parameter `omega_m`, which you can find at lines 802-810. E.g.
```
            elif elem == 'Omega_m':
                Omega_b = self.cosmo_arguments['Omega_b']
                Omega_m = self.cosmo_arguments['Omega_m']
                h = self.cosmo_arguments['h']
                try:
                    omega_nu = self.cosmo_arguments['m_ncdm'] / 93.14
                except:
                    omega_nu = 0.
                self.cosmo_arguments['Omega_cdm'] = Omega_m - Omega_b - omega_nu*h**2
                del self.cosmo_arguments[elem]
```
And then fix in your param file `self.cosmo_arguments['Omega_m'] = 0.27`. For zero neutrino mass this should be what you wanted.

Best,
Thejs

**Comment by deltasata** [comment]
Hi Thejs,

Many thanks for the quick reply. 
1. After doing what you said I am getting an error:
`Configuration Error:
 /|\   You should probably check your prior boundaries... because no valid
/_o_\  starting position was found after 100 tries
`
I sampled Omega_b (and also Omega_cdm) normally (using `data.parameters ['Omega_b'] = [  0.049,      None,  None,      0.0001 , 1, 'cosmo']`). 

2. Another question regarding your comment: `For zero neutrino mass this should be what you wanted.`
Why does this enforce Neutrino mass = 0. I do not want to touch the Neutrino part. All I wanted is to always sample with the constrain that \Omega_b+\Omega_cdm=0.27. So Omega_m=0.27+Neutrino contribution.

Thanks again.

With best regards,
Satadru
