### ISSUE TITLE
Planck likelihood error causing Montepython+Polychord to abort

### ISSUE THREAD

**Issue by ivandebono** [brinckmann/montepython_public#99]
I'm running Montepython with Polychord (--method PC) with Planck 2018 data and likelihoods (plc-3.01). My input parameter file works just fine with Montepython Metropolis-Hastings sampling. 

But running with Polychord produces an error which then causes Montepython to abort the run. The error is due to the values of the cosmological parameters near the edges of the priors space. With Polychord or Nested Sampling, we explore the whole space, hence the error.

Here is the error message:

File "/montepython_public/montepython/MontePython.py", line 40, in <module>
  sys.exit(run())
File "/montepython_public/montepython/run.py", line 44, in run
  sampler.run(cosmo, data, command_line)
File "/montepython_public/montepython/sampler.py", line 51, in run
  pc.run(cosmo, data, command_line)
File "/montepython_public/montepython/PolyChord.py", line 377, in run
  polychord_run(loglike, nDims, nDerived, settings, prior)
File "/.local/lib/python2.7/site-packages/pypolychord-1.16-py2.7-linux-x86_64.egg/pypolychord/__init__.py", line 231, in run_polychord
  settings.seed)
File "/.local/lib/python2.7/site-packages/pypolychord-1.16-py2.7-linux-x86_64.egg/pypolychord/__init__.py", line 192, in wrap_loglikelihood
  logL, phi[:] = loglikelihood(theta)
File "/montepython_public/montepython/PolyChord.py", line 362, in loglike
  logl = sampler.compute_lkl(cosmo, data)
File "/montepython_public/montepython/sampler.py", line 770, in compute_lkl
  value = likelihood.loglkl(cosmo, data)
File "/montepython_public/montepython/likelihood_class.py", line 1048, in loglkl
  lkl = self.clik(tot)[0]
File "lkl.pyx", line 89, in clik.lkl.clik.__call__
clik.lkl.CError: clik_compute(../src/clik.c:391)::ForwardError
distribution_lkl(../src/minipmc/distribution.c:219)::ForwardError
  lklbs_lkl(../src/lklbs.c:219)::ForwardError
    simall_lkl(../src/simall/clik_simall.c:48)::Error -1233 (multipole EE 3 too large (got 0.42259 expected <0.3))

With CAMB+CosmoMC, this error also occurs, but CosmoMC just keeps running. 

Is there any way to tweak MontePython so it ignores the error?

**Comment by brinckmann** [comment]
Hi Ivan,

You should be able to find the relevant line where Planck is called in `montepython/likelihood_class.py` line 1048. Add a try/except where you assign a very large negative (I think) value to `lkl` to reject the point where the Planck likelihood returned an error. E.g.:

```
try:
        lkl = self.clik(tot)[0]
except:
        lkl = -1e30
```
Maybe adding a warning like
`warnings.warn('Planck likelihood returned an error')`
Depending on how elaborate you want to get you can forward the error, pass the cosmological parameters, or only have the except trigger on specific error messages in case something unexpected shows up.

Best,
Thejs

**Comment by ivandebono** [comment]
Hi Thejs,

My solution was very similar:

`
try:
            lkl = self.clik(tot)[0]
  except Exception:
            lkl=-np.inf
`

Adding the warning message is a good idea.

There is another issue though, which might be related. The Planck unbinned (COM_Likelihood_Data-extra-plik-ext_R3.00) TTTEEE likelihoods cannot be run using mpiexec with -np greater than 1.

Are you aware of this? Should I open another issue?

**Comment by brinckmann** [comment]
Hi Ivan,

I have not had any problems using the Planck likelihoods with MPI, but I haven't tried running with the unbinned polarisation likelihood. Note in MontePython MPI governs your number of chains and OMP the number of cores per chain and therefore the number of cores used by Planck. Do you think the problem has something to do with how MontePython is launching chains and calling the Planck likelihood?

Best,
Thejs

**Comment by ivandebono** [comment]
Hi Thejs,

I don't know exactly what is causing the problem. What happens is that the memory used quickly exceeds the available memory (both on a cluster, and on a single processor).

MontePython checks the Planck clik likelihoods once for every chain. So if you run e.g. mpiexec -np 8, this will be done 8 times. This issue referenced here: [https://github.com/brinckmann/montepython_public/issues/70](url)

Perhaps the code could be modified so clik is called just once per run?

Ivan
